/**
 * 资本市场服务解决方案
 * 整合 IPO 上市辅导、并购重组、上市后持续合规、再融资四大服务
 */
import type { SolutionConfig } from '../solution-router'
import { agent } from '../solution-router-agent'

export const capitalMarketsSolution: SolutionConfig = {
  id: 'capital-markets',
  name: '资本市场服务解决方案',
  icon: '🏛️',
  color: '#b45309',
  tagline: '一个方案覆盖上市公司全生命周期 — IPO辅导、并购重组、持续信披、再融资',
  description:
    '整合 IPO 上市辅导、并购重组、上市后持续合规、再融资四大资本市场服务，覆盖 Pre-IPO 企业、已上市公司、PE/VC 和投行的全生命周期需求。调用 Finance + Legal + Invest Agent，零新建后端，一个方案串联资本市场全流程。',
  entrepreneurPurpose: '让同一个 FA 团队同时服务 5 倍项目 — IPO 辅导从 3 个月变 3 周，并购尽调从 6 周变 1 周',
  profitMetrics: [
    'IPO 合规诊断 3 天→2 小时，单项目节省分析师 20 人天',
    '并购 IM 起草 3 周→3 天，FA 可同时承接 3 倍项目',
    '上市后季报信披 2 天→4 小时，董秘从内容生产者变为审核者',
  ],
  valueEquivalent: { humanHours: 480, mbeMinutes: 200, acceleration: '12x' },
  agents: [
    agent('finance', 8002, 'IPO 顾问', 'IPO 辅导 / 板块适配评估 / 合规诊断 / 再融资方案设计'),
    agent('finance', 8002, '财务尽调专家', '财务尽调 / 合并报表 / 估值建模 / LBO/DCF / 信披报告生成'),
    agent('finance', 8002, '税务顾问', '股权税务 / VIE 重组税务 / 并购税务规划'),
    agent('legal', 8003, '资本市场律师', '法律尽调 / 合规审查 / 法律意见书 / 监管申报'),
    agent('legal', 8003, '并购合同专家', '并购协议 / 对赌 / 锁定期 / 信披文件审查'),
    agent('invest', 8011, '投资分析师', '估值建模 / 行业对标 / 标的筛选 / 宏观信号'),
  ],
  localScripts: ['calc_iit', 'calc_vat', 'calc_litigation_fee'],
  knowledgeCache: ['ipo_conditions', 'ma_regulations', 'disclosure_rules', 'securities_law', 'valuation_methods'],
  theme: { primary: '35 80% 35%', accent: '35 80% 45%', sidebarBg: '35 15% 7%' },
  enabledTabs: [
    'today', 'ipo-prep', 'business-plan', 'contracts', 'legal-docs',
    'research', 'macro', 'documents', 'tools', 'chat',
    'workflows', 'tasks', 'dashboard', 'roi', 'knowledge-graph',
  ],
  onboarding: {
    questions: [
      {
        key: 'client_type',
        label: '主要服务对象',
        options: ['Pre-IPO 企业', '已上市公司（董秘/证代）', 'PE/VC 机构', 'M&A 财务顾问（FA）', '投行 IPO 项目组'],
      },
      {
        key: 'primary_service',
        label: '核心业务',
        options: ['IPO 上市辅导', '并购重组顾问', '上市后合规服务', '再融资方案', '综合资本市场服务'],
      },
      {
        key: 'deal_size',
        label: '典型项目规模',
        options: ['< 1 亿', '1–10 亿', '10–100 亿', '> 100 亿'],
      },
    ],
  },
  tools: [
    {
      id: 'ipo-board-match',
      type: 'calculator',
      name: 'IPO 板块适配评估',
      icon: '📊',
      agent: 'finance',
      apiPath: '/api/finance/ipo/board-match',
      description: '输入企业财务指标，5 分钟内评估主板/创业板/科创板/北交所适配度，输出推荐板块与差距整改清单',
      fields: [
        { key: 'revenue_3y', label: '近三年营业收入（万元，逗号分隔）', type: 'text', required: true, array: true, arraySeparator: ',' },
        { key: 'net_profit_3y', label: '近三年净利润（万元，逗号分隔）', type: 'text', required: true, array: true, arraySeparator: ',' },
        { key: 'market_cap_estimate', label: '预计市值（万元）', type: 'currency', required: true },
        { key: 'founded_years', label: '成立年限', type: 'number', required: true },
        { key: 'industry', label: '行业', type: 'text', required: true },
        { key: 'has_rd', label: '是否高新/科技企业', type: 'select', required: true,
          options: [{ value: 'yes', label: '是' }, { value: 'no', label: '否' }] },
      ],
    },
    {
      id: 'ipo-compliance-check',
      type: 'document-ai',
      name: 'IPO 合规诊断',
      icon: '🔍',
      agent: 'finance',
      apiPath: '/api/finance/ipo/compliance-check',
      description: '上传企业基本资料，AI 并行检查股权架构、关联交易、财务规范、税务合规、业务资质 5 大维度，输出红/黄/绿三色整改清单',
      acceptTypes: ['.pdf', '.docx', '.xlsx'],
      fields: [
        { key: 'target_board', label: '目标上市板块', type: 'select', required: true,
          options: [
            { value: 'main', label: '主板' }, { value: 'chinext', label: '创业板' },
            { value: 'star', label: '科创板' }, { value: 'bse', label: '北交所' },
            { value: 'hk', label: '港交所' },
          ] },
      ],
    },
    {
      id: 'valuation-model',
      type: 'calculator',
      name: '并购估值计算',
      icon: '💰',
      agent: 'invest',
      apiPath: '/api/invest/valuation',
      description: 'DCF / EV-EBITDA / 可比交易三种方法估值，输出估值区间与敏感性分析表格',
      fields: [
        { key: 'method', label: '估值方法', type: 'select', required: true,
          options: [
            { value: 'dcf', label: 'DCF 现金流折现' },
            { value: 'ebitda', label: 'EV/EBITDA 倍数法' },
            { value: 'comparable', label: '可比公司法' },
          ] },
        { key: 'ebitda', label: 'EBITDA（万元）', type: 'currency', required: true },
        { key: 'revenue', label: '营业收入（万元）', type: 'currency', required: true },
        { key: 'net_profit', label: '净利润（万元）', type: 'currency', required: true },
        { key: 'industry', label: '所属行业', type: 'text', required: true },
        { key: 'growth_rate', label: '预期增速（%）', type: 'number', required: true },
        { key: 'wacc', label: 'WACC 折现率（%，DCF用）', type: 'number', default: 12 },
      ],
    },
    {
      id: 'bp-writer',
      type: 'document-ai',
      name: '融资 BP 写作',
      icon: '🚀',
      agent: 'finance',
      apiPath: '/api/finance/bp/plans',
      description: '智能生成融资商业计划书（天使/A/B/C轮），14章全文初稿 + 占位符清单 + Word/PDF 双格式导出，2周工作量压缩到3小时',
      fields: [
        { key: 'round', label: '融资轮次', type: 'select', required: true,
          options: [
            { value: 'angel', label: '天使轮（7章精简版）' },
            { value: 'pre-a', label: 'Pre-A 轮' },
            { value: 'series-a', label: 'A 轮（14章完整版）' },
            { value: 'series-b', label: 'B/C 轮及以上' },
          ] },
        { key: 'industry', label: '行业', type: 'text', required: true },
        { key: 'target_amount', label: '融资金额（万元）', type: 'currency', required: true },
        { key: 'company_stage', label: '公司阶段', type: 'select', required: true,
          options: [
            { value: 'idea', label: '创意期（无收入）' },
            { value: 'mvp', label: 'MVP（初步收入）' },
            { value: 'growth', label: '成长期（规模化中）' },
            { value: 'scale', label: '扩张期（盈利稳定）' },
          ] },
      ],
    },
    {
      id: 'ma-screening',
      type: 'document-ai',
      name: '并购标的筛选',
      icon: '🔎',
      agent: 'invest',
      apiPath: '/api/invest/ma/screening',
      description: '基于战略目标批量筛选并购标的，输出评分矩阵+短名单报告（≤10个标的）+初步接触策略',
      acceptTypes: ['.xlsx', '.pdf'],
      fields: [
        { key: 'industry_focus', label: '目标行业', type: 'text', required: true },
        { key: 'size_range', label: '标的规模范围（万元营收）', type: 'text', required: true },
        { key: 'strategic_goal', label: '并购战略目标', type: 'select', required: true,
          options: [
            { value: 'horizontal', label: '横向整合（同行业扩规模）' },
            { value: 'vertical', label: '纵向整合（上下游）' },
            { value: 'diversify', label: '多元化（新业务/新市场）' },
            { value: 'tech', label: '技术/IP 获取' },
          ] },
      ],
    },
    {
      id: 'due-diligence',
      type: 'document-ai',
      name: '财法双轨尽调',
      icon: '📋',
      agent: 'finance',
      apiPath: '/api/finance/ma/due-diligence',
      description: 'Finance + Legal 并行执行，6周→1周，输出财务尽调报告+法律尽调报告+Red Flag清单+合规风险矩阵',
      acceptTypes: ['.pdf', '.docx', '.xlsx'],
      fields: [
        { key: 'target_name', label: '标的公司名称', type: 'text', required: true },
        { key: 'deal_type', label: '交易类型', type: 'select', required: true,
          options: [
            { value: 'full', label: '全资收购' }, { value: 'majority', label: '控股收购' },
            { value: 'minority', label: '参股投资' },
          ] },
        { key: 'focus_area', label: '重点关注领域', type: 'select', required: true,
          options: [
            { value: 'financial', label: '财务为主' }, { value: 'legal', label: '法律为主' },
            { value: 'both', label: '财法并重' },
          ] },
      ],
    },
    {
      id: 'disclosure-report',
      type: 'document-ai',
      name: '定期报告信息披露',
      icon: '📄',
      agent: 'finance',
      apiPath: '/api/finance/disclosure/periodic',
      description: '年报/季报/半年报核心数据自动汇总分析 + MD&A草稿生成 + 信披合规审查 + 完整报告输出，2天→4小时',
      acceptTypes: ['.xlsx', '.csv'],
      fields: [
        { key: 'report_type', label: '报告类型', type: 'select', required: true,
          options: [
            { value: 'annual', label: '年度报告' }, { value: 'semi', label: '半年度报告' },
            { value: 'quarter', label: '季度报告' },
          ] },
        { key: 'period', label: '报告期间', type: 'text', required: true },
        { key: 'exchange', label: '上市交易所', type: 'select', required: true,
          options: [
            { value: 'sse', label: '上海证券交易所' }, { value: 'szse', label: '深圳证券交易所' },
            { value: 'hkex', label: '香港交易所' }, { value: 'nyse', label: '纽交所/纳斯达克' },
          ] },
      ],
    },
    {
      id: 'related-party-check',
      type: 'calculator',
      name: '关联交易合规审查',
      icon: '🔗',
      agent: 'legal',
      apiPath: '/api/legal/disclosure/related-party',
      description: '穿透股权识别所有关联方，定价公允性评估，判断审批阈值，自动生成披露文件，3天→4小时',
      fields: [
        { key: 'transaction_type', label: '关联交易类型', type: 'select', required: true,
          options: [
            { value: 'goods', label: '购销商品/原材料' }, { value: 'service', label: '提供/接受服务' },
            { value: 'loan', label: '关联方资金往来' }, { value: 'guarantee', label: '担保' },
            { value: 'license', label: '知识产权许可' },
          ] },
        { key: 'amount', label: '交易金额（万元）', type: 'currency', required: true },
        { key: 'proportion', label: '占上年净资产比例（%）', type: 'number', required: true },
      ],
    },
    {
      id: 'refinancing-design',
      type: 'calculator',
      name: '再融资方案设计',
      icon: '💹',
      agent: 'finance',
      apiPath: '/api/finance/refinancing/design',
      description: '定增/可转债/配股三方案对比，EPS摊薄分析，资格核查，申报文件清单，3周→3天',
      fields: [
        { key: 'instrument', label: '融资工具', type: 'select', required: true,
          options: [
            { value: 'private', label: '非公开发行（定增）' },
            { value: 'convertible', label: '可转换公司债券' },
            { value: 'rights', label: '配股' },
            { value: 'compare', label: '三方案对比' },
          ] },
        { key: 'amount', label: '计划融资规模（万元）', type: 'currency', required: true },
        { key: 'purpose', label: '募集资金用途', type: 'textarea', required: true },
        { key: 'current_shares', label: '当前总股本（万股）', type: 'number', required: true },
        { key: 'net_assets', label: '最近一期净资产（万元）', type: 'currency', required: true },
      ],
    },
    {
      id: 'announcement-draft',
      type: 'document-ai',
      name: '重大事项临时公告',
      icon: '📢',
      agent: 'legal',
      apiPath: '/api/legal/disclosure/announcement',
      description: '重大事项判断 + 公告草稿自动生成 + 财务影响量化 + 内幕窗口期合规核查，1天→2小时',
      fields: [
        { key: 'event_type', label: '事项类型', type: 'select', required: true,
          options: [
            { value: 'acquisition', label: '重大资产收购' }, { value: 'disposal', label: '重大资产出售' },
            { value: 'lawsuit', label: '重大诉讼仲裁' }, { value: 'contract', label: '重大合同签署' },
            { value: 'profit_warning', label: '业绩预警' }, { value: 'executive', label: '高管变动' },
            { value: 'equity', label: '股权变动/增减持' }, { value: 'other', label: '其他重大事项' },
          ] },
      ],
      acceptTypes: ['.pdf', '.docx'],
    },
  ],
  slashCommands: [
    { cmd: '/IPO评估', label: 'IPO 板块适配评估', icon: '📊', toolId: 'ipo-board-match' },
    { cmd: '/IPO合规', label: 'IPO 合规诊断', icon: '🔍', toolId: 'ipo-compliance-check' },
    { cmd: '/估值', label: '并购估值计算', icon: '💰', toolId: 'valuation-model' },
    { cmd: '/BP', label: '融资 BP 写作', icon: '🚀', toolId: 'bp-writer' },
    { cmd: '/商业计划书', label: '融资 BP 写作', icon: '🚀', toolId: 'bp-writer' },
    { cmd: '/并购筛选', label: '并购标的筛选', icon: '🔎', toolId: 'ma-screening' },
    { cmd: '/尽调', label: '财法双轨尽调', icon: '📋', toolId: 'due-diligence' },
    { cmd: '/信披', label: '定期报告信息披露', icon: '📄', toolId: 'disclosure-report' },
    { cmd: '/关联交易', label: '关联交易合规审查', icon: '🔗', toolId: 'related-party-check' },
    { cmd: '/再融资', label: '再融资方案设计', icon: '💹', toolId: 'refinancing-design' },
    { cmd: '/公告', label: '重大事项临时公告', icon: '📢', toolId: 'announcement-draft' },
    { cmd: '/IPO', label: 'IPO 全流程辅导', icon: '🏛️', description: '启动 IPO 上市辅导工作流' },
    { cmd: '/并购', label: '并购重组全流程', icon: '🤝', description: '启动并购重组工作流' },
  ],
  safetyRules: [
    { id: 'no-guarantee', label: '上市/融资结果不承诺', trigger: '回复含"保证上市""一定融到"等用语', action: '插入免责声明' },
    { id: 'material-info-control', label: '内幕信息控制', trigger: '涉及未公开重大事项', action: '提示内幕信息管理合规要求' },
    { id: 'valuation-range', label: '估值区间声明', trigger: '输出估值结果', action: '注明估值为参考区间，非市场报价' },
    { id: 'legal-opinion-disclaimer', label: '法律意见书须专业签章', trigger: '法律意见书类文件输出', action: '标注"草稿需律师签章，不得直接使用"' },
    { id: 'disclosure-timeliness', label: '信披时效预警', trigger: '重大事项发生后', action: '提示法定披露时限（2 个交易日内）' },
    { id: 'related-party-pricing', label: '关联交易公允性', trigger: '关联交易定价低于/高于市场价 10% 以上', action: '触发独立财务顾问意见建议' },
    { id: 'antitrust-trigger', label: '反垄断申报触发', trigger: '并购交易额超过申报阈值', action: '提示 SAMR 反垄断申报必要性' },
    { id: 'window-period-check', label: '窗口期合规检查', trigger: '定期报告披露前后 30 天', action: '标注股票交易窗口期限制' },
  ],
  quickActions: [
    { id: 'ipo-assess', label: 'IPO 板块评估', icon: '📊', workflowId: 'ipo_board_matching', description: '5分钟评估最优上市板块', cta: '立即评估' },
    { id: 'ipo-diagnose', label: 'IPO 合规诊断', icon: '🔍', workflowId: 'ipo_compliance_diagnosis', description: '3天→2小时，红/黄/绿三色整改清单', cta: '开始诊断' },
    { id: 'bp-write', label: '融资 BP 写作', icon: '🚀', workflowId: 'capital_market_readiness', description: '2周→3小时，14章完整初稿', cta: '开始写作' },
    { id: 'ipo-legal', label: 'IPO 法律支持', icon: '⚖️', workflowId: 'ipo_legal_support', description: '3~4周→1天，法律意见书框架', cta: '启动支持' },
    { id: 'ma-screen', label: '并购标的筛选', icon: '🔎', workflowId: 'ma_target_screening', description: '2周→4小时，短名单报告', cta: '开始筛选' },
    { id: 'ma-dd', label: '财法双轨尽调', icon: '📋', workflowId: 'ma_due_diligence', description: '6周→1周，双轨并行执行', cta: '启动尽调' },
    { id: 'ma-structure', label: '并购方案设计', icon: '🏗️', workflowId: 'ma_deal_structuring', description: '3周→3天，SPA/对赌/融资结构', cta: '开始设计' },
    { id: 'ma-closing', label: '监管申报交割', icon: '📋', workflowId: 'ma_regulatory_closing', description: '申报文件+信披公告+CP Checklist', cta: '准备申报' },
    { id: 'disclosure', label: '定期报告信披', icon: '📄', workflowId: 'disclosure_periodic_report', description: '2天→4小时，季报/年报自动生成', cta: '生成报告' },
    { id: 'announcement', label: '临时公告起草', icon: '📢', workflowId: 'material_event_announcement', description: '1天→2小时，合规公告草稿', cta: '起草公告' },
    { id: 'related-party', label: '关联交易审查', icon: '🔗', workflowId: 'related_party_review', description: '3天→4小时，穿透识别+披露', cta: '开始审查' },
    { id: 'refinancing', label: '再融资方案', icon: '💹', workflowId: 'refinancing_design', description: '3周→3天，三方案摊薄对比', cta: '设计方案' },
  ],
  workflows: [
    {
      id: 'capital_market_readiness',
      name: '融资 BP 写作服务',
      icon: '🚀',
      description: '天使/A/B轮融资商业计划书全文生成，2周工作量压缩至3小时',
      mode: 'sequential',
      deliverable: '14章融资 BP 初稿（Word + PDF）+ 占位符清单 + 股权合规标注',
      successCriteria: [
        'BP 覆盖执行摘要/市场/商业模式/竞争/财务预测等全章',
        '财务章节注入历史数据，税务架构建议完整',
        '股权结构描述经法律专家合规审查',
        '双格式导出，占位符清单无遗漏',
      ],
      steps: [
        { id: 'stage_match', agent: 'finance', expert: 'ipo_advisor', label: '融资阶段判断',
          goal: '确认融资轮次，选择对应 BP 模板', successCriteria: ['天使选7章/A轮以上选14章', '行业适配确认'],
          profitImpact: { dimension: 'revenue', amount: 'BP 写作服务单价 3–10 万，3小时完成' } },
        { id: 'draft_gen', agent: 'finance', expert: 'finance_accountant', label: 'AI 批量生成初稿',
          goal: '生成执行摘要/公司概况/市场/竞争/商业模式等全章', successCriteria: ['各章节逻辑连贯', '内容达标'],
          profitImpact: { dimension: 'cost_saving', amount: '2 周工作量→3 小时' } },
        { id: 'financial_inject', agent: 'finance', expert: 'tax_consultant', label: '财务数据与税务架构注入',
          goal: '历史财务数据和税务优化建议嵌入财务章节', successCriteria: ['三年历史数据填入', '税务效率建议完整'],
          profitImpact: { dimension: 'revenue', amount: '数据驱动的 BP 说服力更强' } },
        { id: 'legal_review', agent: 'legal', expert: 'civil_lawyer', label: '股权合规校验',
          goal: '核查股权结构描述合规，标注对赌/回购/反稀释风险', successCriteria: ['股权无法律风险', '对赌条款风险标注完整'],
          profitImpact: { dimension: 'loss_avoidance', amount: '提前发现股权法律风险，避免融资失败' } },
        { id: 'export', agent: 'finance', expert: 'finance_accountant', label: '导出与占位符清单',
          goal: '输出 Word/PDF 并生成待补充占位符列表', successCriteria: ['双格式导出成功', '占位符清单无遗漏'],
          profitImpact: { dimension: 'cost_saving', amount: '专业格式交付提升客户信任度' } },
      ],
      triggerPhrases: ['融资BP', '商业计划书', '天使轮', 'A轮', '融资材料', '路演材料'],
    },
    {
      id: 'ipo_board_matching',
      name: 'IPO 板块适配评估',
      icon: '📊',
      description: '5分钟评估主板/创业板/科创板/北交所适配度，输出最优推荐与整改时间表',
      mode: 'sequential',
      deliverable: '板块适配报告（最优推荐 + 差距分析 + 整改时间表）',
      successCriteria: ['四大板块逐项对比完成', '满足/不满足/接近三态标注清晰', '整改时间表可执行'],
      steps: [
        { id: 'collect', agent: 'finance', expert: 'ipo_advisor', label: '财务指标采集',
          goal: '采集营收/利润/市值/成立年限/股东人数等关键指标',
          successCriteria: ['关键指标完整', '数据真实性确认'],
          profitImpact: { dimension: 'cost_saving', amount: '2小时人工评估→5分钟' } },
        { id: 'board_compare', agent: 'finance', expert: 'ipo_advisor', label: '板块条件逐项对比',
          goal: '对比主板/创业板/科创板/北交所上市条件，标注达标状态',
          successCriteria: ['所有板块覆盖', '达标/未达标/接近三态标注'],
          profitImpact: { dimension: 'revenue', amount: 'IPO 辅导服务单价 50–200 万' } },
        { id: 'legal_prescreen', agent: 'legal', expert: 'civil_lawyer', label: '法律合规预筛',
          goal: '检查股权清晰度、关联交易、实控人认定等法律合规前提',
          successCriteria: ['股权结构评估完整', '法律风险初步识别'],
          profitImpact: { dimension: 'loss_avoidance', amount: '提前发现法律障碍，节省整改时间' } },
        { id: 'report_gen', agent: 'finance', expert: 'ipo_advisor', label: '推荐报告生成',
          goal: '输出最优板块建议 + 差距分析 + 整改时间表',
          successCriteria: ['推荐板块有理有据', '整改项优先级排序', '时间表可执行'],
          profitImpact: { dimension: 'revenue', amount: '专业报告直接用于客户提案' } },
      ],
      triggerPhrases: ['IPO板块', '上市评估', '科创板', '创业板', '北交所适合吗', '能不能上市'],
    },
    {
      id: 'ipo_compliance_diagnosis',
      name: 'IPO 合规诊断',
      icon: '🔍',
      description: '5大维度并行诊断，3天→2小时，红/黄/绿三色整改优先级清单',
      mode: 'parallel',
      deliverable: '合规诊断报告（5维度红/黄/绿评级 + 整改优先级清单）',
      successCriteria: ['5大维度全覆盖', '红色问题需立即整改', '绿色已达标', '清单可操作'],
      steps: [
        { id: 'equity_check', agent: 'legal', expert: 'civil_lawyer', label: '股权架构检查',
          goal: '核查历史沿革/代持/期权池/员工持股平台',
          successCriteria: ['代持关系识别完整', '期权池规范性确认'],
          profitImpact: { dimension: 'loss_avoidance', amount: '提前发现股权问题节省整改周期 6–12 月' } },
        { id: 'related_party_check', agent: 'legal', expert: 'civil_lawyer', label: '关联交易合规评估',
          goal: '识别利益输送风险，评估定价公允性',
          successCriteria: ['关联交易清单完整', '定价公允性评估有依据'],
          profitImpact: { dimension: 'loss_avoidance', amount: '关联交易问题是上会被否主因之一' } },
        { id: 'finance_check', agent: 'finance', expert: 'finance_accountant', label: '三年财务规范性检查',
          goal: '核查收入确认、毛利率稳定性、现金流质量',
          successCriteria: ['三年数据完整', '异常波动识别并有解释', '收入确认准则合规'],
          profitImpact: { dimension: 'loss_avoidance', amount: '财务问题整改可提前 12 个月完成' } },
        { id: 'tax_check', agent: 'finance', expert: 'tax_consultant', label: '税务合规排查',
          goal: '排查补税风险/稽查记录/税优资质有效性',
          successCriteria: ['近三年税务合规', '稽查风险量化', '税优资质确认'],
          profitImpact: { dimension: 'loss_avoidance', amount: '提前补税补证，避免上市前临时补缴' } },
        { id: 'business_check', agent: 'legal', expert: 'civil_lawyer', label: '业务合规核查',
          goal: '逐项检查经营资质/知识产权/环保/劳动合规',
          successCriteria: ['经营资质齐全', '知产权属清晰', '重大违规无遗漏'],
          profitImpact: { dimension: 'loss_avoidance', amount: '业务合规缺陷可导致 IPO 中止' } },
        { id: 'report_gen', agent: 'finance', expert: 'ipo_advisor', label: '合规报告汇总',
          goal: '输出红/黄/绿三色评级 + 整改优先级清单',
          successCriteria: ['5维度全部覆盖', '整改优先级合理', '时间表明确'],
          profitImpact: { dimension: 'cost_saving', amount: '3 天诊断→2 小时，节省 2 名分析师 20 人天' } },
      ],
      triggerPhrases: ['IPO合规', '合规诊断', '上市前检查', '股权清晰', '关联交易合规'],
    },
    {
      id: 'ipo_legal_support',
      name: 'IPO 上市法律支持',
      icon: '⚖️',
      description: '法律尽调 + 合规核查 + 法律文件起草，3~4周→1天',
      mode: 'sequential',
      deliverable: '法律意见书框架 + 律师工作报告初稿 + 保荐协议审查意见',
      successCriteria: ['股权合规地图完整', '法律文件初稿可用', '合规核查红/黄/绿'],
      steps: [
        { id: 'equity_map', agent: 'legal', expert: 'civil_lawyer', label: '股权架构梳理',
          goal: '梳理历史股权沿革，输出整改建议清单',
          successCriteria: ['沿革完整', '代持/期权/持股平台全覆盖'],
          profitImpact: { dimension: 'cost_saving', amount: '律师梳理时间从 1 周→2 小时' } },
        { id: 'related_party', agent: 'legal', expert: 'civil_lawyer', label: '关联交易评估',
          goal: '识别隐性关联方，输出披露清单与整改路径',
          successCriteria: ['隐性关联方识别完整', '定价公允性有据'],
          profitImpact: { dimension: 'loss_avoidance', amount: '关联交易披露完整，降低问询函风险' } },
        { id: 'compliance_map', agent: 'legal', expert: 'civil_lawyer', label: '业务合规核查',
          goal: '逐项核查资质/知产/环保/劳动，生成合规地图',
          successCriteria: ['红/黄/绿地图完整', '整改优先级明确'],
          profitImpact: { dimension: 'loss_avoidance', amount: '全面合规核查，避免审核中止' } },
        { id: 'legal_docs', agent: 'legal', expert: 'contract_reviewer', label: '法律文件起草',
          goal: '生成法律意见书框架、律师工作报告初稿、决议模板',
          successCriteria: ['文件框架符合规范', '法律意见书引用相关法规'],
          profitImpact: { dimension: 'cost_saving', amount: '文件起草 2 周→4 小时' } },
        { id: 'agreement_review', agent: 'legal', expert: 'contract_reviewer', label: '保荐/承销协议审查',
          goal: '逐条审查对赌/回购/反稀释条款，标注谈判要点',
          successCriteria: ['高风险条款标注完整', '谈判策略明确'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免不利条款锁定，保护创始人权益' } },
        { id: 'disclosure_check', agent: 'legal', expert: 'civil_lawyer', label: '信息披露合规审查',
          goal: '比对最新信披规则，生成修改意见清单',
          successCriteria: ['逐项与最新规则对照', '修改意见可执行'],
          profitImpact: { dimension: 'loss_avoidance', amount: '信披合规避免问询函和退回' } },
      ],
      triggerPhrases: ['上市法律', 'IPO法律', '法律意见书', '保荐协议', '招股书'],
    },
    {
      id: 'ma_target_screening',
      name: '并购标的筛选',
      icon: '🔎',
      description: '基于战略目标并行扫描，2周→4小时，输出评分矩阵+短名单（≤10个）',
      mode: 'parallel',
      deliverable: '标的短名单报告（评分矩阵 + ≤10个标的 + 接触策略）',
      successCriteria: ['筛选标准清晰', '长名单覆盖充分', '短名单优先级明确'],
      steps: [
        { id: 'criteria', agent: 'invest', expert: 'investment_analyst', label: '筛选标准设定',
          goal: '基于战略目标生成标的筛选标准',
          successCriteria: ['行业/规模/盈利/协同效应标准量化'],
          profitImpact: { dimension: 'revenue', amount: '战略匹配的并购协同价值 > 溢价成本' } },
        { id: 'market_scan', agent: 'invest', expert: 'investment_analyst', label: '市场扫描与长名单',
          goal: '生成行业 map + 潜在标的长名单 + 初步估值区间',
          successCriteria: ['上市/非上市标的均覆盖', '初步估值区间合理'],
          profitImpact: { dimension: 'cost_saving', amount: '市场扫描 2 周→2 小时' } },
        { id: 'financial_screen', agent: 'finance', expert: 'finance_accountant', label: '财务快筛',
          goal: '收入增速/毛利/负债率/现金流质量快速筛选',
          successCriteria: ['明显不符合项淘汰有据', '财务快筛覆盖全部长名单'],
          profitImpact: { dimension: 'cost_saving', amount: '财务快筛避免浪费完整尽调资源' } },
        { id: 'legal_screen', agent: 'legal', expert: 'civil_lawyer', label: '合规快筛',
          goal: '重大诉讼/监管处罚/股权纠纷风险信号标注',
          successCriteria: ['重大法律风险识别', '风险信号标注清晰'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免收购有重大法律瑕疵的标的' } },
        { id: 'shortlist', agent: 'invest', expert: 'investment_analyst', label: '短名单报告',
          goal: '输出≤10个标的评分矩阵+推荐优先级+初步接触策略',
          successCriteria: ['评分矩阵维度完整', '推荐理由充分', '接触策略可执行'],
          profitImpact: { dimension: 'revenue', amount: '并购顾问服务单价 50–500 万' } },
      ],
      triggerPhrases: ['并购标的', '收购目标', '并购筛选', '战略并购', '寻找收购目标'],
    },
    {
      id: 'ma_due_diligence',
      name: '财务与法律双轨尽调',
      icon: '📋',
      description: 'Finance + Legal 并行，6周→1周，双轨报告+Red Flag清单',
      mode: 'parallel',
      deliverable: '财务尽调报告 + 法律尽调报告 + Red Flag 清单 + 合规风险矩阵',
      successCriteria: ['财务/税务尽调覆盖三年历史', '法律尽调章程/股权/合同全覆盖', 'Red Flag 逐项量化'],
      steps: [
        { id: 'financial_dd', agent: 'finance', expert: 'finance_accountant', label: '财务尽调',
          goal: '三年历史财务数据审查（收入质量/成本/运营资本）',
          successCriteria: ['收入质量分析完整', '异常波动解释充分'],
          profitImpact: { dimension: 'cost_saving', amount: '财务尽调 3 周→3 天' } },
        { id: 'tax_dd', agent: 'finance', expert: 'tax_consultant', label: '税务尽调',
          goal: '税务历史/未决风险/递延税务资产合理性审查',
          successCriteria: ['历史税务处理记录完整', '潜在税务风险量化'],
          profitImpact: { dimension: 'loss_avoidance', amount: '发现隐藏税务风险，调整交易估值' } },
        { id: 'valuation', agent: 'finance', expert: 'finance_accountant', label: '估值模型',
          goal: '构建 LBO/DCF 模型，输出估值区间和敏感性分析',
          successCriteria: ['三种方法估值结果交叉验证', '敏感性分析完整'],
          profitImpact: { dimension: 'revenue', amount: '客观估值支持谈判，避免溢价过高' } },
        { id: 'legal_dd', agent: 'legal', expert: 'civil_lawyer', label: '法律尽调',
          goal: '公司章程/股权/重大合同/知产/诉讼/监管合规逐项核查',
          successCriteria: ['重大合同全覆盖', '未决诉讼量化', '知产权属清晰'],
          profitImpact: { dimension: 'loss_avoidance', amount: '法律瑕疵发现后可调价或放弃交易' } },
        { id: 'contract_review', agent: 'legal', expert: 'contract_reviewer', label: '重大合同梳理',
          goal: '识别变更控制条款、合同转让限制、竞业条款',
          successCriteria: ['高风险条款逐条标注', '变更控制条款覆盖完整'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免收购后合同无效损失' } },
        { id: 'synergy', agent: 'finance', expert: 'finance_accountant', label: '协同效应量化',
          goal: '成本节约+收入协同估算，整合成本和时间表',
          successCriteria: ['协同效应量化可信', '整合成本估算合理'],
          profitImpact: { dimension: 'revenue', amount: '协同效应是溢价支付的核心依据' } },
        { id: 'red_flag', agent: 'finance', expert: 'finance_accountant', label: '尽调报告（财务+税务）',
          goal: '输出尽调报告并列 Red Flag 清单',
          successCriteria: ['报告结构完整', 'Red Flag 按严重程度分级'],
          profitImpact: { dimension: 'cost_saving', amount: '6 周工作→1 周' } },
        { id: 'legal_report', agent: 'legal', expert: 'civil_lawyer', label: '尽调报告（法律）',
          goal: '输出法律尽调报告+合规风险矩阵',
          successCriteria: ['法律风险逐项评级', '合规风险矩阵完整'],
          profitImpact: { dimension: 'cost_saving', amount: '法律尽调从 3 周→4 天' } },
      ],
      triggerPhrases: ['尽调', '并购尽调', '财务尽调', '法律尽调', 'due diligence', 'DD'],
    },
    {
      id: 'ma_deal_structuring',
      name: '并购方案设计',
      icon: '🏗️',
      description: '交易架构 + 税务规划 + 估值谈判 + SPA起草 + 融资方案，3周→3天',
      mode: 'sequential',
      deliverable: '交易架构推荐 + 并购协议关键条款框架 + 融资方案 + 监管审批路径',
      successCriteria: ['交易架构对比完整', 'SPA关键条款框架可用', '融资方案利息覆盖比合理'],
      steps: [
        { id: 'structure', agent: 'finance', expert: 'finance_accountant', label: '交易架构设计',
          goal: '现金/股票/混合/LBO方案税务效率+控制权影响对比',
          successCriteria: ['五种架构全部评估', '推荐方案理由充分'],
          profitImpact: { dimension: 'cost_saving', amount: '方案设计 3 周→3 天' } },
        { id: 'tax_plan', agent: 'finance', expert: 'tax_consultant', label: 'VIE/红筹税务规划',
          goal: '境外SPV选地/境外资金回流/预扣税优化',
          successCriteria: ['税务架构图清晰', '综合税负对比有据'],
          profitImpact: { dimension: 'cost_saving', amount: '最优架构节省税务成本 5-15%' } },
        { id: 'valuation_support', agent: 'invest', expert: 'investment_analyst', label: '估值谈判支持',
          goal: 'EBITDA倍数/DCF/可比交易三种方法锚定价格区间',
          successCriteria: ['谈判底价有依据', '让步空间规划合理'],
          profitImpact: { dimension: 'revenue', amount: '理性报价避免超额支付' } },
        { id: 'spa_draft', agent: 'legal', expert: 'civil_lawyer', label: '并购协议起草',
          goal: 'SPA/对赌/锁定期/陈述与保证/赔偿机制关键条款框架',
          successCriteria: ['对赌触发条件清晰', '赔偿Cap/Basket设置合理'],
          profitImpact: { dimension: 'loss_avoidance', amount: '条款保护，降低交割后赔偿风险' } },
        { id: 'financing', agent: 'finance', expert: 'finance_accountant', label: '融资方案设计',
          goal: '并购贷款/定增/可转债融资结构，利息覆盖比测算',
          successCriteria: ['融资组合成本最优', 'DSCR符合银行要求'],
          profitImpact: { dimension: 'revenue', amount: '最优融资结构降低整体资金成本' } },
        { id: 'regulatory_path', agent: 'legal', expert: 'civil_lawyer', label: '监管合规预判',
          goal: '证监会/反垄断/外资安全审查路径梳理',
          successCriteria: ['审批路径清晰', '预计审批周期合理'],
          profitImpact: { dimension: 'cost_saving', amount: '提前规划减少审批延误' } },
      ],
      triggerPhrases: ['并购方案', '交易架构', '收购协议', 'SPA', '并购融资', '对赌设计'],
    },
    {
      id: 'ma_regulatory_closing',
      name: '监管申报与交割',
      icon: '📋',
      description: '证监会申报 + 反垄断申报 + 股东大会文件 + 信披公告 + CP Checklist，含人工确认',
      mode: 'sequential',
      deliverable: '申报文件包 + 信披公告草稿 + 交割CP Checklist',
      successCriteria: ['申报文件清单完整', 'CP Checklist全部满足', '交割安排明确'],
      steps: [
        { id: 'csrc', agent: 'legal', expert: 'civil_lawyer', label: '证监会申报文件',
          goal: '重大资产重组报告书/财务报告/法律意见书框架',
          successCriteria: ['文件框架符合证监会格式要求', '关键章节内容可用'],
          profitImpact: { dimension: 'cost_saving', amount: '申报文件起草 4 周→1 周' } },
        { id: 'antitrust', agent: 'legal', expert: 'civil_lawyer', label: '反垄断申报',
          goal: 'SAMR申报阈值判断+申请书框架+市场集中度分析',
          successCriteria: ['申报义务判断有法规依据', 'HHI指数计算完整'],
          profitImpact: { dimension: 'loss_avoidance', amount: '提前判断规避强制申报违规' } },
        { id: 'shareholders', agent: 'finance', expert: 'finance_accountant', label: '股东大会文件',
          goal: '董事会/股东大会决议+独立董事意见+独立财务顾问报告',
          successCriteria: ['决议格式符合章程', '独立意见内容充分'],
          profitImpact: { dimension: 'cost_saving', amount: '文件准备从 2 周→3 天' } },
        { id: 'disclosure', agent: 'legal', expert: 'civil_lawyer', label: '信披公告准备',
          goal: '重大资产重组预案/报告书摘要/交割完成公告草稿',
          successCriteria: ['公告格式符合交易所规则', '审慎性语言合规'],
          profitImpact: { dimension: 'loss_avoidance', amount: '及时合规信披，避免监管问询' } },
        { id: 'cp_check', agent: 'finance', expert: 'finance_accountant', label: '交割条件核查',
          goal: '监管批准/公司治理/陈述保证/融资落实/第三方同意全项确认',
          successCriteria: ['CP Checklist完成率100%', '阻断交割风险全部处理'],
          profitImpact: { dimension: 'loss_avoidance', amount: '确保交割顺利，避免延期损失' } },
      ],
      triggerPhrases: ['监管申报', '证监会审批', '反垄断', '重大资产重组', '交割', 'CP Checklist'],
    },
    {
      id: 'disclosure_periodic_report',
      name: '定期报告信息披露',
      icon: '📄',
      description: '年报/季报自动生成，2天→4小时，MD&A草稿+合规审查',
      mode: 'sequential',
      deliverable: '完整定期报告草稿（含图表）+ 信披合规检查清单',
      successCriteria: ['财务数据完整准确', 'MD&A逻辑清晰', '信披格式合规'],
      steps: [
        { id: 'data_integrate', agent: 'finance', expert: 'finance_accountant', label: '财务数据整合',
          goal: '年报/季报核心财务数据汇总与同比分析',
          successCriteria: ['主要财务指标同比环比完整', '数据来源可追溯'],
          profitImpact: { dimension: 'cost_saving', amount: '数据整合从 1 天→1 小时' } },
        { id: 'mda_draft', agent: 'finance', expert: 'finance_accountant', label: 'MD&A 草稿生成',
          goal: '经营成果分析/现金流分析/风险因素更新',
          successCriteria: ['分析有深度', '风险因素描述准确', 'MD&A逻辑连贯'],
          profitImpact: { dimension: 'cost_saving', amount: 'MD&A 写作从 1 天→2 小时' } },
        { id: 'compliance_check', agent: 'legal', expert: 'civil_lawyer', label: '信披合规检查',
          goal: '对照交易所格式指引逐项核查，标注遗漏披露项',
          successCriteria: ['所有必披露项覆盖', '格式符合交易所要求'],
          profitImpact: { dimension: 'loss_avoidance', amount: '合规问题提前发现，避免交易所问询函' } },
        { id: 'final_report', agent: 'finance', expert: 'finance_accountant', label: '最终报告输出',
          goal: '完整定期报告草稿（含数据图表），提交董秘确认',
          successCriteria: ['报告格式完整', '数据图表正确', '可直接提交审核'],
          profitImpact: { dimension: 'cost_saving', amount: '报告生成 2 天→4 小时' } },
      ],
      triggerPhrases: ['定期报告', '年报', '季报', '半年报', '信息披露', '董秘报告'],
    },
    {
      id: 'material_event_announcement',
      name: '重大事项临时公告',
      icon: '📢',
      description: '重大事项判断+公告起草+财务影响量化+窗口期核查，1天→2小时',
      mode: 'sequential',
      deliverable: '临时公告草稿 + 内幕信息合规确认',
      successCriteria: ['披露义务判断准确', '公告格式符合交易所要求', '窗口期合规'],
      steps: [
        { id: 'trigger_check', agent: 'legal', expert: 'civil_lawyer', label: '重大事项判断',
          goal: '评估是否触发临时公告披露义务',
          successCriteria: ['披露触发标准引用具体法规', '判断明确有依据'],
          profitImpact: { dimension: 'loss_avoidance', amount: '及时披露避免违规处罚和投资者诉讼' } },
        { id: 'draft', agent: 'legal', expert: 'civil_lawyer', label: '公告草稿起草',
          goal: '按交易所格式生成临时公告初稿',
          successCriteria: ['格式符合规范', '审慎性语言运用恰当'],
          profitImpact: { dimension: 'cost_saving', amount: '公告起草从 4 小时→30 分钟' } },
        { id: 'financial_impact', agent: 'finance', expert: 'finance_accountant', label: '财务影响量化',
          goal: '估算事项对净利润/资产/现金流的影响',
          successCriteria: ['影响金额有合理依据', '正负影响均评估'],
          profitImpact: { dimension: 'revenue', amount: '精准量化影响，支持投资者决策' } },
        { id: 'window_check', agent: 'legal', expert: 'civil_lawyer', label: '合规审查',
          goal: '核查内幕交易窗口期冲突，确认披露时间合规',
          successCriteria: ['窗口期规则正确应用', '披露时限符合要求'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免窗口期内交易违规，防范内幕交易指控' } },
      ],
      triggerPhrases: ['临时公告', '重大事项公告', '信息披露公告', '业绩预告', '股东变动公告'],
    },
    {
      id: 'related_party_review',
      name: '关联交易合规审查',
      icon: '🔗',
      description: '穿透识别关联方+定价公允性+审批阈值判断+披露文件，3天→4小时',
      mode: 'parallel',
      deliverable: '关联方清单 + 定价公允性评估 + 审批触发判断 + 披露文件草稿',
      successCriteria: ['关联方穿透识别完整', '定价公允性有据', '审批要求判断准确'],
      steps: [
        { id: 'identify', agent: 'finance', expert: 'finance_accountant', label: '关联方识别',
          goal: '穿透股权结构识别所有关联方，汇总年度关联交易清单',
          successCriteria: ['隐性关联方全覆盖', '年度交易额汇总完整'],
          profitImpact: { dimension: 'loss_avoidance', amount: '关联方漏报是信披违规常见原因' } },
        { id: 'pricing', agent: 'finance', expert: 'finance_accountant', label: '定价公允性评估',
          goal: '与市场/第三方价格对比，计算超额收益或损失',
          successCriteria: ['对比依据充分', '差价是否在合理范围内有结论'],
          profitImpact: { dimension: 'loss_avoidance', amount: '定价不公允是监管处罚重点' } },
        { id: 'approval', agent: 'legal', expert: 'civil_lawyer', label: '合规触发判断',
          goal: '判断是否超过审批阈值（董事会/股东大会/独立董事）',
          successCriteria: ['阈值判断引用具体规则', '审批路径明确'],
          profitImpact: { dimension: 'loss_avoidance', amount: '超阈值未审批是重大违规' } },
        { id: 'disclosure_prep', agent: 'legal', expert: 'civil_lawyer', label: '披露文件准备',
          goal: '起草年报关联交易章节+临时公告（如需）',
          successCriteria: ['披露格式符合规范', '金额与清单一致'],
          profitImpact: { dimension: 'cost_saving', amount: '披露文件从 3 天→4 小时' } },
      ],
      triggerPhrases: ['关联交易', '关联方审查', '关联交易合规', '关联方披露'],
    },
    {
      id: 'refinancing_design',
      name: '再融资方案设计',
      icon: '💹',
      description: '定增/可转债/配股三方案对比，EPS摊薄分析，申报清单，3周→3天',
      mode: 'sequential',
      deliverable: '再融资方案对比报告（工具推荐 + EPS摊薄 + 监管资格 + 申报清单）',
      successCriteria: ['三种方案量化对比', '摊薄分析准确', '监管资格核查完整'],
      steps: [
        { id: 'needs', agent: 'finance', expert: 'ipo_advisor', label: '再融资需求诊断',
          goal: '资金用途/规模/时间窗口/摊薄容忍度，推荐最优工具',
          successCriteria: ['需求分析完整', '工具推荐有理有据'],
          profitImpact: { dimension: 'revenue', amount: '再融资方案顾问服务单价 20–100 万' } },
        { id: 'private_placement', agent: 'finance', expert: 'finance_accountant', label: '定增方案设计',
          goal: '发行价/对象/锁定期/募资用途方案（符合再融资新规）',
          successCriteria: ['新规合规性确认', '定价机制说明清晰'],
          profitImpact: { dimension: 'cost_saving', amount: '3 周→1 天' } },
        { id: 'cb_compare', agent: 'finance', expert: 'finance_accountant', label: '可转债/配股对比',
          goal: '三方案 EPS 摊薄对比（转股价/溢价率/回售条款）',
          successCriteria: ['三方案可比口径统一', 'EPS 摊薄测算准确'],
          profitImpact: { dimension: 'revenue', amount: '最优方案选择最大化股东价值' } },
        { id: 'model', agent: 'finance', expert: 'finance_accountant', label: '财务影响模型',
          goal: '融资前后资本结构/偿债能力/ROE 影响测算',
          successCriteria: ['财务影响量化', '多情景敏感性分析'],
          profitImpact: { dimension: 'revenue', amount: '财务模型直接支持股东大会审议' } },
        { id: 'eligibility', agent: 'legal', expert: 'civil_lawyer', label: '监管合规核查',
          goal: '再融资资格核查（利润要求/未分配利润/前次募资使用情况）',
          successCriteria: ['再融资资格明确', '不符合项列出整改方案'],
          profitImpact: { dimension: 'loss_avoidance', amount: '提前发现资格问题，避免申报失败' } },
        { id: 'filing_list', agent: 'legal', expert: 'civil_lawyer', label: '申报文件清单',
          goal: '证监会注册文件/股东大会决议/募集说明书框架',
          successCriteria: ['文件清单完整', '各文件要求说明清楚'],
          profitImpact: { dimension: 'cost_saving', amount: '申报文件准备从 1 周→2 天' } },
      ],
      triggerPhrases: ['再融资', '定增', '可转债', '配股', '增发', '非公开发行'],
    },
  ],
  scenarios: [
    { id: 'ipo_match', label: 'IPO 板块适配', icon: '📊', prompt: '我们公司净利润连续3年超3000万，推荐哪个A股上市板块？', expectedOutcome: '四大板块适配分析 + 最优推荐 + 差距整改清单', expert: 'finance.ipo_advisor', profitImpact: { dimension: 'revenue', amount: 'IPO 辅导服务单价 50–200 万' } },
    { id: 'ipo_compliance', label: 'IPO 合规自查', icon: '🔍', prompt: '我司准备冲刺创业板，帮我做一个全面的合规诊断', expectedOutcome: '5维度合规诊断报告，红/黄/绿整改优先级清单', workflowId: 'ipo_compliance_diagnosis', profitImpact: { dimension: 'loss_avoidance', amount: '提前发现合规问题，节省 6–12 个月整改期' } },
    { id: 'bp_angel', label: '天使轮 BP', icon: '🚀', prompt: '帮我为融资客户起草一份天使轮商业计划书', expectedOutcome: '7章 BP 初稿 + 占位符清单 + 股权合规标注', workflowId: 'capital_market_readiness', profitImpact: { dimension: 'revenue', amount: 'BP 写作 2 周工作量压缩到 3 小时' } },
    { id: 'bp_series_a', label: 'A 轮完整 BP', icon: '🚀', prompt: '客户准备 A 轮融资，生成 14 章完整商业计划书', expectedOutcome: '14章完整 BP + Word/PDF 导出 + 股权合规标注', workflowId: 'capital_market_readiness', profitImpact: { dimension: 'revenue', amount: 'A 轮 BP 服务费 5–20 万' } },
    { id: 'ma_target', label: '并购标的初筛', icon: '🔎', prompt: '帮我在医疗器械行业找5–10个可并购的A股上市公司标的', expectedOutcome: '评分矩阵+短名单报告（5–10个）+初步接触策略', workflowId: 'ma_target_screening', profitImpact: { dimension: 'cost_saving', amount: '标的筛选 2 周→4 小时' } },
    { id: 'ma_dd', label: '并购尽调', icon: '📋', prompt: '帮我对目标公司做财务与法律双轨尽调', expectedOutcome: '财务+税务+法律三份尽调报告 + Red Flag 清单', workflowId: 'ma_due_diligence', profitImpact: { dimension: 'cost_saving', amount: '6 周→1 周，整体加速 6 倍' } },
    { id: 'valuation_calc', label: '并购估值', icon: '💰', prompt: '用 DCF 和 EV/EBITDA 方法帮我估算这家公司的价值区间', expectedOutcome: '三种方法估值区间 + 敏感性分析 + 估值结论', expert: 'invest.investment_analyst', profitImpact: { dimension: 'revenue', amount: '客观估值支持谈判' } },
    { id: 'disclosure_report', label: '季报信披生成', icon: '📄', prompt: '帮我生成本季度的信息披露报告草稿', expectedOutcome: '完整季报草稿（MD&A+数据+图表）+合规检查清单', workflowId: 'disclosure_periodic_report', profitImpact: { dimension: 'cost_saving', amount: '董秘季报从 2 天→4 小时' } },
    { id: 'announcement_draft', label: '重大公告起草', icon: '📢', prompt: '公司签了一份重大合同，帮我起草临时公告', expectedOutcome: '公告草稿 + 披露义务判断 + 窗口期合规确认', workflowId: 'material_event_announcement', profitImpact: { dimension: 'loss_avoidance', amount: '及时合规披露，避免处罚' } },
    { id: 'related_party', label: '关联交易审查', icon: '🔗', prompt: '帮我审查今年和关联方的所有交易是否合规', expectedOutcome: '关联方清单 + 定价公允评估 + 审批要求 + 披露草稿', workflowId: 'related_party_review', profitImpact: { dimension: 'loss_avoidance', amount: '关联交易合规，避免监管问询' } },
    { id: 'refinancing_plan', label: '再融资方案', icon: '💹', prompt: '公司需要融资8亿，比较定增和可转债哪个更划算', expectedOutcome: '定增 vs 可转债方案对比 + EPS摊薄分析 + 申报清单', workflowId: 'refinancing_design', profitImpact: { dimension: 'revenue', amount: '最优融资工具节省利息成本 1000 万/年' } },
  ],
}

export default capitalMarketsSolution
