/**
 * 自动拆分自 solution-registry-data.ts。
 * 请勿手工编辑“结构”——如需改方案内容，请直接改本文件字段即可。
 */
import type { SolutionConfig } from '../solution-router'
import { agent } from '../solution-router-agent'

export const constructionCostSolution: SolutionConfig = {
  id: 'construction-cost',
  name: '工程造价咨询方案',
  icon: '🏗️',
  color: '#ea580c',
  tagline: '一个造价师年产值翻 3 倍，审核更准利润更高',
  description: 'AI 把翻定额、算工程量、核取费加速 10 倍。一个造价师过去年做 20 个项目，现在能做 60 个。',
  entrepreneurPurpose: '同样团队承接 3 倍项目，每个项目审核零差错',
  profitMetrics: ['定额查询 2h→10s，每个项目省 40+ 小时', '年产值 50 万→150 万/人', '核减遗漏降低 90%'],
  valueEquivalent: { humanHours: 80, mbeMinutes: 10, acceleration: '480x' },
  agents: [
    agent('cost', 8007, '造价工程专家', '定额查询、工程量计算、清单编制'),
    agent('cost', 8007, '取费审核专家', '取费计算、税金计算、造价估算'),
    agent('legal', 8003, '合同合规专家', '施工合同审查、变更签证、索赔分析'),
  ],
  localScripts: ['calc_cost_estimate', 'calc_cost_fee', 'calc_cost_tax'],
  knowledgeCache: ['cost_standards'],
  theme: { primary: '21 90% 48%', accent: '21 90% 48%', sidebarBg: '20 15% 6%' },
  enabledTabs: ['chat', 'tools', 'workflows', 'dashboard', 'knowledge-graph'],
  tools: [
    { id: 'cost-fee', type: 'calculator', name: '取费计算器', icon: '🧮',
      agent: 'cost', apiPath: '/api/cost/calc/fee', localScript: 'calc_cost_fee',
      fields: [
        { key: 'project_type', label: '工程类型', type: 'select', required: true,
          options: [
            { value: 'building', label: '建筑工程' }, { value: 'municipal', label: '市政工程' },
            { value: 'decoration', label: '装修工程' }, { value: 'installation', label: '安装工程' },
          ] },
        { key: 'base_cost', label: '直接费（元）', type: 'currency', required: true },
      ],
    },
    { id: 'cost-tax', type: 'calculator', name: '工程税金计算', icon: '🏗️',
      agent: 'cost', apiPath: '/api/cost/calc/tax', localScript: 'calc_cost_tax',
      fields: [
        { key: 'amount', label: '税前造价（元）', type: 'currency', required: true },
        { key: 'tax_rate', label: '税率', type: 'select', required: true,
          options: [{ value: '0.09', label: '9%（一般）' }, { value: '0.03', label: '3%（简易）' }] },
      ],
    },
    { id: 'cost-estimate', type: 'calculator', name: '造价估算', icon: '📐',
      agent: 'cost', apiPath: '/api/cost/calc/estimate', localScript: 'calc_cost_estimate',
      fields: [
        { key: 'area', label: '建筑面积（㎡）', type: 'number', required: true },
        { key: 'structure', label: '结构形式', type: 'select', required: true,
          options: [
            { value: 'frame', label: '框架结构' }, { value: 'shear_wall', label: '剪力墙结构' },
            { value: 'steel', label: '钢结构' },
          ] },
      ],
    },
    {
      id: 'quota-lookup', type: 'calculator', name: '定额查询', icon: '📖',
      agent: 'cost', apiPath: '/api/cost/calc/quota-lookup',
      description: '按定额编号或关键词查询定额子目（含人工/材料/机械组价明细）',
      fields: [
        { key: 'quota_code', label: '定额编号（如 1-15）', type: 'text' },
        { key: 'keyword', label: '关键词（如 "C30 混凝土"）', type: 'text' },
        { key: 'region', label: '适用地区', type: 'select', default: 'national',
          options: [
            { value: 'national', label: '全国统一定额' }, { value: 'beijing', label: '北京市' },
            { value: 'shanghai', label: '上海市' }, { value: 'guangdong', label: '广东省' },
            { value: 'zhejiang', label: '浙江省' }, { value: 'jiangsu', label: '江苏省' },
          ] },
      ],
    },
  ],
  slashCommands: [
    { cmd: '/取费', label: '取费计算', icon: '🧮', toolId: 'cost-fee' },
    { cmd: '/税金', label: '工程税金', icon: '🏗️', toolId: 'cost-tax' },
    { cmd: '/估算', label: '造价估算', icon: '📐', toolId: 'cost-estimate' },
    { cmd: '/定额', label: '定额查询', icon: '📖', toolId: 'quota-lookup' },
    { cmd: '/概预算', label: '概预算编制', workflowId: 'budget_compilation' },
    { cmd: '/结算', label: '结算审核', workflowId: 'settlement_audit' },
    { cmd: '/招标', label: '招投标分析', workflowId: 'bidding_analysis' },
    { cmd: '/变更', label: '变更估价', workflowId: 'change_valuation' },
    { cmd: '/鉴定', label: '司法鉴定', workflowId: 'forensic_appraisal' },
    { cmd: '/全过程', label: '全过程咨询', workflowId: 'whole_process_consulting' },
    { cmd: '/标书', label: '招标文件', workflowId: 'tender_document_drafting' },
    { cmd: '/BIM', label: 'BIM 算量', workflowId: 'bim_cost_integration' },
    { cmd: '/投资', label: '投资估算', workflowId: 'pre_construction_consulting' },
    { cmd: '/EPC', label: 'EPC/PPP', workflowId: 'epc_ppp_advisory' },
    { cmd: '/代理', label: '招标代理', workflowId: 'bidding_agency_full' },
    { cmd: '/对标', label: '造价对标', workflowId: 'cost_database_service' },
  ],
  workflows: [
    // ── 核心 4 大工作流 ──
    {
      id: 'budget_compilation', name: '概预算编制', icon: '📐',
      description: '工程分类 → 工程量计算 → 定额套价 → 取费计算 → 概预算报告（3天→30分钟）',
      mode: 'sequential',
      estimatedTime: { human: '3 天', ai: '30 分钟' },
      aiRate: 0.80,
      steps: [
        { id: 'project_info', agent: 'cost', expert: 'cost_engineer', label: '工程分类与基础信息确认' },
        { id: 'quantity_calc', agent: 'cost', expert: 'cost_engineer', label: '工程量计算' },
        { id: 'quota_pricing', agent: 'cost', expert: 'cost_engineer', label: '定额套价' },
        { id: 'fee_calculation', agent: 'cost', expert: 'cost_engineer', label: '取费计算' },
        { id: 'report_output', agent: 'cost', expert: 'cost_engineer', label: '概预算报告输出' },
      ],
      triggerPhrases: ['概预算', '编制预算', '工程预算', '估算', '投资估算'],
    },
    {
      id: 'settlement_audit', name: '结算审核', icon: '📋',
      description: '工程量复核 → 单价审核 → 取费审核 → 合同合规 → 审核报告（核减率精度+40%）',
      mode: 'sequential',
      estimatedTime: { human: '5 天', ai: '2 小时' },
      aiRate: 0.75,
      steps: [
        { id: 'audit_overview', agent: 'cost', expert: 'cost_engineer', label: '结算资料接收与概况确认' },
        { id: 'quantity_audit', agent: 'cost', expert: 'cost_engineer', label: '工程量逐项复核' },
        { id: 'price_audit', agent: 'cost', expert: 'cost_engineer', label: '单价与取费审核' },
        { id: 'contract_compliance', agent: 'legal', expert: 'contract_reviewer', label: '合同合规核查' },
        { id: 'audit_summary', agent: 'cost', expert: 'cost_engineer', label: '审核报告输出' },
      ],
      triggerPhrases: ['结算审核', '审核结算', '工程结算', '核减'],
    },
    {
      id: 'bidding_analysis', name: '招投标分析', icon: '📊',
      description: '标书解析 → 清单报价 → 竞标分析 → 合规审查 → 投标策略（2天→1小时）',
      mode: 'parallel',
      estimatedTime: { human: '2 天', ai: '1 小时' },
      aiRate: 0.70,
      steps: [
        { id: 'tender_analysis', agent: 'cost', expert: 'cost_engineer', label: '招标文件关键条款解析' },
        { id: 'boq_pricing', agent: 'cost', expert: 'cost_engineer', label: '清单编制与投标报价' },
        { id: 'competition_analysis', agent: 'cost', expert: 'cost_engineer', label: '竞标价格分析' },
        { id: 'compliance_check', agent: 'legal', expert: 'contract_reviewer', label: '投标合规性审查' },
        { id: 'strategy_recommendation', agent: 'cost', expert: 'cost_engineer', label: '投标策略建议' },
      ],
      triggerPhrases: ['招投标', '投标报价', '标书分析', '清单编制'],
    },
    {
      id: 'change_valuation', name: '变更估价', icon: '📝',
      description: '签证解析 → 变更工程量 → 估价计算 → 合同比对 → 估价单（1天→20分钟）',
      mode: 'sequential',
      estimatedTime: { human: '1 天', ai: '20 分钟' },
      aiRate: 0.85,
      steps: [
        { id: 'sign_parse', agent: 'cost', expert: 'cost_engineer', label: '变更签证解析' },
        { id: 'change_quantity', agent: 'cost', expert: 'cost_engineer', label: '变更工程量计算' },
        { id: 'change_valuation', agent: 'cost', expert: 'cost_engineer', label: '变更估价计算' },
        { id: 'contract_check', agent: 'legal', expert: 'contract_reviewer', label: '合同条款比对' },
      ],
      triggerPhrases: ['变更签证', '签证估价', '材料调差', '工程变更'],
    },
    // ── 高阶专项工作流 ──
    {
      id: 'forensic_appraisal', name: '司法造价鉴定', icon: '⚖️',
      description: '委托审查 → 证据链 → 争议分类 → 独立复核 → 多方对比 → 鉴定报告（15天→2天）',
      mode: 'sequential',
      estimatedTime: { human: '15 天', ai: '2 天' },
      aiRate: 0.65,
      steps: [
        { id: 'commission_review', agent: 'cost', expert: 'cost_engineer', label: '委托函审查与鉴定范围确定' },
        { id: 'evidence_review', agent: 'legal', expert: 'civil_lawyer', label: '证据梳理与证据链分析' },
        { id: 'dispute_classification', agent: 'cost', expert: 'cost_engineer', label: '争议点分类与金额汇总' },
        { id: 'independent_calc', agent: 'cost', expert: 'cost_engineer', label: '独立造价复核计算' },
        { id: 'comparison_analysis', agent: 'cost', expert: 'cost_engineer', label: '多方观点对比分析' },
        { id: 'legal_opinion', agent: 'legal', expert: 'civil_lawyer', label: '法律意见嵌入' },
        { id: 'report_draft', mode: 'hitl', label: '鉴定报告人工签字确认' },
      ],
      triggerPhrases: ['司法鉴定', '造价鉴定', '法院委托', '工程鉴定', '诉讼举证'],
    },
    {
      id: 'whole_process_consulting', name: '全过程造价咨询', icon: '🔄',
      description: '决策→设计→招投标→施工→竣工→后评估，6阶段节点自动托管',
      mode: 'sequential',
      estimatedTime: { human: '项目全周期', ai: '节点自动托管' },
      aiRate: 0.70,
      steps: [
        { id: 'stage1_decision', agent: 'cost', expert: 'cost_engineer', label: '阶段1·决策阶段造价咨询' },
        { id: 'stage2_design', agent: 'cost', expert: 'expert_design', label: '阶段2·设计阶段限额管控' },
        { id: 'stage3_bidding', agent: 'cost', expert: 'cost_engineer', label: '阶段3·招投标阶段造价管控' },
        { id: 'stage4_construction', agent: 'cost', expert: 'cost_engineer', label: '阶段4·施工阶段进度款与变更' },
        { id: 'stage5_completion', agent: 'cost', expert: 'cost_engineer', label: '阶段5·竣工结算审核' },
        { id: 'stage6_post_eval', agent: 'cost', expert: 'expert_design', label: '阶段6·竣工后评估与归档' },
      ],
      triggerPhrases: ['全过程造价', '全过程咨询', '造价托管', '阶段节点'],
    },
    {
      id: 'tender_document_drafting', name: '招标文件编制', icon: '📄',
      description: '项目概况 → 资格条件 → 工程量清单 → 控制价 → 评标办法 → 合同条款 → 合规审查',
      mode: 'sequential',
      estimatedTime: { human: '7 天', ai: '1 天' },
      aiRate: 0.80,
      steps: [
        { id: 'project_scope', agent: 'cost', expert: 'cost_engineer', label: '项目概况与招标范围' },
        { id: 'qualification_requirements', agent: 'legal', expert: 'contract_reviewer', label: '资格条件设置' },
        { id: 'boq_compilation', agent: 'cost', expert: 'cost_engineer', label: '工程量清单编制' },
        { id: 'control_price', agent: 'cost', expert: 'cost_engineer', label: '招标控制价编制' },
        { id: 'evaluation_method', agent: 'cost', expert: 'cost_engineer', label: '评标办法设计' },
        { id: 'contract_terms', agent: 'legal', expert: 'contract_reviewer', label: '合同关键条款起草' },
        { id: 'compliance_review', agent: 'legal', expert: 'contract_reviewer', label: '招标文件合规审查' },
      ],
      triggerPhrases: ['招标文件', '招标公告', '控制价', '工程量清单编制', '评标办法'],
    },
    {
      id: 'bim_cost_integration', name: 'BIM 造价集成', icon: '🏗️',
      description: 'IFC 模型解析 → 构件映射 → 5D 算量 → GB50500 清单 → EVM 挣值分析（10天→1天）',
      mode: 'sequential',
      estimatedTime: { human: '10 天', ai: '1 天' },
      aiRate: 0.85,
      steps: [
        { id: 'model_check', agent: 'cost', expert: 'cost_engineer', label: 'IFC 模型接收与质量检查' },
        { id: 'element_mapping', agent: 'cost', expert: 'cost_engineer', label: '构件族库→定额子目映射' },
        { id: 'quantity_extraction', agent: 'cost', expert: 'cost_engineer', label: '5D 工程量自动提取' },
        { id: 'boq_linkage', agent: 'cost', expert: 'cost_engineer', label: 'BIM→GB50500 清单联动' },
        { id: 'evm_analysis', agent: 'cost', expert: 'cost_engineer', label: '4D 进度×5D 挣值分析' },
        { id: 'clash_impact', agent: 'cost', expert: 'expert_design', label: '碰撞与变更造价影响' },
      ],
      triggerPhrases: ['BIM', 'IFC', 'Revit', '模型算量', 'BIM算量', '5D造价'],
    },
    {
      id: 'pre_construction_consulting', name: '投资决策/设计阶段咨询', icon: '💡',
      description: '投资估算 → 经济评价 → 设计概算 → 限额设计 → 方案比选（精度±10%-20%）',
      mode: 'sequential',
      estimatedTime: { human: '10 天', ai: '1.5 天' },
      aiRate: 0.75,
      steps: [
        { id: 'investment_estimate', agent: 'cost', expert: 'cost_engineer', label: '投资估算编制' },
        { id: 'economic_evaluation', agent: 'cost', expert: 'expert_design', label: '经济评价（NPV/IRR）' },
        { id: 'design_budget', agent: 'cost', expert: 'cost_engineer', label: '设计概算编制' },
        { id: 'limit_design', agent: 'cost', expert: 'expert_design', label: '限额设计目标分解' },
        { id: 'scheme_comparison', agent: 'cost', expert: 'expert_design', label: '多方案造价比选' },
      ],
      triggerPhrases: ['投资估算', '可研', '设计概算', '限额设计', '经济评价', 'NPV', 'IRR'],
    },
    {
      id: 'epc_ppp_advisory', name: 'EPC/PPP 专项咨询', icon: '🏛️',
      description: '模式选型 → EPC总价/PPP财务测算 → 风险分担矩阵 → VfM评价 → 财政承受能力论证',
      mode: 'sequential',
      estimatedTime: { human: '20 天', ai: '3 天' },
      aiRate: 0.60,
      steps: [
        { id: 'mode_selection', agent: 'cost', expert: 'cost_engineer', label: '项目模式选型' },
        { id: 'financial_model', agent: 'cost', expert: 'expert_design', label: 'EPC总价/PPP全生命周期测算' },
        { id: 'risk_matrix', agent: 'legal', expert: 'contract_reviewer', label: '风险分担矩阵设计' },
        { id: 'contract_key_terms', agent: 'legal', expert: 'contract_reviewer', label: '合同关键条款起草' },
        { id: 'vfm_evaluation', agent: 'cost', expert: 'expert_design', label: '物有所值 VfM 评价' },
        { id: 'fiscal_capacity', agent: 'cost', expert: 'expert_design', label: '财政承受能力论证' },
      ],
      triggerPhrases: ['EPC', 'PPP', '总承包', '政府和社会资本', 'VfM', '物有所值', '财政承受能力'],
    },
    {
      id: 'bidding_agency_full', name: '招标代理全流程', icon: '📜',
      description: '委托受理 → 方案策划 → 文件编制 → 公告发布 → 资格审查 → 开标（HITL）→ 评标 → 定标 → 合同 → 归档',
      mode: 'sequential',
      estimatedTime: { human: '30 天', ai: '5 天' },
      aiRate: 0.70,
      steps: [
        { id: 'commission_acceptance', agent: 'cost', expert: 'cost_engineer', label: '委托受理与合规性预审' },
        { id: 'bidding_scheme', agent: 'cost', expert: 'cost_engineer', label: '招标方案策划' },
        { id: 'document_preparation', agent: 'cost', expert: 'cost_engineer', label: '招标文件及控制价编制' },
        { id: 'announcement_publish', agent: 'cost', expert: 'cost_engineer', label: '公告发布与报名管理' },
        { id: 'qualification_review', agent: 'legal', expert: 'contract_reviewer', label: '投标人资格审查' },
        { id: 'clarification', agent: 'legal', expert: 'contract_reviewer', label: '答疑与澄清文件发布' },
        { id: 'bid_opening', mode: 'hitl', label: '开标组织（现场/电子开标）' },
        { id: 'evaluation_support', agent: 'cost', expert: 'cost_engineer', label: '评标辅助（AI 初审）' },
        { id: 'bid_award', agent: 'legal', expert: 'contract_reviewer', label: '定标公示与异议处理' },
        { id: 'contract_negotiation', agent: 'legal', expert: 'contract_reviewer', label: '合同条款谈判支持' },
        { id: 'archive_management', agent: 'cost', expert: 'cost_engineer', label: '全流程资料归档' },
      ],
      triggerPhrases: ['招标代理', '代理机构', '委托代理', '开标评标', '定标公示'],
    },
    {
      id: 'cost_database_service', name: '造价大数据与指标库', icon: '📊',
      description: '历史项目对标 → 材料价格查询 → 定额语义检索 → 清单模板复用 → 成本预警（2天→30秒）',
      mode: 'parallel',
      estimatedTime: { human: '2 天', ai: '30 秒' },
      aiRate: 0.95,
      steps: [
        { id: 'benchmark_query', agent: 'cost', expert: 'cost_engineer', label: '历史项目造价对标' },
        { id: 'material_price_query', agent: 'cost', expert: 'cost_engineer', label: '材料价格库查询' },
        { id: 'quota_semantic_search', agent: 'cost', expert: 'cost_engineer', label: '定额子目语义检索' },
        { id: 'template_reuse', agent: 'cost', expert: 'cost_engineer', label: '清单模板智能推荐' },
        { id: 'indicator_analysis', agent: 'cost', expert: 'cost_engineer', label: '造价指标综合分析' },
        { id: 'cost_alert', agent: 'cost', expert: 'cost_engineer', label: '成本预警识别' },
      ],
      triggerPhrases: ['造价对标', '历史项目', '单方造价', '材料信息价', '造价指标', '定额检索'],
    },
  ],
  safetyRules: [
    // ── 基础 5 条 ──
    { id: 'price-abnormal-alert',       label: '单价异常报警',       level: 'warning', trigger: '综合单价偏离信息价或定额基价 ≥ 20%',              action: '橙色预警，标注异常项并要求核实依据' },
    { id: 'tax-method-check',           label: '计税方式校验',       level: 'hard',    trigger: '一般计税/简易计税选择与合同不一致',               action: '阻止计算，提示核对合同约定' },
    { id: 'settlement-over-contract',   label: '结算超合同价预警',   level: 'danger',  trigger: '结算金额超过合同价 15% 以上',                     action: '红色预警，列出主要增量项和变更依据' },
    { id: 'quota-region-mismatch',      label: '定额地区不匹配',     level: 'hard',    trigger: '使用的定额标准与项目所在地区不一致',               action: '阻止套价，提示选择正确地区定额' },
    { id: 'bid-deadline-guard',         label: '投标截止倒计时',     level: 'danger',  trigger: '距投标截止日 ≤ 3 天',                             action: '红色弹窗+置顶任务，提醒完成标书' },
    // ── 对标永达信新增 12 条 ──
    { id: 'forensic-independence',      label: '司法鉴定独立性',     level: 'hard',    trigger: '鉴定人员与当事方存在利害关系',                     action: '阻止出具报告，要求回避并更换鉴定人员' },
    { id: 'forensic-evidence',          label: '鉴定证据完整性',     level: 'danger',  trigger: '缺失合同/图纸/签证核心证据',                       action: '红色预警，列出缺失清单并要求法院补充' },
    { id: 'tender-exclusive-clause',    label: '招标排他性条款',     level: 'hard',    trigger: '资格条件含指向性/排他性表述（特定品牌/独家资质）',  action: '阻止发布，提示违反《招标投标法》第32条' },
    { id: 'ppp-fiscal-redline',         label: 'PPP 财政支付红线',   level: 'danger',  trigger: '政府年度支付责任 > 一般公共预算 10%',               action: '红色预警，触发财政部92号文红线' },
    { id: 'bim-model-version',          label: 'BIM 模型版本一致',   level: 'hard',    trigger: 'IFC 文件版本与设计变更版本不一致',                  action: '阻止算量，提示刷新最新模型' },
    { id: 'limit-design-breach',        label: '限额设计突破',       level: 'warning', trigger: '设计概算 > 投资估算 ±10%',                         action: '橙色预警，列出超限专业并要求调整方案' },
    { id: 'epc-provisional-sum-excess', label: 'EPC 暂列金超限',     level: 'warning', trigger: '暂列金占总价 > 10%',                               action: '橙色预警，提示风险过高，建议调整暂列金构成' },
    { id: 'bid-qualification-disc',     label: '资格条件歧视性',     level: 'hard',    trigger: '含限定地域/规模/所有制等歧视性条款',               action: '阻止发布，提示违反《招标投标法实施条例》第32条' },
    { id: 'bid-expert-conflict',        label: '评标专家回避',       level: 'danger',  trigger: '评标专家与投标人存在利害关系未申请回避',            action: '红色预警，强制更换专家并重新评标' },
    { id: 'bid-e-trail',                label: '电子招投标留痕',     level: 'hard',    trigger: '开标/评标/定标环节缺失电子签章或时间戳',            action: '阻止归档，要求补全电子证据链' },
    { id: 'cost-benchmark-deviation',   label: '造价对标偏离预警',   level: 'warning', trigger: '当前项目单方造价偏离历史均值 ≥ 25%',                action: '橙色预警，提示核查工程量/材料价/取费标准' },
    { id: 'material-price-volatility',  label: '材料价格剧烈波动',   level: 'warning', trigger: '主材近3期价格波动 ≥ 15%',                          action: '橙色预警，提示考虑合同调价条款或锁定价格' },
  ],
  quickActions: [
    { id: 'quick-estimate',    label: '快速造价估算', icon: '📐', workflowId: 'budget_compilation',         description: '输入面积和结构形式，秒出造价估算',                   cta: '开始估算' },
    { id: 'fee-calc',          label: '取费计算',     icon: '🧮', description: '输入直接费，自动按 GB50500 计算全部取费',             cta: '开始计算' },
    { id: 'settlement-review', label: '结算审核',     icon: '📋', workflowId: 'settlement_audit',           description: '启动结算审核全流程（工程量→单价→取费→报告）',        cta: '开始审核' },
    { id: 'material-adjust',   label: '材料调差',     icon: '📦', workflowId: 'change_valuation',           description: '价差法/指数法/FIDIC 公式计算材料调差',               cta: '计算调差' },
    { id: 'quota-search',      label: '定额查询',     icon: '📖', description: '按关键词或编号查询定额子目和单价',                   cta: '查询定额' },
    { id: 'forensic-appraisal',label: '司法鉴定',     icon: '⚖️', workflowId: 'forensic_appraisal',         description: '法院委托造价鉴定，证据梳理+独立复核+鉴定报告',       cta: '启动鉴定' },
    { id: 'whole-process',     label: '全过程托管',   icon: '🔄', workflowId: 'whole_process_consulting',   description: '决策→设计→招投标→施工→竣工→后评估全阶段托管',      cta: '启动托管' },
    { id: 'tender-doc',        label: '招标文件',     icon: '📄', workflowId: 'tender_document_drafting',   description: '一键生成招标文件+控制价+清单+评标办法',              cta: '生成标书' },
    { id: 'bim-takeoff',       label: 'BIM 算量',     icon: '🏗️', workflowId: 'bim_cost_integration',       description: '解析 IFC 模型，自动算量并联动 GB50500 清单',         cta: '启动 BIM' },
    { id: 'investment-estimate',label: '投资估算',    icon: '💡', workflowId: 'pre_construction_consulting',description: '决策阶段投资估算+经济评价+限额设计',                 cta: '启动估算' },
    { id: 'epc-ppp',           label: 'EPC/PPP',      icon: '🏛️', workflowId: 'epc_ppp_advisory',           description: 'EPC 总价测算/PPP 财务测算+VfM 评价+风险分担',       cta: '启动咨询' },
    { id: 'bidding-agency',    label: '招标代理',     icon: '📜', workflowId: 'bidding_agency_full',         description: '全流程招标代理（委托→公告→资审→开标→评标→合同）',  cta: '启动代理' },
    { id: 'cost-benchmark',    label: '造价对标',     icon: '📊', workflowId: 'cost_database_service',       description: '历史项目造价对标+单方造价指标+成本预警',             cta: '开始对标' },
    { id: 'material-price',    label: '材料价格库',   icon: '💰', description: '自然语言查询材料信息价/市场价+近12期价差趋势',       cta: '查询价格' },
  ],
  scenarios: [
    { id: 'quota_lookup', label: '定额查询', icon: '📖', prompt: '查询这项施工内容的定额子目和单价', expectedOutcome: '定额编号 + 子目名称 + 含量 + 基价', expert: 'cost.cost_engineer', profitImpact: { dimension: 'cost_saving', amount: '定额查询 2h→10s，每项目省 40+ 小时' } },
    { id: 'change_order', label: '变更签证', icon: '📝', prompt: '分析这份变更签证的造价影响', expectedOutcome: '变更金额（增/减）+ 计算依据 + 合同条款引用', expert: 'cost.cost_engineer', profitImpact: { dimension: 'revenue', amount: '审核更准确，单项多收审核费 1-3 万' } },
  ],
}

export default constructionCostSolution
