/**
 * 自动拆分自 solution-registry-data.ts。
 * 请勿手工编辑“结构”——如需改方案内容，请直接改本文件字段即可。
 */
import type { SolutionConfig } from '../solution-router'
import { agent } from '../solution-router-agent'

export const ecommerceBrandServiceSolution: SolutionConfig = {
  id: 'ecommerce-brand-service',
  name: '品牌电商全价值链方案',
  icon: '🛒',
  color: '#e11d48',
  tagline: '5 人 TP 团队做出 20 人的产出，毛利率提升 20 个百分点',
  description: 'TP/代运营公司利润 = GMV × 佣金率 - 人力成本。AI 让 5 人团队做出 20 人产出，毛利率从 15% 做到 35%。',
  entrepreneurPurpose: '同样团队规模服务 4 倍品牌客户，毛利率从 15% 提到 35%',
  profitMetrics: ['客服人力成本降 60%', '内容生产效率 10 倍提升', '佣金结算零差错'],
  valueEquivalent: { humanHours: 240, mbeMinutes: 55, acceleration: '260x' },
  agents: [
    agent('cs', 8004, '电商客服专家', '多品牌BPO、工单SLA、话术库、消费者运营'),
    agent('growth', 8009, '增长营销专家', '大促策划、投放优化、私域运营、内容排期'),
    agent('sales', 8008, '品牌BD专家', '渠道拓展、竞品分析、客户成功'),
    agent('finance', 8002, '电商财务专家', '佣金核算、服务费结算、税务处理'),
    agent('legal', 8003, '合规审查专家', '消保合规、代运营合同、广告法审查'),
  ],
  localScripts: ['calc_iit', 'calc_vat'],
  knowledgeCache: [],
  theme: { primary: '347 77% 50%', accent: '347 77% 50%', sidebarBg: '347 15% 7%' },
  enabledTabs: ['brands', 'chat', 'workflows', 'tools', 'erp-sync', 'dashboard', 'costs', 'efficiency', 'scheduler', 'knowledge-graph'],
  onboarding: {
    questions: [
      { key: 'brand_count', label: '目前服务品牌数量', options: ['1-3个', '4-10个', '10个以上'] },
      { key: 'platform', label: '主要运营平台', options: ['天猫/淘宝', '京东', '抖音', '小红书', '多平台'] },
      { key: 'pain_point', label: '最想解决的问题', options: ['客服效率', '佣金结算', '营销ROI', '合规风险'] },
    ],
  } as any,
  tools: [
    // ── 客服工具 ──
    { id: 'response-generator', type: 'doc-generator', name: '客服话术生成', icon: '💬',
      agent: 'cs', apiPath: '/api/cs/ai/response-generate', category: '客服工具',
      description: '根据客户问题和场景，AI 生成专业客服回复话术（一键复制到剪贴板）',
      fields: [
        { key: 'customer_message', label: '客户消息', type: 'textarea', required: true, placeholder: '粘贴客户原始消息' },
        { key: 'scenario', label: '场景', type: 'select', required: true,
          options: [
            { value: 'pre_sale', label: '售前咨询' },
            { value: 'after_sale', label: '售后处理' },
            { value: 'complaint', label: '投诉处理' },
            { value: 'refund', label: '退换货' },
          ] },
      ],
    },
    { id: 'sla-calc', type: 'calculator', name: 'SLA 达标计算', icon: '📊',
      agent: 'cs', apiPath: '/api/cs/calc/sla', category: '客服工具',
      description: '客服 SLA 达标率和响应时效计算',
      fields: [
        { key: 'sla_tier', label: 'SLA 等级', type: 'select', required: true,
          options: [
            { value: 'standard', label: '标准（首响60s/解决4h）' },
            { value: 'premium', label: '高级（首响30s/解决2h）' },
            { value: 'vip', label: 'VIP（首响15s/解决1h）' },
          ] },
        { key: 'total_tickets', label: '工单总量', type: 'number', required: true },
        { key: 'breached_tickets', label: '超时工单数', type: 'number', required: true },
      ],
    },
    // ── 合规工具 ──
    { id: 'product-compliance-check', type: 'document-ai', name: '商品合规检查', icon: '🔍',
      agent: 'cs', apiPath: '/api/cs/ai/product-compliance', category: '合规工具',
      description: '检查商品标题/描述/详情页是否违反平台规则和广告法',
      fields: [
        { key: 'product_title', label: '商品标题', type: 'text', required: true },
        { key: 'product_desc', label: '商品描述', type: 'textarea', required: true },
        { key: 'platform', label: '销售平台', type: 'select', required: true,
          options: [
            { value: 'taobao', label: '淘宝/天猫' },
            { value: 'jd', label: '京东' },
            { value: 'douyin', label: '抖音' },
            { value: 'pdd', label: '拼多多' },
          ] },
      ],
    },
    { id: 'extreme-words-check', type: 'document-ai', name: '极限词检查', icon: '🚫',
      agent: 'growth', apiPath: '/api/growth/ai/extreme-words', category: '合规工具',
      description: '扫描文案中的广告法极限词/违禁词，避免平台处罚（罚款 5-20 万）',
      fields: [
        { key: 'text', label: '待检查文案', type: 'textarea', required: true, placeholder: '粘贴商品标题、描述或广告文案' },
      ],
    },
    // ── 营销工具 ──
    { id: 'campaign-roi-calc', type: 'calculator', name: '活动 ROI 计算器', icon: '📈',
      agent: 'growth', apiPath: '/api/growth/calc/campaign-roi', category: '营销工具',
      description: '计算营销活动投入产出比（GMV、转化率、客单价、退货率）',
      fields: [
        { key: 'ad_spend', label: '广告投入（元）', type: 'currency', required: true },
        { key: 'gmv', label: '活动 GMV（元）', type: 'currency', required: true },
        { key: 'return_rate', label: '退货率（%）', type: 'number', placeholder: '默认 5%' },
      ],
    },
    // ── 财务工具 ──
    { id: 'commission-calc', type: 'calculator', name: '佣金结算计算器', icon: '💰',
      agent: 'finance', apiPath: '/api/finance/calc/commission', category: '财务工具',
      description: '按品牌 GMV × 佣金率自动计算月度服务费，含平台扣点和税费',
      fields: [
        { key: 'gmv', label: '月度 GMV（元）', type: 'currency', required: true },
        { key: 'commission_rate', label: '佣金比例（%）', type: 'number', required: true, placeholder: '如 8' },
        { key: 'fixed_fee', label: '固定服务费（元/月）', type: 'currency', default: 0 },
        { key: 'platform_rate', label: '平台扣点（%）', type: 'number', placeholder: '如 5' },
      ],
    },
    { id: 'iit', type: 'calculator', name: '个税计算器', icon: '🧾',
      agent: 'finance', apiPath: '/api/finance/calc/iit', localScript: 'calc_iit', category: '财务工具',
      fields: [
        { key: 'salary', label: '税前月薪（元）', type: 'currency', required: true },
      ],
    },
    // ── 报告工具 ──
    { id: 'monthly-report-gen', type: 'doc-generator', name: '月度运营报告', icon: '📋',
      agent: 'growth', apiPath: '/api/growth/ai/monthly-report', category: '报告工具',
      description: '一键生成品牌月度运营报告（GMV/转化/客服绩效/内容数据）',
      fields: [
        { key: 'brand_name', label: '品牌名称', type: 'text', required: true },
        { key: 'month', label: '月份', type: 'text', required: true, placeholder: '如 2026-03' },
      ],
    },
  ],
  slashCommands: [
    { cmd: '/话术', label: '生成客服话术', icon: '💬', toolId: 'response-generator' },
    { cmd: '/合规', label: '商品合规检查', icon: '🔍', toolId: 'product-compliance-check' },
    { cmd: '/极限词', label: '极限词检查', icon: '🚫', toolId: 'extreme-words-check' },
    { cmd: '/ROI', label: '活动 ROI 计算', icon: '📈', toolId: 'campaign-roi-calc' },
    { cmd: '/佣金', label: '佣金结算计算', icon: '💰', toolId: 'commission-calc' },
    { cmd: '/月报', label: '生成月度报告', icon: '📋', toolId: 'monthly-report-gen' },
    { cmd: '/个税', label: '个税计算', icon: '🧾', toolId: 'iit' },
    { cmd: '/SLA', label: 'SLA达标计算', icon: '📊', toolId: 'sla-calc' },
  ],
  workflows: [
    {
      id: 'auto_cs_loop', name: 'L1 AI Copilot 客服', icon: '🤖',
      description: '只读千牛/飞鸽消息 → 意图分类(13类) → ERP 查单 → AI 生成话术 → 人粘贴发送。人效 3-5 倍，零封号风险。',
      mode: 'sequential',
      deliverable: 'AI 生成的回复话术（已写入剪贴板，客服一键粘贴发送）',
      successCriteria: ['意图识别准确率 ≥ 90%', '首响时间 < 10 秒', 'ERP 数据实时同步'],
      steps: [
        { id: 'listen', agent: 'cs', expert: 'cs_consultant', label: '消息监听',
          goal: '实时监听千牛/飞鸽新消息', successCriteria: ['只读权限，零封号风险'],
          profitImpact: { dimension: 'cost_saving', amount: '自动接收消息，省去人工值守' } },
        { id: 'classify', agent: 'cs', expert: 'cs_consultant', label: '意图识别',
          goal: '13 类意图自动分类', successCriteria: ['分类准确率 ≥ 90%', '覆盖售前/售后/物流/退换货'],
          profitImpact: { dimension: 'cost_saving', amount: '免去人工分拣，效率提升 5 倍' } },
        { id: 'erp_query', agent: 'cs', expert: 'cs_consultant', label: 'ERP 查询',
          goal: 'CDP 读安全区 ERP 订单/物流/库存', successCriteria: ['数据实时', '只读安全区'],
          profitImpact: { dimension: 'cost_saving', amount: '免切换系统查单，每单省 2 分钟' } },
        { id: 'generate', agent: 'cs', expert: 'cs_consultant', label: '话术生成',
          goal: 'AI 生成回复并写入剪贴板', successCriteria: ['话术专业准确', '可一键复制'],
          profitImpact: { dimension: 'cost_saving', amount: '话术自动生成，客服人力省 60%' } },
        { id: 'send', agent: 'cs', expert: 'cs_consultant', label: '人工发送',
          goal: '客服确认后粘贴发送', successCriteria: ['人工确认环节保障质量', '零封号'],
          profitImpact: { dimension: 'loss_avoidance', amount: '人在回路，避免 AI 误回复导致客诉' } },
      ],
      triggerPhrases: ['AI客服', 'Copilot', '话术', '千牛', '飞鸽'],
    },
    {
      id: 'erp_batch_ops', name: 'ERP 批量操作', icon: '🔗',
      description: '批量同步聚水潭/旺店通订单、库存、物流数据到 MBE',
      mode: 'sequential',
      deliverable: '同步报告（成功/失败/异常条目明细）',
      successCriteria: ['数据一致性 100%', '异常订单标记并通知'],
      steps: [
        { id: 'connect', agent: 'cs', expert: 'cs_consultant', label: '连接 ERP',
          goal: '验证 ERP API 连接状态', successCriteria: ['API Key 有效', '权限验证通过'],
          profitImpact: { dimension: 'cost_saving', amount: '自动连接免去人工配置' } },
        { id: 'sync', agent: 'cs', expert: 'cs_consultant', label: '数据同步',
          goal: '拉取新增/更新订单和库存', successCriteria: ['增量同步', '数据完整'],
          profitImpact: { dimension: 'cost_saving', amount: '批量同步省 4 小时人工/日' } },
        { id: 'validate', agent: 'cs', expert: 'cs_consultant', label: '数据校验',
          goal: '校验数据一致性并标记异常', successCriteria: ['异常率 < 1%', '异常条目有处理建议'],
          profitImpact: { dimension: 'loss_avoidance', amount: '数据校验避免发错货/漏发' } },
      ],
      triggerPhrases: ['ERP同步', '聚水潭', '旺店通', '批量同步'],
    },
    {
      id: 'cs_performance_collect', name: '客服绩效采集', icon: '📊',
      description: '自动采集各品牌客服 KPI（首响/解决率/满意度），生成团队绩效看板',
      mode: 'sequential',
      deliverable: '客服绩效报告（按品牌/按人/按时段的 KPI 对比）',
      successCriteria: ['数据覆盖所有服务品牌', 'KPI 计算口径一致'],
      steps: [
        { id: 'collect', agent: 'cs', expert: 'cs_consultant', label: '数据采集',
          goal: '从各平台采集客服工作数据', successCriteria: ['覆盖所有品牌', '数据完整'],
          profitImpact: { dimension: 'cost_saving', amount: '自动采集省 2 小时/日人工统计' } },
        { id: 'analyze', agent: 'cs', expert: 'cs_consultant', label: '绩效分析',
          goal: '按品牌/按人维度计算 KPI', successCriteria: ['首响/解决率/满意度/工单量四维度'],
          profitImpact: { dimension: 'revenue', amount: '数据驱动团队优化，满意度提升 15%' } },
        { id: 'report', agent: 'cs', expert: 'cs_consultant', label: '生成报告',
          goal: '输出可视化绩效看板', successCriteria: ['对比上周/上月趋势', '标注异常指标'],
          profitImpact: { dimension: 'cost_saving', amount: '自动生成报告省 1 天统计人力/月' } },
      ],
      triggerPhrases: ['客服绩效', '绩效报告', '客服KPI', '团队考核'],
    },
    {
      id: 'campaign_operation', name: '大促运营全链路', icon: '🎯',
      description: '输出可执行的大促作战方案，从策划到结算全闭环',
      mode: 'sequential',
      deliverable: '大促作战手册（选品方案 + 投放计划 + 客服预案 + 结算明细）',
      successCriteria: ['选品含 ROI 预估和库存风险', '投放预算分配有数据依据', '客服话术覆盖 Top 10 问题', '结算金额可追溯'],
      steps: [
        { id: 'plan', agent: 'growth', expert: 'growth_consultant', label: '活动策划与选品',
          goal: '确定活动主题、选品和 GMV 目标', successCriteria: ['GMV 目标有往期数据支撑', '选品 ≥ 3 个梯度（引流/利润/形象款）'],
          profitImpact: { dimension: 'revenue', amount: '精选品+策划使大促 GMV 提升 30-50%' } },
        { id: 'content', agent: 'growth', expert: 'content_creator', label: '内容与投放执行',
          goal: '输出各渠道内容和预算分配方案', successCriteria: ['覆盖 ≥ 3 个渠道', '每渠道含 ROI 预估和素材数量'],
          profitImpact: { dimension: 'cost_saving', amount: '内容生产 10 倍提速，投放人力省 60%' } },
        { id: 'cs_ready', agent: 'cs', expert: 'cs_consultant', label: '客服备战与话术',
          goal: '确保客服团队能应对流量高峰', successCriteria: ['话术库覆盖促销规则/退换货/物流查询', '含排班方案和应急预案'],
          profitImpact: { dimension: 'loss_avoidance', amount: '大促零投诉，避免平台罚款 5-10 万' } },
        { id: 'settle', agent: 'finance', expert: 'finance_accountant', label: '活动复盘与结算',
          goal: '输出活动 ROI 和品牌结算明细', successCriteria: ['GMV/费用/利润逐项列出', '佣金计算可追溯到合同条款'],
          profitImpact: { dimension: 'cost_saving', amount: '零差错结算，避免佣金争议损失 2-5 万' } },
      ],
      triggerPhrases: ['大促', '618', '双十一', '活动运营'],
    },
    {
      id: 'monthly_settlement', name: '月度品牌服务结算', icon: '💰',
      description: '确保月度服务费核算准确、双方确认无争议',
      mode: 'sequential',
      deliverable: '月度结算对账单（含服务费明细 + 税务处理）',
      successCriteria: ['数据源与品牌方可交叉验证', '佣金计算引用合同费率条款', '税务处理符合适用税规'],
      steps: [
        { id: 'cs_data', agent: 'cs', expert: 'cs_consultant', label: '客服数据汇总',
          goal: '输出客服工作量和质量指标', successCriteria: ['含工单量/响应时长/解决率等 KPI', '数据源可追溯'],
          profitImpact: { dimension: 'cost_saving', amount: '自动汇总省 1 天人工，月省 2000 元' } },
        { id: 'ops_data', agent: 'growth', expert: 'growth_consultant', label: '运营数据汇总',
          goal: '输出运营效果指标', successCriteria: ['含 GMV/流量/转化率/ROI', '按渠道拆分'],
          profitImpact: { dimension: 'revenue', amount: '数据驱动决策，运营效率提升 40%' } },
        { id: 'commission', agent: 'finance', expert: 'finance_accountant', label: '佣金与费用核算',
          goal: '精确计算服务费和佣金', successCriteria: ['费率引用合同条款', '含基础服务费 + 绩效佣金明细'],
          profitImpact: { dimension: 'loss_avoidance', amount: '佣金零差错，避免品牌方结算争议 2-10 万' } },
        { id: 'tax', agent: 'finance', expert: 'tax_consultant', label: '税务合规检查',
          goal: '确认发票开具和税务处理合规', successCriteria: ['发票税率正确', '进项抵扣合规'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免进项抵扣违规，防止补税 5-20 万' } },
      ],
      triggerPhrases: ['月度结算', '佣金核算', '服务费结算'],
    },
    {
      id: 'brand_onboarding', name: '品牌入驻全流程', icon: '🏪',
      description: '从品牌评估到首月运营的全流程交付，确保入驻即盈利',
      mode: 'sequential',
      deliverable: '品牌入驻交付包（评估报告 + 合同要点 + 客服配置 + 内容规划 + 首月 KPI）',
      successCriteria: ['品牌盈亏测算含 AI Copilot 人效加成', '合同费率条款明确无歧义', '客服 SLA 承诺与成本匹配', '首月内容排期覆盖 3+ 渠道'],
      steps: [
        { id: 'assess', agent: 'sales', expert: 'sales_consultant', label: '品牌评估与盈亏测算',
          goal: '判断该品牌是否值得接入，盈亏平衡点在哪', successCriteria: ['含 GMV 预估、佣金收入、人力成本三项', 'AI Copilot 人效提升后的盈亏平衡点'],
          profitImpact: { dimension: 'loss_avoidance', amount: '筛掉亏损品牌，避免年损 10-30 万' } },
        { id: 'contract', agent: 'legal', expert: 'contract_reviewer', label: '合同审查与签署',
          goal: '确保合同条款保护 TP 方利益', successCriteria: ['费率/SLA/考核/退出条款完整', '知识产权归属明确'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免合同漏洞导致年损 5-20 万' } },
        { id: 'cs_setup', agent: 'cs', expert: 'cs_consultant', label: '客服团队配置',
          goal: '搭建客服体系并配置 AI Copilot', successCriteria: ['话术库覆盖该品类 Top 20 问题', 'SLA 等级与合同承诺匹配'],
          profitImpact: { dimension: 'cost_saving', amount: 'AI Copilot 上线省 60% 客服人力' } },
        { id: 'content', agent: 'growth', expert: 'content_strategist', label: '内容规划与排期',
          goal: '制定首月全渠道内容计划', successCriteria: ['覆盖 3+ 渠道', '含 ROI 预估'],
          profitImpact: { dimension: 'revenue', amount: '首月即有内容曝光，缩短冷启动 2 周' } },
      ],
      triggerPhrases: ['品牌入驻', '新品牌', '品牌接入', '入驻流程'],
    },
    {
      id: 'complaint_escalation', name: '消费者投诉升级处理', icon: '🔥',
      description: '投诉受理到解决的全流程，确保合规且损失最小化',
      mode: 'sequential',
      deliverable: '投诉处理决议书（责任判定 + 合规审查 + 赔偿方案 + 话术模板）',
      successCriteria: ['责任判定引用平台规则和消保法', '赔偿方案在合规范围内且成本最优', '话术模板可直接使用'],
      steps: [
        { id: 'intake', agent: 'cs', expert: 'cs_consultant', label: '投诉受理与分类',
          goal: '快速定性投诉类型和紧急程度', successCriteria: ['投诉类型明确', '紧急程度分级（P1-P4）'],
          profitImpact: { dimension: 'loss_avoidance', amount: '快速响应避免升级到平台介入' } },
        { id: 'liability', agent: 'legal', expert: 'civil_lawyer', label: '责任判定与合规审查',
          goal: '判定责任归属并确认合规处理方式', successCriteria: ['引用消保法/广告法具体条款', '赔偿上限有法规依据'],
          profitImpact: { dimension: 'loss_avoidance', amount: '合规处理避免平台罚款 5-50 万' } },
        { id: 'solution', agent: 'cs', expert: 'cs_consultant', label: '解决方案与话术',
          goal: '输出可执行的解决方案和客服话术', successCriteria: ['含 2-3 个方案（最优/折中/底线）', '话术模板可直接复制使用'],
          profitImpact: { dimension: 'loss_avoidance', amount: '最优方案比直接赔偿省 30-50%' } },
        { id: 'finance', agent: 'finance', expert: 'finance_accountant', label: '赔偿入账与记录',
          goal: '赔偿金额正确入账并归到对应品牌', successCriteria: ['赔偿记入正确科目', '可在品牌台账追溯'],
          profitImpact: { dimension: 'cost_saving', amount: '准确入账避免重复赔偿' } },
      ],
      triggerPhrases: ['投诉', '客诉', '升级处理', '消保', '平台介入'],
    },
  ],
  safetyRules: [
    { id: 'complaint-escalation', label: '投诉自动升级', trigger: '客户提及投诉/12315/消保委', action: '立即转人工，通知运营主管' },
    { id: 'high-value-refund', label: '大额退款审核', trigger: '退款金额 > 500 元', action: '暂停自动处理，需主管确认' },
    { id: 'vip-customer', label: 'VIP 客户专属', trigger: '客户等级为金卡及以上', action: '优先排队+专属话术' },
    { id: 'low-confidence', label: 'AI 信心不足', trigger: 'AI 置信度 < 60%', action: '标记为需人工确认' },
    { id: 'repeat-question', label: '重复提问检测', trigger: '客户连续 2 次提同一问题', action: '升级处理+道歉话术' },
    { id: 'negative-sentiment', label: '负面情绪预警', trigger: '情绪分 < -0.6', action: '预警+安抚话术+人工介入' },
    { id: 'legal-keywords', label: '法律关键词', trigger: '提及律师/法院/起诉', action: '立即转人工+通知法务' },
    { id: 'regulatory-keywords', label: '监管关键词', trigger: '提及工商/市监/消协', action: '立即转人工+通知运营主管' },
  ],
  quickActions: [
    { id: 'start-copilot', label: '开启 AI Copilot', icon: '🤖', workflowId: 'auto_cs_loop', description: '启动 AI 客服 Copilot，自动读消息+生成话术', cta: '立即开启' },
    { id: 'new-brand', label: '新品牌入驻', icon: '🏪', workflowId: 'brand_onboarding', description: '启动标准化品牌接入流程（3 天完成）', cta: '开始入驻' },
    { id: 'monthly-settle', label: '月度结算', icon: '💰', workflowId: 'monthly_settlement', description: '一键启动月度佣金核算和对账', cta: '开始结算' },
    { id: 'complaint-handle', label: '投诉处理', icon: '🚨', workflowId: 'complaint_escalation', description: 'AI 辅助投诉分析+方案生成（30 分钟）', cta: '处理投诉' },
  ],
  scenarios: [
    { id: 'start_copilot', label: '开启 AI Copilot 客服', icon: '🤖', prompt: '现在 5 个客服每天处理 250 条消息，开启 AI Copilot 后人效能提升多少？值不值得投入？每月能省多少人力成本？', expectedOutcome: '人效对比分析 + ROI 测算 + 实施步骤', workflowId: 'auto_cs_loop', profitImpact: { dimension: 'cost_saving', amount: '人效 3-5 倍提升，同样团队服务更多品牌，零封号风险' } },
    { id: 'brand_onboard', label: '新品牌入驻', icon: '🏪', prompt: '新品牌入驻的对接流程和注意事项', expectedOutcome: '入驻检查清单 + 时间排期 + 合同要点 + 盈亏测算', workflowId: 'brand_onboarding', profitImpact: { dimension: 'revenue', amount: '新品牌年佣金增收 20-50 万' } },
    { id: 'campaign_roi', label: '大促 ROI 分析', icon: '📊', prompt: '分析本次营销活动的投入产出比', expectedOutcome: 'ROI 计算过程 + 渠道对比 + 优化建议', expert: 'growth.growth_consultant', workflowId: 'campaign_operation', profitImpact: { dimension: 'revenue', amount: '精准投放优化 ROI 3:1，增收 100 万+' } },
    { id: 'complaint', label: '客诉升级处理', icon: '🔥', prompt: '处理这个升级客诉，需要合规和赔偿方案', expectedOutcome: '处理方案 + 话术模板 + 赔偿金额 + 消保法引用', workflowId: 'complaint_escalation', profitImpact: { dimension: 'loss_avoidance', amount: '避免平台处罚 + 赔偿损失 5-20 万' } },
    { id: 'settlement_check', label: '月度佣金核算', icon: '💰', prompt: '核算本月品牌服务佣金和费用明细', expectedOutcome: '佣金明细 + 发票金额 + 税务处理', workflowId: 'monthly_settlement', profitImpact: { dimension: 'loss_avoidance', amount: '零差错结算，避免对账争议 2-10 万' } },
    { id: 'contract_review', label: '代运营合同审查', icon: '📋', prompt: '审查品牌代运营合同的关键条款和风险点', expectedOutcome: '条款风险清单 + 修改建议 + 费率确认', expert: 'legal.contract_reviewer', profitImpact: { dimension: 'loss_avoidance', amount: '避免合同陷阱损失 5-20 万' } },
    { id: 'competitor_analysis', label: '竞品分析', icon: '🔍', prompt: '为品牌做竞品分析和差异化建议', expectedOutcome: '竞品矩阵 + 价格带分析 + 差异化策略', expert: 'sales.sales_consultant', profitImpact: { dimension: 'revenue', amount: '差异化定位提升品牌 GMV 15-30%' } },
  ],
}

export default ecommerceBrandServiceSolution
