/**
 * 自动拆分自 solution-registry-data.ts。
 * 请勿手工编辑“结构”——如需改方案内容，请直接改本文件字段即可。
 */
import type { SolutionConfig } from '../solution-router'
import { agent } from '../solution-router-agent'

export const financeTaxServiceSolution: SolutionConfig = {
  id: 'finance-tax-service',
  name: '财税专业服务解决方案',
  icon: '📊',
  color: '#00d4aa',
  tagline: '统一派遣 AI 专家团队 — 记账报税、审计辅助、税务筹划、合规审查全链路',
  description:
    '为会计师事务所、审计师事务所、税务师事务所统一派遣 AI 专家团队，覆盖记账报税、审计辅助、税务筹划、合规审查全链路。',
  entrepreneurPurpose: '同样团队服务 3 倍客户，净利润率从 15% 提到 40%',
  profitMetrics: ['人效 30 家→100 家客户/会计', '凭证 2h→3min', '税务筹划提高客单价'],
  valueEquivalent: { humanHours: 24, mbeMinutes: 3, acceleration: '480x' },
  agents: [
    agent('finance', 8002, '记账报税专家', '发票识别、凭证生成、纳税申报'),
    agent('finance', 8002, '审计分析专家', '审计底稿、报表分析、异常检测'),
    agent('finance', 8002, '税务筹划专家', '税务方案设计、优惠政策匹配、风险评估'),
    agent('legal', 8003, '合规审查专家', '会计准则校验、税务合规、法规更新'),
  ],
  localScripts: ['calc_iit', 'calc_vat'],
  knowledgeCache: ['tax_law_basics', 'accounting_standards'],
  theme: { primary: '164 100% 42%', accent: '164 100% 42%' },
  enabledTabs: ['today', 'bookkeeping', 'invoices', 'tax-filing', 'reports', 'tax-planning', 'tools', 'documents', 'chat', 'dashboard', 'knowledge-graph'],
  onboarding: {
    questions: [
      { key: 'taxpayer_type', label: '纳税人类型', options: ['一般纳税人', '小规模纳税人'] },
      { key: 'client_count', label: '服务客户数量', options: ['1-10家', '10-50家', '50家以上'] },
      { key: 'industry', label: '主要行业', options: ['商贸', '服务', '制造', '建筑', '科技', '其他'] },
    ],
  },
  tools: [
    { id: 'iit', type: 'calculator', name: '个税计算器', icon: '🧾',
      agent: 'finance', apiPath: '/api/finance/calc/iit', localScript: 'calc_iit',
      fields: [
        { key: 'salary', label: '税前月薪（元）', type: 'currency', required: true },
        { key: 'insurance', label: '五险一金（元）', type: 'currency', default: 0 },
        { key: 'deduction', label: '专项附加扣除（元）', type: 'currency', default: 0 },
      ],
    },
    { id: 'vat', type: 'calculator', name: 'VAT 計算器', icon: '📊',
      agent: 'finance', apiPath: '/api/finance/calc/vat', localScript: 'calc_vat',
      fields: [
        { key: 'amount', label: '含税金额（元）', type: 'currency', required: true },
        { key: 'rate', label: '税率', type: 'select', required: true,
          options: [
            { value: '0.13', label: '13%' }, { value: '0.09', label: '9%' },
            { value: '0.06', label: '6%' }, { value: '0.03', label: '3%（小规模）' },
          ] },
      ],
    },
    { id: 'stamp-tax', type: 'calculator', name: '印花税计算器', icon: '📌',
      agent: 'finance', apiPath: '/api/finance/calc/stamp-tax',
      description: '合同/凭证印花税精确计算（11类合同税率速查）',
      fields: [
        { key: 'contract_type', label: '合同类型', type: 'select', required: true,
          options: [
            { value: 'purchase_sale', label: '买卖合同（0.03%）' },
            { value: 'processing', label: '加工承揽（0.05%）' },
            { value: 'construction', label: '建设工程（0.03%）' },
            { value: 'transport', label: '运输合同（0.03%）' },
            { value: 'technology', label: '技术合同（0.03%）' },
            { value: 'lease', label: '租赁合同（0.1%）' },
            { value: 'warehouse', label: '仓储保管（0.1%）' },
            { value: 'loan', label: '借款合同（0.005%）' },
            { value: 'property_insurance', label: '财产保险（0.1%）' },
            { value: 'property_transfer', label: '产权转移（0.05%）' },
            { value: 'business_book', label: '营业账簿（0.025%）' },
          ] },
        { key: 'amount', label: '合同金额（元）', type: 'currency', required: true },
      ],
    },
    { id: 'cit-quarterly', type: 'calculator', name: '企业所得税预缴', icon: '🏢',
      agent: 'finance', apiPath: '/api/finance/calc/cit-quarterly',
      description: '季度企业所得税预缴计算（含小微企业优惠）',
      fields: [
        { key: 'quarterly_profit', label: '季度利润总额（元）', type: 'currency', required: true },
        { key: 'is_small_profit', label: '是否小微企业', type: 'select', default: 'false',
          options: [
            { value: 'true', label: '是（年应纳税所得额≤300万）' },
            { value: 'false', label: '否' },
          ] },
      ],
    },
    {
      id: 'voucher-gen', type: 'document-ai', name: '智能凭证生成', icon: '📒',
      agent: 'finance', apiPath: '/api/finance/documents/upload',
      description: '上传发票/银行回单，AI 自动识别并生成记账凭证（含借贷科目和金额）',
      acceptTypes: ['.jpg', '.png', '.pdf', '.xlsx'],
    },
    { id: 'bank-feed', type: 'batch-processor', name: '银行流水自动对账', icon: '🏦',
      agent: 'finance', apiPath: '/api/finance/bank/feed-reconcile',
      description: '上传银行流水，AI 自动匹配已有凭证，未匹配项一键生成新凭证',
      acceptTypes: ['.xlsx', '.csv'],
      fields: [
        { key: 'period', label: '对账期间', type: 'text', required: true },
      ],
    },
    { id: 'recurring-voucher', type: 'automation', name: '定期凭证管理', icon: '🔄',
      agent: 'finance', apiPath: '/api/finance/vouchers/recurring',
      description: '设置房租/工资/折旧/摊销等定期自动生成凭证，到期自动执行',
      fields: [
        { key: 'template_name', label: '模板名称', type: 'text', required: true },
        { key: 'recurrence', label: '重复周期', type: 'select', required: true,
          options: [
            { value: 'monthly', label: '每月' }, { value: 'quarterly', label: '每季' },
            { value: 'yearly', label: '每年' },
          ] },
        { key: 'amount', label: '金额（元）', type: 'currency', required: true },
      ],
    },
    { id: 'coa-wizard', type: 'setup-wizard', name: '行业科目表初始化', icon: '📑',
      agent: 'finance', apiPath: '/api/finance/companies/coa-init',
      description: '新客户建账：根据行业自动生成标准科目表（商贸/服务/制造/建筑/科技/餐饮）',
      fields: [
        { key: 'industry', label: '行业类型', type: 'select', required: true,
          options: [
            { value: 'trade', label: '商贸流通' }, { value: 'service', label: '现代服务' },
            { value: 'manufacturing', label: '生产制造' }, { value: 'construction', label: '建筑施工' },
            { value: 'tech', label: '科技/软件' }, { value: 'catering', label: '餐饮住宿' },
          ] },
        { key: 'taxpayer_type', label: '纳税人类型', type: 'select', required: true,
          options: [
            { value: 'general', label: '一般纳税人' }, { value: 'small', label: '小规模纳税人' },
          ] },
      ],
    },
    { id: 'auditor-view', type: 'access-control', name: '审计师只读副本', icon: '👁️',
      agent: 'finance', apiPath: '/api/finance/audit/readonly-view',
      description: '为外部审计师生成只读数据副本（凭证/报表/科目余额），审计结束自动回收权限',
      fields: [
        { key: 'period', label: '审计期间', type: 'text', required: true },
        { key: 'auditor_name', label: '审计师姓名', type: 'text', required: true },
      ],
    },
    { id: 'client-pnl', type: 'report', name: '客户利润排行', icon: '📈',
      agent: 'finance', apiPath: '/api/finance/dashboard/pnl-by-client',
      description: '按客户维度的收入/成本/利润排行，识别高价值客户和亏损客户',
      fields: [
        { key: 'period', label: '分析期间', type: 'text', required: true },
      ],
    },
    { id: 'materiality-calc', type: 'calculator', name: '重要性水平计算', icon: '📐',
      agent: 'finance', apiPath: '/api/finance/calc/materiality',
      description: '根据基准（税前利润/营收/总资产）计算三级重要性水平',
      fields: [
        { key: 'benchmark_type', label: '基准选择', type: 'select', required: true,
          options: [
            { value: 'pretax_profit', label: '税前利润' }, { value: 'revenue', label: '营业收入' },
            { value: 'total_assets', label: '总资产' }, { value: 'equity', label: '净资产' },
          ] },
        { key: 'benchmark_amount', label: '基准金额（万元）', type: 'currency', required: true },
      ],
    },
    { id: 'sampling-calc', type: 'calculator', name: '审计抽样计算', icon: '🎲',
      agent: 'finance', apiPath: '/api/finance/calc/audit-sampling',
      description: '根据总体规模和可容忍错报计算样本量',
      fields: [
        { key: 'sampling_method', label: '抽样方法', type: 'select', required: true,
          options: [
            { value: 'attribute', label: '属性抽样（控制测试）' },
            { value: 'mus', label: '货币单元抽样（MUS）' },
            { value: 'classical', label: '经典变量抽样' },
          ] },
        { key: 'population_size', label: '总体规模', type: 'number', required: true },
        { key: 'tolerable_error', label: '可容忍错报/偏差率', type: 'number', required: true },
      ],
    },
    { id: 'confirmation-gen', type: 'doc-generator', name: '函证生成器', icon: '📮',
      agent: 'finance', apiPath: '/api/finance/ai/confirmation-gen',
      description: '批量生成应收/应付/银行标准询证函',
      fields: [
        { key: 'confirm_type', label: '函证类型', type: 'select', required: true,
          options: [
            { value: 'ar', label: '应收账款' }, { value: 'ap', label: '应付账款' },
            { value: 'bank', label: '银行' }, { value: 'related', label: '关联方' },
          ] },
        { key: 'style', label: '函证方式', type: 'select', required: true,
          options: [
            { value: 'positive', label: '积极式' }, { value: 'negative', label: '消极式' },
          ] },
      ],
    },
    { id: 'fraud-scan', type: 'document-ai', name: '舞弊风险筛查', icon: '🔎',
      agent: 'finance', apiPath: '/api/finance/ai/fraud-screening',
      description: '上传日记账/明细账，AI 全量扫描异常交易模式',
      acceptTypes: ['.xlsx', '.csv'],
      fields: [
        { key: 'period', label: '审计期间', type: 'text', required: true },
      ],
    },
  ],
  slashCommands: [
    { cmd: '/个税', label: '个税计算', icon: '🧾', toolId: 'iit' },
    { cmd: '/VAT', label: 'VAT 計算', icon: '📊', toolId: 'vat' },
    { cmd: '/印花税', label: '印花税计算', icon: '📌', toolId: 'stamp-tax' },
    { cmd: '/企业所得税', label: '企业所得税预缴', icon: '🏢', toolId: 'cit-quarterly' },
    { cmd: '/凭证', label: '智能凭证生成', icon: '📒', toolId: 'voucher-gen' },
    { cmd: '/记账', label: '月度记账流程', icon: '📒', description: '启动月度记账全流程' },
    { cmd: '/对账', label: '银行流水对账', icon: '🏦', toolId: 'bank-feed' },
    { cmd: '/定期凭证', label: '定期凭证管理', icon: '🔄', toolId: 'recurring-voucher' },
    { cmd: '/科目表', label: '行业科目表初始化', icon: '📑', toolId: 'coa-wizard' },
    { cmd: '/客户利润', label: '客户利润排行', icon: '📈', toolId: 'client-pnl' },
    { cmd: '/重要性', label: '重要性水平计算', icon: '📐', toolId: 'materiality-calc' },
    { cmd: '/抽样', label: '审计抽样', icon: '🎲', toolId: 'sampling-calc' },
    { cmd: '/函证', label: '生成函证', icon: '📮', toolId: 'confirmation-gen' },
    { cmd: '/舞弊', label: '舞弊筛查', icon: '🔎', toolId: 'fraud-scan' },
  ],
  safetyRules: [
    { id: 'unbalanced-voucher', label: '借贷不平衡拦截', trigger: '凭证借方合计 ≠ 贷方合计', action: '阻止保存，提示差额' },
    { id: 'duplicate-voucher', label: '重复凭证检测', trigger: '同日期同金额同摘要', action: '弹窗警告' },
    { id: 'large-amount-review', label: '大额凭证复核', trigger: '单笔 > 50 万', action: '标记需主管复核' },
    { id: 'period-locked', label: '已关账期间保护', trigger: '修改已关账凭证', action: '拒绝操作' },
    { id: 'tax-deadline-alert', label: '申报截止提醒', trigger: '距截止 ≤ 3 天未申报', action: '红色预警' },
    { id: 'audit-trail-protect', label: '审计轨迹保护', trigger: '凭证修改/删除/冲红', action: '强制记录' },
    { id: 'workpaper-lock', label: '底稿锁定保护', trigger: '复核后底稿被修改', action: '拒绝修改，需合伙人解锁' },
    { id: 'materiality-threshold-alert', label: '重要性水平预警', trigger: '累计错报超实际执行重要性', action: '扩大审计范围' },
    { id: 'dual-signoff', label: '双签审核', trigger: '审计报告出具前', action: '经理+合伙人双签' },
    { id: 'independence-check', label: '独立性检查', trigger: '接受新项目', action: '利益冲突检测' },
    { id: 'confirmation-control', label: '函证控制', trigger: '函证发出/回收', action: '审计师全程控制' },
  ],
  quickActions: [
    { id: 'new-voucher', label: '录入凭证', icon: '📝', workflowId: 'monthly_bookkeeping', description: 'AI 自动生成借贷分录', cta: '开始录入' },
    { id: 'bank-reconcile', label: '银行对账', icon: '🏦', workflowId: 'bank_feed_reconcile', description: '上传流水自动匹配凭证', cta: '开始对账' },
    { id: 'month-close', label: '月末结账', icon: '🔒', workflowId: 'monthly_bookkeeping', description: '核对→报表→关账', cta: '开始结账' },
    { id: 'tax-filing', label: '报税助手', icon: '📋', workflowId: 'tax_planning', description: '各税种应缴金额和申报表草稿', cta: '开始报税' },
    { id: 'audit-check', label: '审计检查', icon: '🔍', workflowId: 'audit_analysis', description: '异常检测+审计底稿', cta: '开始审计' },
    { id: 'new-client', label: '新客户建账', icon: '📑', workflowId: 'coa_setup', description: '行业科目表 3 分钟建账', cta: '开始建账' },
    { id: 'new-audit-project', label: '新审计项目', icon: '📋', description: '风险评估→重要性→审计计划', cta: '创建项目' },
    { id: 'materiality', label: '重要性水平', icon: '📐', description: 'AI 自动计算三级重要性', cta: '开始计算' },
    { id: 'sampling', label: '审计抽样', icon: '🎲', description: '方法选择+样本量+选样', cta: '设计抽样' },
    { id: 'confirmation', label: '智能函证', icon: '📮', description: '批量生成+跟踪+差异调查', cta: '生成函证' },
    { id: 'fraud', label: '舞弊筛查', icon: '🔎', description: '日记账全量扫描+关联方', cta: '开始筛查' },
    { id: 'audit-report', label: '审计报告', icon: '📄', description: '汇总→评估→报告+建议书', cta: '生成报告' },
  ],
  workflows: [
    {
      id: 'monthly_bookkeeping', name: '月度记账报税', icon: '📒',
      description: '确保月度账务准确完整、报表合规、按时申报',
      mode: 'sequential',
      deliverable: '月度财务报表 + 纳税申报确认单',
      successCriteria: [
        '凭证与发票一一对应，无遗漏',
        '资产负债表平衡（借贷差 = 0）',
        '纳税申报数据与账务一致',
      ],
      steps: [
        { id: 'invoice', agent: 'finance', expert: 'finance_accountant', label: '发票归集与核验',
          goal: '确认全部发票真实、合规、已入账', successCriteria: ['列出发票总数和金额汇总', '标注异常发票（抬头/税号/金额不符）'],
          profitImpact: { dimension: 'loss_avoidance', amount: '拦截异常发票，避免税务风险 5-50 万' } },
        { id: 'voucher', agent: 'finance', expert: 'finance_accountant', label: '记账凭证生成',
          goal: '生成完整准确的会计凭证', successCriteria: ['每笔凭证含借贷科目和金额', '引用会计准则条款'],
          profitImpact: { dimension: 'cost_saving', amount: '凭证生成 2h→3min，月省会计人力 3 天' } },
        { id: 'report', agent: 'finance', expert: 'finance_accountant', label: '财务报表编制',
          goal: '编制三张主要报表并校验勾稽', successCriteria: ['资产=负债+所有者权益', '利润表与现金流量表交叉验证'],
          profitImpact: { dimension: 'cost_saving', amount: '报表自动编制，月省编表时间 2 天' } },
        { id: 'tax_filing', agent: 'finance', expert: 'tax_consultant', label: '纳税申报',
          goal: '确定各税种申报金额和截止日期', successCriteria: ['各稅種申報金額明確', '标注申报截止日和注意事项'],
          profitImpact: { dimension: 'loss_avoidance', amount: '按时准确申报，避免滞纳金和罚款' } },
      ],
      triggerPhrases: ['月度记账', '记账报税', '月末结账'],
    },
    {
      id: 'tax_planning', name: '税务筹划方案', icon: '💡',
      description: '在合法合规前提下降低企业综合税负',
      mode: 'sequential',
      deliverable: '税务筹划方案书（现状 + 风险 + 方案 + 合规确认）',
      successCriteria: [
        '方案预计节税金额有精确测算',
        '每项筹划措施引用税法依据',
        '合规性经法律专家确认',
      ],
      steps: [
        { id: 'diagnosis', agent: 'finance', expert: 'tax_consultant', label: '税务现状诊断',
          goal: '摸清当前税负结构和优化空间', successCriteria: ['列出各税种实际税负率', '对标行业平均税负率'],
          profitImpact: { dimension: 'cost_saving', amount: '发现节税空间 3-15 万/年' } },
        { id: 'risk', agent: 'finance', expert: 'tax_consultant', label: '税务风险评估',
          goal: '识别现有税务操作中的风险点', successCriteria: ['逐项标注风险等级和金额影响', '含近三年税务稽查关注点'],
          profitImpact: { dimension: 'loss_avoidance', amount: '识别风险点避免稽查处罚 10-100 万' } },
        { id: 'plan', agent: 'finance', expert: 'tax_consultant', label: '筹划方案设计',
          goal: '输出 ≥ 2 套可行筹划方案并对比', successCriteria: ['每套方案含实施步骤和预期节税金额', '对比实施成本和风险'],
          profitImpact: { dimension: 'cost_saving', amount: '节税方案落地后年省 5-30 万' } },
        { id: 'compliance', agent: 'legal', expert: 'civil_lawyer', label: '合规性检查',
          goal: '确认筹划方案不触碰法律红线', successCriteria: ['逐方案给出合规/存疑/违规结论', '引用税法和刑法相关条款'],
          profitImpact: { dimension: 'loss_avoidance', amount: '合规把关避免偷逃税刑事风险' } },
      ],
      triggerPhrases: ['税务筹划', '节税方案', '合理避税'],
    },
    {
      id: 'audit_analysis', name: '审计异常检测', icon: '🔍',
      description: '并行分析财务比率和准则合规，自动检测异常并生成审计底稿',
      mode: 'parallel',
      deliverable: '异常检测报告 + 审计底稿初稿',
      successCriteria: [
        '20+ 财务比率计算完成并对标行业',
        '大额凭证/科目偏离/未审核堆积等异常逐项列出',
        '每项异常含审计准则引用（ISA/CAS）',
      ],
      steps: [
        { id: 'ratio_analysis', agent: 'finance', expert: 'finance_accountant', label: '财务比率分析',
          goal: '计算流动比率/速动比率/ROE 等 20+ 指标并对标行业', successCriteria: ['列出所有异常指标及偏离幅度', '标注同比/环比变动'],
          profitImpact: { dimension: 'cost_saving', amount: '比率分析从 3 小时缩短到 5 分钟' } },
        { id: 'compliance_check', agent: 'legal', expert: 'civil_lawyer', label: '准则合规校验',
          goal: '校验会计处理是否符合企业会计准则', successCriteria: ['逐科目检查准则符合性', '标注不合规项及准则条文'],
          profitImpact: { dimension: 'loss_avoidance', amount: '提前发现准则问题，避免审计调整 10-50 万' } },
        { id: 'workpaper_draft', agent: 'finance', expert: 'finance_accountant', label: '底稿初稿',
          goal: '汇总异常项生成审计底稿初稿', successCriteria: ['底稿含索引号/科目/异常描述/审计结论', '引用审计准则 1101/1315'],
          profitImpact: { dimension: 'cost_saving', amount: '底稿编制从半天缩短到 15 分钟' } },
      ],
      triggerPhrases: ['审计检查', '异常检测', '审计底稿', '审计分析'],
    },
    {
      id: 'bank_feed_reconcile', name: '银行流水自动对账', icon: '🏦',
      description: '上传银行流水，AI 自动匹配已有凭证，差异项标注原因并一键补录',
      mode: 'sequential',
      deliverable: '银行余额调节表 + 未达账项清单 + 补录凭证',
      successCriteria: [
        '银行流水逐笔与账面凭证匹配',
        '未匹配项逐项标注原因（未入账/金额差异/时间差异）',
        '银行余额调节表借贷平衡',
      ],
      steps: [
        { id: 'import', agent: 'finance', expert: 'finance_accountant', label: '流水导入解析',
          goal: '解析银行流水文件，提取收支明细', successCriteria: ['列出流水总笔数和收支汇总', '标注异常格式行'],
          profitImpact: { dimension: 'cost_saving', amount: '流水导入从手工录入 1 小时缩短到 1 分钟' } },
        { id: 'match', agent: 'finance', expert: 'finance_accountant', label: '智能匹配凭证',
          goal: 'AI 按金额+日期+摘要自动匹配', successCriteria: ['匹配率 ≥ 90%', '差异项逐笔列出原因'],
          profitImpact: { dimension: 'cost_saving', amount: '对账从 2 小时缩短到 5 分钟' } },
        { id: 'reconcile', agent: 'finance', expert: 'finance_accountant', label: '差异处理与补录',
          goal: '未匹配项一键生成凭证，输出调节表', successCriteria: ['调节表借贷平衡', '未达账项全部处理'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免银行对账差异导致审计问题' } },
      ],
      triggerPhrases: ['银行对账', '流水匹配', '银行余额调节'],
    },
    {
      id: 'coa_setup', name: '新客户建账', icon: '📑',
      description: '新客户接入时，根据行业自动生成标准科目表并导入期初余额',
      mode: 'sequential',
      deliverable: '完整科目表 + 辅助核算设置 + 期初余额表',
      successCriteria: [
        '科目表覆盖行业常用科目 95%+',
        '辅助核算项（客户/供应商/项目）设置完整',
        '期初余额试算平衡',
      ],
      steps: [
        { id: 'industry_match', agent: 'finance', expert: 'finance_accountant', label: '行业匹配',
          goal: '根据客户信息匹配行业标准科目表', successCriteria: ['确认行业分类', '加载对应模板'],
          profitImpact: { dimension: 'cost_saving', amount: '新客户建账从半天缩短到 3 分钟' } },
        { id: 'coa_generate', agent: 'finance', expert: 'finance_accountant', label: '科目表生成',
          goal: '生成科目表并适配纳税人类型', successCriteria: ['一级到四级科目完整', '进项/销项税额科目正确'],
          profitImpact: { dimension: 'cost_saving', amount: '不再手工逐个添加科目' } },
        { id: 'balance_import', agent: 'finance', expert: 'finance_accountant', label: '期初余额导入',
          goal: '导入期初余额并验证平衡', successCriteria: ['资产=负债+权益', '各科目余额方向正确'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免期初错误影响全年账务' } },
      ],
      triggerPhrases: ['新客户建账', '科目表初始化', '新建账套'],
    },
    {
      id: 'audit_planning', name: '审计计划与风险评估', icon: '📋',
      description: '新项目承接：AI 自动分析行业风险、计算重要性、编制审计计划书',
      mode: 'sequential',
      deliverable: '审计计划书（审计范围 + 时间安排 + 人员分工 + 重要性水平 + 重点领域）',
      successCriteria: ['行业风险和经营风险识别完整', '三级重要性水平计算有依据', '审计范围和重点领域明确'],
      steps: [
        { id: 'info_collect', agent: 'finance', expert: 'finance_accountant', label: '信息收集',
          goal: '收集被审计单位基本信息和前期底稿',
          successCriteria: ['企业基本信息完整', '前期审计问题已梳理'],
          profitImpact: { dimension: 'cost_saving', amount: '信息收集自动化，省 2 小时' } },
        { id: 'risk_assess', agent: 'finance', expert: 'finance_accountant', label: '风险评估',
          goal: '识别行业风险、经营风险和重大错报风险',
          successCriteria: ['行业风险分析完整', '经营风险逐项列出', '重大错报风险矩阵'],
          profitImpact: { dimension: 'loss_avoidance', amount: '全面风险识别避免审计遗漏' } },
        { id: 'materiality', agent: 'finance', expert: 'finance_accountant', label: '重要性确定',
          goal: '计算三级重要性水平',
          successCriteria: ['基准选择有依据', '整体/执行/微小三级计算完成'],
          profitImpact: { dimension: 'cost_saving', amount: '重要性计算从 1 小时到 3 分钟' } },
        { id: 'plan_draft', agent: 'finance', expert: 'finance_accountant', label: '计划编制',
          goal: '输出完整审计计划书',
          successCriteria: ['审计范围/时间/人员/重点全覆盖'],
          profitImpact: { dimension: 'cost_saving', amount: '审计计划编制从 2 天到 1 小时' } },
      ],
      triggerPhrases: ['审计计划', '新项目', '风险评估', '审计方案'],
    },
    {
      id: 'fraud_screening', name: '舞弊风险智能筛查', icon: '🔎',
      description: '日记账全量扫描+关联方检测+收入截止测试，输出舞弊风险矩阵',
      mode: 'parallel',
      deliverable: '舞弊风险矩阵（红/黄/绿标注 + 异常交易明细 + 深入调查建议）',
      successCriteria: ['日记账全量扫描无遗漏', '关联方交易识别完整', '收入确认测试覆盖'],
      steps: [
        { id: 'journal_scan', agent: 'finance', expert: 'finance_accountant', label: '日记账全量扫描',
          goal: '识别异常时间/金额/摘要/对手方模式',
          successCriteria: ['月末大额手工调整', '非工作时间分录', '整数金额异常'],
          profitImpact: { dimension: 'loss_avoidance', amount: '发现舞弊线索避免重大损失 50-500 万' } },
        { id: 'related_party', agent: 'finance', expert: 'finance_accountant', label: '关联方检测',
          goal: '识别隐性关联方和异常定价',
          successCriteria: ['未披露关联方识别', '非公允定价标注'],
          profitImpact: { dimension: 'loss_avoidance', amount: '关联方舞弊是最常见财务造假手段' } },
        { id: 'revenue_test', agent: 'finance', expert: 'finance_accountant', label: '收入截止测试',
          goal: '验证收入确认条件和归属期间',
          successCriteria: ['期末收入截止准确', '确认条件满足'],
          profitImpact: { dimension: 'loss_avoidance', amount: '收入虚增是最高风险审计领域' } },
        { id: 'risk_matrix', agent: 'finance', expert: 'finance_accountant', label: '风险矩阵输出',
          goal: '汇总舞弊风险评级',
          successCriteria: ['红/黄/绿分级', '每项有依据和建议'],
          profitImpact: { dimension: 'cost_saving', amount: '舞弊筛查从 1 天到 30 分钟' } },
      ],
      triggerPhrases: ['舞弊', '日记账测试', '关联方', '造假'],
    },
    {
      id: 'confirmation_management', name: '智能函证管理', icon: '📮',
      description: '函证全生命周期：筛选对象→批量生成→发函跟踪→差异调查→替代程序',
      mode: 'sequential',
      deliverable: '函证汇总表（发函/回函/差异/替代程序全记录）',
      successCriteria: ['函证范围覆盖充分', '回函差异逐项调查', '未回函有替代程序'],
      steps: [
        { id: 'select', agent: 'finance', expert: 'finance_accountant', label: '函证对象筛选',
          goal: '根据重要性和金额确定函证范围',
          successCriteria: ['大额客户/供应商全覆盖', '银行函证覆盖所有开户行'],
          profitImpact: { dimension: 'cost_saving', amount: '筛选自动化，省 2 小时' } },
        { id: 'generate', agent: 'finance', expert: 'finance_accountant', label: '批量生成函证',
          goal: '自动填充金额和地址，生成标准询证函',
          successCriteria: ['模板格式标准', '金额与账面一致'],
          profitImpact: { dimension: 'cost_saving', amount: '函证编制从 1 天到 1 小时' } },
        { id: 'track', agent: 'finance', expert: 'finance_accountant', label: '回函跟踪',
          goal: '跟踪发函/回函状态，标注差异',
          successCriteria: ['回函率统计', '差异金额逐笔列出'],
          profitImpact: { dimension: 'cost_saving', amount: '跟踪自动化，零遗漏' } },
        { id: 'alternative', agent: 'finance', expert: 'finance_accountant', label: '替代程序',
          goal: '未回函项目设计替代审计程序',
          successCriteria: ['替代程序覆盖未回函项', '程序充分有效'],
          profitImpact: { dimension: 'loss_avoidance', amount: '替代程序避免审计覆盖不足' } },
      ],
      triggerPhrases: ['函证', '询证函', '回函', '银行确认'],
    },
    {
      id: 'audit_report_gen', name: '审计报告生成', icon: '📄',
      description: '汇总全部审计发现→评估累计错报→判定意见类型→生成报告+管理层建议书',
      mode: 'sequential',
      deliverable: '审计报告初稿 + 管理层建议书（内控缺陷 + 改进建议）',
      successCriteria: ['全部审计发现汇总完整', '意见类型判定有依据', '管理层建议可执行'],
      steps: [
        { id: 'summarize', agent: 'finance', expert: 'finance_accountant', label: '发现汇总',
          goal: '汇总全部审计发现和未更正错报',
          successCriteria: ['错报按科目分类', '累计金额计算准确'],
          profitImpact: { dimension: 'cost_saving', amount: '自动汇总省 4 小时' } },
        { id: 'evaluate', agent: 'finance', expert: 'finance_accountant', label: '影响评估',
          goal: '评估累计错报是否超过重要性',
          successCriteria: ['与三级重要性对比', '影响判定有依据'],
          profitImpact: { dimension: 'loss_avoidance', amount: '精准评估避免审计意见偏差' } },
        { id: 'report_draft', agent: 'finance', expert: 'finance_accountant', label: '报告生成',
          goal: '生成审计报告初稿（含意见类型自动判定）',
          successCriteria: ['报告格式标准', '意见段措辞准确', '引用准则条文'],
          profitImpact: { dimension: 'cost_saving', amount: '报告编制从 2 天到 1 小时' } },
        { id: 'management_letter', agent: 'finance', expert: 'finance_accountant', label: '管理层建议书',
          goal: '输出内控缺陷和改进建议',
          successCriteria: ['缺陷按严重程度分级', '建议具体可执行'],
          profitImpact: { dimension: 'revenue', amount: '高质量建议书提升客户粘性' } },
      ],
      triggerPhrases: ['审计报告', '审计意见', '管理建议书'],
    },
  ],
  scenarios: [
    { id: 'invoice_check', label: '发票合规检查', icon: '🧾', prompt: '检查这批发票是否合规', expectedOutcome: '逐张发票合规/异常判定 + 异常原因 + 处理建议', expert: 'finance.finance_accountant', profitImpact: { dimension: 'loss_avoidance', amount: '避免虚开发票风险，防止稽查处罚 5-50 万' } },
    { id: 'tax_calc', label: '企业税负测算', icon: '📊', prompt: '测算当前企业整体税负率', expectedOutcome: '各税种税负率 + 综合税负率 + 行业对标', expert: 'finance.tax_consultant', profitImpact: { dimension: 'cost_saving', amount: '发现节税空间，年省 3-30 万' } },
    { id: 'annual_audit', label: '年审准备', icon: '📋', prompt: '准备年度审计需要的材料清单和注意事项', expectedOutcome: '完整材料清单（含科目余额表/银行对账单等）+ 常见问题预警', expert: 'finance.finance_accountant', profitImpact: { dimension: 'loss_avoidance', amount: '避免审计问题导致处罚，防损 5-20 万' } },
    { id: 'audit_anomaly', label: '审计异常速查', icon: '🔍', prompt: '应收账款周转率异常下降，帮我分析可能原因', expectedOutcome: '异常原因分析 + 风险等级 + 进一步审计程序建议', expert: 'finance.finance_accountant', profitImpact: { dimension: 'cost_saving', amount: '异常定位从 2 小时缩短到 5 分钟' } },
    { id: 'audit_workpaper', label: '审计底稿编制', icon: '📑', prompt: '帮我编制应收账款函证替代程序审计底稿', expectedOutcome: '完整底稿（含替代程序/检查步骤/结论/准则引用）', expert: 'finance.finance_accountant', profitImpact: { dimension: 'cost_saving', amount: '底稿编制效率提升 10 倍' } },
    { id: 'voucher_entry', label: '快速做凭证', icon: '📒', prompt: '帮我做一张记账凭证', expectedOutcome: '完整借贷分录 + 科目代码 + 会计准则依据', expert: 'finance.finance_accountant', profitImpact: { dimension: 'cost_saving', amount: '凭证生成 2h→3min' } },
    { id: 'bank_reconcile', label: '银行对账', icon: '🏦', prompt: '本月银行流水和账面有差异，帮我对账', expectedOutcome: '银行余额调节表 + 未达账项清单 + 差异原因分析', workflowId: 'bank_feed_reconcile', profitImpact: { dimension: 'cost_saving', amount: '银行对账从 2 小时缩短到 5 分钟' } },
    { id: 'recurring_setup', label: '设置定期凭证', icon: '🔄', prompt: '帮我设置每月自动生成房租凭证', expectedOutcome: '定期凭证模板（含科目/金额/周期）+ 下次执行时间', expert: 'finance.finance_accountant', profitImpact: { dimension: 'cost_saving', amount: '每月省 2-5 小时重复录入' } },
    { id: 'new_client_setup', label: '新客户建账', icon: '📑', prompt: '新接了一个商贸公司客户，帮我建账', expectedOutcome: '行业科目表 + 辅助核算设置 + 建账清单', workflowId: 'coa_setup', profitImpact: { dimension: 'cost_saving', amount: '新客户建账从半天缩短到 3 分钟' } },
    { id: 'client_profit', label: '客户利润分析', icon: '📈', prompt: '分析一下我服务的客户哪些赚钱哪些亏钱', expectedOutcome: '客户利润排行榜 + 高/低价值客户清单 + 经营建议', expert: 'finance.finance_accountant', profitImpact: { dimension: 'revenue', amount: '识别亏损客户调整定价，月增收 1-5 万' } },
    { id: 'audit_plan_new', label: '新审计项目计划', icon: '📋', prompt: '新接一个制造业公司年度审计，帮我制定审计计划', expectedOutcome: '审计计划书（范围+时间+重点领域+重要性水平+人员）', expert: 'finance.finance_accountant', profitImpact: { dimension: 'cost_saving', amount: '审计计划编制从 2 天到 1 小时' } },
    { id: 'materiality_determine', label: '重要性水平计算', icon: '📐', prompt: '被审计单位税前利润 800 万，如何确定重要性水平？', expectedOutcome: '三级重要性（整体/执行/微小）+ 基准选择依据 + 计算底稿', expert: 'finance.finance_accountant', profitImpact: { dimension: 'cost_saving', amount: '3 分钟完成重要性计算' } },
    { id: 'fraud_detect', label: '舞弊风险排查', icon: '🔎', prompt: '日记账有大量月末手工调整分录，请分析舞弊风险', expectedOutcome: '舞弊风险矩阵 + 异常交易明细 + 深入调查建议', expert: 'finance.finance_accountant', profitImpact: { dimension: 'loss_avoidance', amount: '发现舞弊线索避免 50-500 万损失' } },
    { id: 'confirmation_plan', label: '函证方案设计', icon: '📮', prompt: '应收账款余额 5000 万，如何设计函证方案？', expectedOutcome: '函证范围 + 样本选择 + 积极/消极式选择 + 替代程序', expert: 'finance.finance_accountant', profitImpact: { dimension: 'cost_saving', amount: '函证准备从 1 周到 2 小时' } },
    { id: 'sampling_method', label: '抽样方法选择', icon: '🎲', prompt: '测试销售收入完整性，用什么抽样方法？样本量多少？', expectedOutcome: '推荐方法 + 样本量计算 + 选样明细', expert: 'finance.finance_accountant', profitImpact: { dimension: 'cost_saving', amount: '抽样设计从 2 小时到 10 分钟' } },
    { id: 'audit_report_type', label: '审计意见类型', icon: '📄', prompt: '累计未更正错报超过重要性但未遍及，出什么类型报告？', expectedOutcome: '意见类型判定 + 审计准则引用 + 意见段措辞', expert: 'finance.finance_accountant', profitImpact: { dimension: 'loss_avoidance', amount: '意见类型判定准确避免执业风险' } },
    { id: 'internal_control', label: '内控评价', icon: '🏛️', prompt: '被审计单位采购审批全靠口头，如何评估内控风险？', expectedOutcome: '内控缺陷评级 + 控制测试方案 + 实质性程序调整', expert: 'finance.finance_accountant', profitImpact: { dimension: 'loss_avoidance', amount: '内控薄弱需扩大实质性程序范围' } },
  ],
}

export default financeTaxServiceSolution
