/**
 * 自动拆分自 solution-registry-data.ts。
 * 请勿手工编辑“结构”——如需改方案内容，请直接改本文件字段即可。
 */
import type { SolutionConfig } from '../solution-router'
import { agent } from '../solution-router-agent'

export const hkFinanceTaxSolution: SolutionConfig = {
  id: 'hk-finance-tax',
  name: '香港財稅專業服務',
  icon: '🏦',
  color: '#3b82f6',
  tagline: '香港會計師事務所的 AI 專家團隊 — 稅務先行、跨境制勝',
  description:
    '首個覆蓋香港三套 HKFRS 準則 + 轉移定價 + 全球最低稅的 AI 方案。' +
    '以 Finance Agent + Legal Agent 為基礎，注入香港 IRO / AFRC / OECD 知識庫，' +
    '讓每位會計師服務 3 倍客戶，年創收翻倍。' +
    '燈塔客戶：Cheng & Cheng Limited（PrimeGlobal 亞太區主席，140+ 國家網絡）。',
  entrepreneurPurpose: '讓每位會計師服務 3 倍客戶，年創收翻倍，無需增加人手',
  profitMetrics: [
    '利得稅計算表 4h→25min，每月多服務 15-20 新客戶',
    '銀行月結單整理 3天→3分鐘，稅務調查不再熬夜',
    '轉移定價本地文件 5天→1天，一個稅務合夥人年省 60 工作日',
    'AML 客戶盡調 3h→10min，降低 AMLO 違規罰款風險',
  ],
  valueEquivalent: { humanHours: 40, mbeMinutes: 180, acceleration: '800x' },
  agents: [
    agent('finance', 8002, '香港稅務顧問', '利得稅申報、轉移定價、FSIE豁免、暫繳稅計算'),
    agent('finance', 8002, '香港審計專家', 'HKFRS/HKPBE/HKSMEFRS三準則、AFRC質檢、審計底稿'),
    agent('legal', 8003, '香港法律顧問', '公司法(Cap.622)、僱傭條例(Cap.57)、合同法、私隱條例、商業糾紛'),
  ],
  localScripts: ['calc_hk_profits_tax', 'calc_hk_stamp_duty'],
  knowledgeCache: ['hk_tax_law', 'hk_transfer_pricing', 'hk_aml_kyc'],
  theme: { primary: '217 91% 60%', accent: '217 91% 60%', sidebarBg: '220 20% 7%' },
  enabledTabs: ['today', 'tax-filing', 'reports', 'tools', 'documents', 'chat', 'knowledge-graph'],
  tools: [
    {
      id: 'hk-profits-tax',
      type: 'calculator',
      name: '利得稅快速估算',
      icon: '🧮',
      agent: 'finance',
      apiPath: '/api/finance/hk/profits-tax/quick-estimate',
      description: '香港利得稅快速估算（兩級稅率 8.25%/16.5%，30 秒出結果）',
      fields: [
        { key: 'company_name', label: '公司名稱', type: 'text', required: true },
        { key: 'period', label: '財政年度', type: 'text', required: true, default: '2024/25' },
        { key: 'accounting_profit', label: '帳面稅前利潤（HKD）', type: 'currency', required: true },
        {
          key: 'entity_type',
          label: '實體類型',
          type: 'select',
          required: true,
          options: [
            { value: 'corporation', label: '有限公司（8.25%/16.5%）' },
            { value: 'partnership', label: '合夥/獨資（7.5%/15%）' },
          ],
        },
        {
          key: 'connected_persons_group',
          label: '集團已有成員享受優惠稅率',
          type: 'select',
          default: 'false',
          options: [
            { value: 'false', label: '否（可享兩級稅率）' },
            { value: 'true', label: '是（按標準稅率計算）' },
          ],
        },
      ],
    },
    {
      id: 'hk-bank-stmt',
      type: 'document-ai',
      name: '銀行月結單解析',
      icon: '🏦',
      agent: 'finance',
      apiPath: '/api/finance/hk/bank-stmt/parse-csv',
      description: '自動識別 22 家港銀品牌，提取交易記錄，標記可疑交易（傳統 3 天 → 3 分鐘）',
      acceptTypes: ['.csv', '.xlsx', '.txt'],
    },
    {
      id: 'hk-aml-screen',
      type: 'calculator',
      name: 'AML 客戶快速篩查',
      icon: '🛡️',
      agent: 'legal',
      apiPath: '/api/finance/hk/aml/screen',
      description: 'UN/OFAC/EU/HK 制裁名單 + PEP 評估 + 司法管轄區風險（AMLO Cap.615）',
      fields: [
        { key: 'entity_name', label: '客戶姓名/公司名稱', type: 'text', required: true },
        {
          key: 'entity_type',
          label: '客戶類型',
          type: 'select',
          required: true,
          options: [
            { value: 'company', label: '公司/機構' },
            { value: 'individual', label: '個人' },
            { value: 'trust', label: '信托' },
          ],
        },
        { key: 'jurisdiction', label: '司法管轄區（ISO代碼）', type: 'text', required: true, default: 'HK' },
        { key: 'business_nature', label: '業務性質（可選）', type: 'text' },
        { key: 'incorporation_jurisdiction', label: '成立地（如 VG=BVI, KY=開曼）', type: 'text' },
      ],
    },
    {
      id: 'hk-tp-alp',
      type: 'document-ai',
      name: 'TP 可比性分析（CSV）',
      icon: '📊',
      agent: 'finance',
      apiPath: '/api/finance/tp/analyze-csv',
      description: '上傳 Orbis/手動可比公司 CSV → IQR 四分位計算 → ALP 符合性驗證',
      acceptTypes: ['.csv', '.xlsx'],
    },
  ],
  workflows: [
    {
      id: 'hk_profits_tax_return',
      name: '利得稅申報全流程',
      icon: '🧮',
      description: '收集財務數據 → 稅務調整 → 計算兩級稅率 → 生成 BIR51/BIR52 草稿 → 離岸豁免初步評估',
      mode: 'sequential' as const,
      deliverable: 'BIR51/BIR52 利得稅計算表草稿 + 離岸豁免評估意見',
      successCriteria: [
        '稅務調整項目含 IRO 條款依據',
        '兩級稅率計算正確（首 HKD 200 萬 @ 8.25%）',
        '暫繳稅金額按 75% 計算',
      ],
      steps: [
        {
          id: 'collect_data', agent: 'finance', expert: 'hk_tax_advisor',
          label: '財務數據收集與科目映射',
          goal: '整理全年收支並按稅務科目分類',
          successCriteria: ['收入分類（應稅/免稅/離岸）', '不可扣除支出識別', '折舊免稅額資產清單'],
          profitImpact: { dimension: 'cost_saving', amount: '數據整理從 2 小時到 10 分鐘' },
        },
        {
          id: 'tax_calc', agent: 'finance', expert: 'hk_tax_advisor',
          label: '應評稅利潤及稅款計算',
          goal: '輸出完整的稅款計算表',
          successCriteria: ['加回/扣除含法規依據', '折舊免稅額按 Class A/B/C 計算', '暫繳稅正確計算'],
          profitImpact: { dimension: 'cost_saving', amount: '計算從 4 小時到 25 分鐘' },
        },
        {
          id: 'bir_draft', agent: 'finance', expert: 'hk_tax_advisor',
          label: 'BIR51/BIR52 草稿及離岸評估',
          goal: '生成可提交的申報表草稿和離岸豁免意見',
          successCriteria: ['BIR 各行填報數字與計算表一致', '離岸風險提示涵蓋 TP 交叉風險'],
          profitImpact: { dimension: 'cost_saving', amount: '申報準備從半天到 15 分鐘' },
        },
      ],
      triggerPhrases: ['利得稅', 'profits tax', 'BIR51', 'BIR52', '年度申報'],
    },
    {
      id: 'hk_bank_stmt_ocr',
      name: '銀行月結單整理',
      icon: '🏦',
      description: '上傳 22 家港銀月結單 → 自動解析 → 可疑交易標記 → 賬簿交叉核對',
      mode: 'sequential' as const,
      deliverable: '結構化交易記錄 + 可疑交易清單 + 稅務調查準備報告',
      successCriteria: [
        '識別銀行品牌（22 家覆蓋）',
        '提取所有交易記錄（日期/金額/描述）',
        '大額及可疑交易自動標記',
      ],
      steps: [
        {
          id: 'parse', agent: 'finance', expert: 'hk_tax_advisor',
          label: '月結單自動解析',
          goal: '提取全部交易記錄並識別銀行品牌',
          successCriteria: ['正確識別銀行', '提取所有交易', '可疑交易標記'],
          profitImpact: { dimension: 'cost_saving', amount: '整理從 3 天到 3 分鐘' },
        },
        {
          id: 'cross_check', agent: 'finance', expert: 'hk_tax_advisor',
          label: '賬簿交叉核對 & 調查準備',
          goal: '識別未入賬收入和個人/公司賬戶混用',
          successCriteria: ['未入賬收入清單', '異常交易說明', '稅務調查問答建議'],
          profitImpact: { dimension: 'loss_avoidance', amount: '稅務調查應對有據可查' },
        },
      ],
      triggerPhrases: ['月結單', 'bank statement', '銀行流水', '稅務調查'],
    },
    {
      id: 'hk_aml_screening',
      name: 'AML 客戶盡調',
      icon: '🛡️',
      description: '制裁名單篩查 + PEP 評估 + 司法管轄區風險 → AMLO Cap.615 格式 CDD 報告',
      mode: 'sequential' as const,
      deliverable: 'CDD 報告（符合 AMLO Cap.615 第 IV 部格式）+ 開戶決定建議',
      successCriteria: [
        '覆蓋 UN/OFAC/EU/HK 四大制裁名單',
        'PEP 評估含直系及關聯 PEP',
        '風險評級含評級理由和後續行動',
      ],
      steps: [
        {
          id: 'screen', agent: 'legal', expert: 'civil_lawyer',
          label: '多層制裁及 PEP 篩查',
          goal: '完成 L1-L3 三層篩查，識別所有風險標誌',
          successCriteria: ['制裁名單狀態明確', 'PEP 判定含信息來源', '司法管轄區 FATF 評估'],
          profitImpact: { dimension: 'loss_avoidance', amount: '盡調從 3 小時到 10 分鐘' },
        },
        {
          id: 'cdd_report', agent: 'legal', expert: 'civil_lawyer',
          label: 'CDD 報告生成及開戶決定',
          goal: '輸出合規 CDD 報告和開戶建議',
          successCriteria: ['報告符合 AMLO S12-S21', '開戶決定含風險依據', '後續行動清單明確'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免 AMLO 違規罰款最高 HKD 100 萬' },
        },
      ],
      triggerPhrases: ['AML', 'KYC', '盡職調查', 'CDD', '制裁名單', 'PEP'],
    },
    {
      id: 'tp_comparable_analysis',
      name: 'TP 可比性分析',
      icon: '📊',
      description: '自動搜索可比公司（yfinance）+ CSV 上傳（Orbis） → IQR → ALP 驗證 → PDF 報告',
      mode: 'parallel' as const,
      deliverable: 'OECD Annex II 格式 ALP 符合性報告（含 IQR 計算、WCA 調整）',
      successCriteria: [
        '可比公司 ≥ 5 家，含行業篩選說明',
        'IQR 區間計算（P25/P50/P75）',
        'ALP 合規結論含 IRO S50AAB 依據',
      ],
      steps: [
        {
          id: 'search', agent: 'finance', expert: 'hk_tax_advisor',
          label: '可比公司搜索',
          goal: '建立最終可比公司池',
          successCriteria: ['行業 SIC 代碼正確', '可比公司 ≥ 5 家', '異常值已剔除'],
          profitImpact: { dimension: 'cost_saving', amount: '可比搜索從 1 天到 30 分鐘' },
        },
        {
          id: 'alp_report', agent: 'finance', expert: 'hk_tax_advisor',
          label: 'IQR 計算及 ALP 結論',
          goal: '計算四分位區間並判定 ALP 合規性',
          successCriteria: ['IQR 方法符合 OECD §3.57-3.62', 'WCA 調整計算正確', '風險評級明確'],
          profitImpact: { dimension: 'loss_avoidance', amount: 'TP 文件充分降低 IRD 調整風險' },
        },
      ],
      triggerPhrases: ['轉移定價', 'transfer pricing', 'ALP', 'IQR', '可比性分析'],
    },
    {
      id: 'bank_rec_investigation',
      name: '銀行月結單異常核查',
      icon: '🔍',
      description: 'OCR 解析月結單 → 賬簿核對 → 異常交易分析 → 稅務調查問詢清單生成',
      mode: 'sequential' as const,
      deliverable: '未對賬項分類清單 + 異常交易報告 + IRD 問詢回覆模板',
      successCriteria: [
        '未對賬項按時差/錯誤/可疑分類',
        '異常模式識別（結構化交易/循環資金/現金異常）',
        'IRD 問詢回覆框架完整',
      ],
      steps: [
        {
          id: 'ocr_parse', agent: 'finance', expert: 'hk_tax_advisor',
          label: '月結單 OCR 解析與賬簿匹配',
          goal: '完成銀行數據與賬簿的自動匹配',
          successCriteria: ['精確匹配率 > 90%', '未匹配項全部識別', '重複記錄檢測'],
          profitImpact: { dimension: 'cost_saving', amount: '核查從 2 小時到 20 分鐘' },
        },
        {
          id: 'anomaly_analysis', agent: 'finance', expert: 'hk_tax_advisor',
          label: '異常模式分析與問詢清單',
          goal: '輸出異常交易清單和 IRD 應對模板',
          successCriteria: ['異常按嚴重程度評級', 'IRD 問詢框架覆蓋所有異常點'],
          profitImpact: { dimension: 'loss_avoidance', amount: '稅務調查有備無患' },
        },
      ],
      triggerPhrases: ['銀行核查', '月結單異常', '稅務調查', 'bank reconciliation', '未入賬'],
    },
    {
      id: 'offshore_exemption_claim',
      name: '離岸豁免申請文件',
      icon: '🌏',
      description: '業務來源地分析（source of profits test）→ 支持文件清單 → Advance Ruling 申請函起草',
      mode: 'sequential' as const,
      deliverable: '離岸豁免可行性報告 + Advance Ruling 申請函草稿 + IRD 問卷回覆模板',
      successCriteria: [
        '業務來源地分析引用相關案例法（HK-TVB/ING Baring）',
        'Advance Ruling 申請格式符合 IRO S88A',
        '支持文件清單按合同/業務/財務三類分類',
      ],
      steps: [
        {
          id: 'source_analysis', agent: 'finance', expert: 'hk_tax_advisor',
          label: '業務來源地分析',
          goal: '評估利潤是否可申請離岸豁免',
          successCriteria: ['引用 DIPN 21/39 指引', '可行性評估（強/中/弱）', '主要法律依據明確'],
          profitImpact: { dimension: 'revenue', amount: '離岸利潤合法豁免，稅率從 16.5% 降至 0%' },
        },
        {
          id: 'ruling_draft', agent: 'legal', expert: 'civil_lawyer',
          label: 'Advance Ruling 申請函及 IRD 問卷',
          goal: '輸出可提交的申請函和問卷回覆框架',
          successCriteria: ['申請函格式符合 IRO S88A', '論據引用案例法', '文件清單完整'],
          profitImpact: { dimension: 'cost_saving', amount: '申請準備從 2 天到 3 小時' },
        },
      ],
      triggerPhrases: ['離岸豁免', 'offshore exemption', '源自香港', 'source of profits', 'Advance Ruling'],
    },
    {
      id: 'transfer_pricing_doc',
      name: '轉移定價本地文件',
      icon: '📋',
      description: '關聯交易識別 → FAR 功能分析 → 定價方法選擇 → OECD BEPS Action 13 格式本地文件生成',
      mode: 'sequential' as const,
      deliverable: '符合 IRO S50AAB + OECD Annex II 格式的完整本地文件（英文正文 + 中文摘要）',
      successCriteria: [
        '關聯方交易按類型分類（貨物/服務/IP/財務）',
        'FAR 分析雙方對比表完整',
        '定價方法選擇含充分論據',
        'ALP 符合性結論有數據支持',
      ],
      steps: [
        {
          id: 'far_analysis', agent: 'finance', expert: 'hk_tax_advisor',
          label: '關聯交易識別與 FAR 分析',
          goal: '建立受控交易清單並完成功能風險分析',
          successCriteria: ['觸發門檻評估（HKD 2.2 億/1.1 億）', 'FAR 雙方對比完整', '測試方識別正確'],
          profitImpact: { dimension: 'cost_saving', amount: 'FAR 分析從 2 天到 4 小時' },
        },
        {
          id: 'local_file_draft', agent: 'finance', expert: 'hk_tax_advisor',
          label: '定價方法選擇與本地文件起草',
          goal: '輸出符合 OECD Annex II 格式的完整本地文件',
          successCriteria: ['定價方法含論據', 'ALP 結論有數據', '文件格式符合 IRO S50AAB'],
          profitImpact: { dimension: 'cost_saving', amount: 'TP 文件從 5 天到 1 天' },
        },
      ],
      triggerPhrases: ['轉移定價文件', 'TP local file', '本地文件', 'BEPS Action 13', 'IRO S50AAB'],
    },
    {
      id: 'hk_global_minimum_tax_readiness',
      name: '全球最低稅（Pillar Two）評估',
      icon: '🌐',
      description: '門檻判斷（€7.5 億）→ ETR 計算 → 補足稅估算 → 香港 QDMTT 申報準備 → 應對策略',
      mode: 'sequential' as const,
      deliverable: 'Pillar Two 影響評估報告 + QDMTT 申報準備清單 + 90 天行動計劃',
      successCriteria: [
        '觸發門檻分析含過去 4 年收入數據',
        '各司法管轄區 ETR 計算（含香港 16.5%）',
        '補足稅估算含 SBIE 豁免計算',
        'QDMTT 申報截止日期明確',
      ],
      steps: [
        {
          id: 'threshold_etr', agent: 'finance', expert: 'hk_tax_advisor',
          label: '門檻分析與 ETR 計算',
          goal: '確認是否觸發 Pillar Two 並計算各地有效稅率',
          successCriteria: ['門檻判斷含 4 年收入', 'ETR 公式正確（調整後稅款/GloBE 利潤）', '安全港適用性評估'],
          profitImpact: { dimension: 'loss_avoidance', amount: '提前規劃避免 Pillar Two 合規罰款' },
        },
        {
          id: 'qdmtt_strategy', agent: 'finance', expert: 'hk_tax_advisor',
          label: '補足稅計算與應對方案',
          goal: '輸出補足稅金額和 QDMTT 合規計劃',
          successCriteria: ['補足稅含 SBIE 計算', 'QDMTT 數據要求清單完整', '應對策略含 SBIE 優化建議'],
          profitImpact: { dimension: 'cost_saving', amount: 'Pillar Two 分析從 2 週到 4 小時' },
        },
      ],
      triggerPhrases: ['全球最低稅', 'Pillar Two', 'QDMTT', 'GloBE', '15%', '€7.5億', 'IIR', 'UTPR'],
    },
    {
      id: 'audit_report_generation',
      name: '審計報告生成（三套準則）',
      icon: '📄',
      description: '實體分類 → 適用準則確認（HKFRS/HKPBE/HKSMEFRS）→ KAM 起草 → HKSA 700 系列報告生成',
      mode: 'sequential' as const,
      deliverable: '符合 HKSA 700 系列的獨立核數師報告草稿 + KAM 段落（PIE 適用）',
      successCriteria: [
        '準則選擇正確（HKFRS/HKPBE/HKSMEFRS）',
        '重要性水平計算有文件支持',
        'KAM 段落包含事項識別依據和審計程序概述',
        '報告格式符合最新 HKSA 700（修訂）',
      ],
      steps: [
        {
          id: 'standards_and_materiality', agent: 'finance', expert: 'hk_audit_specialist',
          label: '準則確認與重要性水平計算',
          goal: '確定適用準則和整體重要性水平',
          successCriteria: ['PIE 判斷正確', '重要性水平計算含依據', '科目映射核對完整'],
          profitImpact: { dimension: 'cost_saving', amount: '準備工作從 2 小時到 15 分鐘' },
        },
        {
          id: 'kam_and_report', agent: 'finance', expert: 'hk_audit_specialist',
          label: 'KAM 識別與審計報告生成',
          goal: '輸出完整審計報告草稿',
          successCriteria: ['KAM 含識別依據和審計應對', '報告格式符合 HKSA 700', '意見類型選擇正確'],
          profitImpact: { dimension: 'cost_saving', amount: '審計報告從 8 小時到 1 小時' },
        },
      ],
      triggerPhrases: ['審計報告', 'audit report', 'HKFRS', 'HKPBE', 'HKSMEFRS', 'KAM', 'HKSA 700'],
    },
    {
      id: 'aml_client_due_diligence',
      name: 'AML/KYC 客戶盡職調查',
      icon: '🔎',
      description: '並行核查身份/制裁/PEP/業務背景 → 風險評級 → CDD 報告（AMLO Cap.615 第 IV 部）',
      mode: 'parallel' as const,
      deliverable: '正式 CDD 報告 + 風險評級（Low/Medium/High）+ EDD 措施清單（高風險時）',
      successCriteria: [
        'UBO 識別（直接/間接持股 ≥25%）',
        '制裁名單覆蓋 UN/OFAC/EU/HKMA',
        'PEP 含直系及密切關聯人評估',
        'CDD 等級（SDD/標準/EDD）建議合理',
      ],
      steps: [
        {
          id: 'identity_sanctions', agent: 'finance', expert: 'hk_tax_advisor',
          label: '身份核查與制裁/PEP 篩查（並行）',
          goal: '完成 L1-L3 篩查並核實客戶身份',
          successCriteria: ['身份文件清單完整', '制裁/PEP 無漏查', 'UBO 穿透識別'],
          profitImpact: { dimension: 'cost_saving', amount: '盡調從 3 小時到 30 分鐘' },
        },
        {
          id: 'risk_cdd', agent: 'legal', expert: 'civil_lawyer',
          label: '綜合風險評級與 CDD 報告',
          goal: '輸出正式 CDD 報告和入冊建議',
          successCriteria: ['風險評級含 AMLO Sch.2 因素', 'CDD 報告符合第 IV 部格式', 'EDD 措施清單明確'],
          profitImpact: { dimension: 'loss_avoidance', amount: '全面盡調降低 MLRO 合規風險' },
        },
      ],
      triggerPhrases: ['客戶盡調', 'client due diligence', 'CDD', 'KYC 盡調', 'AMLO', 'MLRO', 'UBO 識別'],
    },
    {
      id: 'afrc_quality_review',
      name: 'AFRC 質量管理評分準備',
      icon: '📊',
      description: 'HKSQM 1（事務所）+ HKSQM 2（業務）差距分析 → 改進行動清單 → 90 天 SOP 提升計劃',
      mode: 'parallel' as const,
      deliverable: 'AFRC 差距分析報告 + P0/P1/P2 改進清單 + 90 天行動計劃',
      successCriteria: [
        'HKSQM 1 六大組成部分逐項評估',
        'HKSQM 2 業務層面樣本核查',
        'Critical Gaps 全部識別',
        'SOP 起草建議覆蓋高頻缺失點',
      ],
      steps: [
        {
          id: 'hksqm_assessment', agent: 'finance', expert: 'hk_audit_specialist',
          label: 'HKSQM 1+2 並行評估',
          goal: '完成事務所和業務層面的質量管理差距識別',
          successCriteria: ['每個組成部分評分（Strong/Adequate/Needs Improvement/Critical）', '底稿完整性抽查結果'],
          profitImpact: { dimension: 'loss_avoidance', amount: 'AFRC 評分等級提升，降低監管風險' },
        },
        {
          id: 'action_plan', agent: 'finance', expert: 'hk_audit_specialist',
          label: '差距清單與 SOP 起草',
          goal: '輸出 90 天可執行改進計劃',
          successCriteria: ['P0 問題必須在 AFRC 審查前解決', 'SOP 模板覆蓋高頻缺失點'],
          profitImpact: { dimension: 'loss_avoidance', amount: '提前準備，從容應對 AFRC 檢查' },
        },
      ],
      triggerPhrases: ['AFRC', '質量管理', 'HKSQM', 'EQR', '審計質量', '質量複核'],
    },
    {
      id: 'hk_ipo_preparation',
      name: '港股 IPO 上市準備',
      icon: '📈',
      description: '港交所主板/GEM 條件適配 → 財務報告準備 → 架構稅務分析 → IPO 盡調清單生成',
      mode: 'sequential' as const,
      deliverable: 'IPO 適配評估報告 + 財務數據差距清單 + 盡調清單 + 保薦人溝通材料',
      successCriteria: [
        '三項上市測試（盈利/市值收入現金流/市值收入）明確評估',
        '財務報告準則差異分析（CAS vs HKFRS）',
        '架構稅務分析含預提稅效率',
        '盡調清單覆蓋財務/法律/業務三維',
      ],
      steps: [
        {
          id: 'listing_conditions', agent: 'finance', expert: 'hk_tax_advisor',
          label: '上市條件評估與財務準備',
          goal: '確認最優上市測試路徑並識別財務數據缺口',
          successCriteria: ['三項測試對比分析', 'CAS→HKFRS 主要差異識別', '招股書財務數據框架'],
          profitImpact: { dimension: 'revenue', amount: 'IPO 籌備從 20 工作日到 8 小時（評估階段）' },
        },
        {
          id: 'structure_and_dd', agent: 'legal', expert: 'hk_legal_advisor',
          label: '架構稅務分析與盡調清單',
          goal: '輸出最優上市架構建議和完整盡調清單',
          successCriteria: ['架構對比（直接/紅籌/H股）含稅務效率', '盡調清單三維分類'],
          profitImpact: { dimension: 'cost_saving', amount: '盡調準備提效，減少後期補充成本' },
        },
      ],
      triggerPhrases: ['港股IPO', '港交所上市', '主板上市', 'GEM', '招股書', '盈利測試', '現金流測試'],
    },
    {
      id: 'dual_listing_coordination',
      name: 'A+H 兩地上市協調',
      icon: '🔗',
      description: 'CAS→HKFRS 財務轉換 → 兩地披露合規對齊 → 跨境稅務架構 → 紅籌/VIE 合規評估',
      mode: 'sequential' as const,
      deliverable: 'A+H 兩地上市協調報告 + 財務差異調整清單 + 跨境稅務規劃建議 + VIE 合規評估',
      successCriteria: [
        'CAS vs HKFRS 六大差異領域逐項分析',
        'CSRC + SFC 雙重披露要求對照表',
        '預提稅規劃含實益擁有人認定要求',
        'VIE/紅籌架構合規評估',
      ],
      steps: [
        {
          id: 'financial_reconciliation', agent: 'finance', expert: 'hk_audit_specialist',
          label: 'CAS→HKFRS 差異調整與披露對齊',
          goal: '識別兩地財務報表差異並制定時間線',
          successCriteria: ['六大差異領域（收入/租賃/金融工具/政府補助/投資性房地產/遞延稅）', '兩地披露要求對照'],
          profitImpact: { dimension: 'cost_saving', amount: '兩地協調從 30 工作日到 12 小時（分析階段）' },
        },
        {
          id: 'tax_and_structure', agent: 'finance', expert: 'hk_tax_advisor',
          label: '跨境稅務與架構合規評估',
          goal: '輸出最優稅務架構和 VIE 合規評估',
          successCriteria: ['H股股息預提稅計算含協定優惠', 'VIE 合規風險評估', 'CSRC 境外上市備案清單'],
          profitImpact: { dimension: 'revenue', amount: '稅務規劃優化兩地上市後的股息效率' },
        },
      ],
      triggerPhrases: ['A+H', '兩地上市', 'H股', '紅籌', 'VIE', 'CAS轉HKFRS', '雙重上市', 'CSRC境外備案'],
    },
  ],
  scenarios: [
    {
      id: 'profits_tax_calc',
      label: '利得稅估算',
      icon: '🧮',
      prompt: '我的香港有限公司 2024/25 年度帳面利潤 HKD 500 萬，請計算應繳利得稅及暫繳稅',
      expectedOutcome: '兩級稅率計算表 + 應繳稅款 + 暫繳稅 + BIR51 草稿',
      expert: 'finance.hk_tax_advisor',
      profitImpact: { dimension: 'cost_saving', amount: '稅務計算從 4 小時到 25 分鐘' },
    },
    {
      id: 'offshore_check',
      label: '離岸豁免初步評估',
      icon: '🌏',
      prompt: '我公司是香港貿易公司，採購在深圳談判，香港開發票，是否可以申請離岸豁免？',
      expectedOutcome: '來源地分析 + 離岸豁免可行性 + 所需文件 + TP 交叉風險提示',
      expert: 'finance.hk_tax_advisor',
      profitImpact: { dimension: 'revenue', amount: '離岸利潤合法豁免，稅率從 16.5% 降至 0%' },
    },
    {
      id: 'bank_stmt_upload',
      label: '月結單整理（稅務調查)',
      icon: '🏦',
      prompt: '請整理這份 HSBC 月結單，識別可能需要向稅務局解釋的交易',
      expectedOutcome: '結構化交易列表 + 可疑交易標記 + 賬簿核對建議',
      workflowId: 'hk_bank_stmt_ocr',
      profitImpact: { dimension: 'cost_saving', amount: '月結單整理 3 天 → 3 分鐘' },
    },
    {
      id: 'aml_screen',
      label: 'AML 客戶篩查',
      icon: '🛡️',
      prompt: '請對這家 BVI 公司「XYZ Global Trade Limited」進行 AML 背景篩查',
      expectedOutcome: '制裁名單狀態 + PEP 評估 + 風險評級 + CDD 報告',
      workflowId: 'hk_aml_screening',
      profitImpact: { dimension: 'loss_avoidance', amount: '避免 AMLO 違規罰款（最高 HKD 100 萬）' },
    },
    {
      id: 'tp_alp_check',
      label: 'TP 定價合規性',
      icon: '📊',
      prompt: 'ABC Trading 向關聯方收取服務費，利潤率 2.5%，是否符合獨立交易原則？',
      expectedOutcome: 'ALP 區間 + IQR 統計 + 風險評級 + 建議措施',
      workflowId: 'tp_comparable_analysis',
      profitImpact: { dimension: 'loss_avoidance', amount: 'TP 風險預防：避免 IRD 調整補稅+罰款' },
    },
  ],
  slashCommands: [
    { cmd: '/利得稅', label: '利得稅估算', icon: '🧮', toolId: 'hk-profits-tax' },
    { cmd: '/月結單', label: '銀行月結單解析', icon: '🏦', toolId: 'hk-bank-stmt' },
    { cmd: '/AML', label: 'AML 客戶快速篩查', icon: '🛡️', toolId: 'hk-aml-screen' },
    { cmd: '/TP', label: 'TP 可比性分析', icon: '📊', toolId: 'hk-tp-alp' },
    { cmd: '/離岸', label: '離岸豁免評估', icon: '🌏', description: '啟動離岸豁免申請全流程' },
    { cmd: '/轉移定價', label: '轉移定價文件', icon: '📋', description: '生成 TP 本地文件草稿' },
  ],
  status: 'available',
}

export default hkFinanceTaxSolution
