/**
 * 自动拆分自 solution-registry-data.ts。
 * 请勿手工编辑“结构”——如需改方案内容，请直接改本文件字段即可。
 */
import type { SolutionConfig } from '../solution-router'
import { agent } from '../solution-router-agent'

export const hkFinanceTaxSolution: SolutionConfig = {
  id: 'hk-finance-tax',
  name: '香港財稅專業服務',
  icon: '🏦',
  color: '#3b82f6',
  tagline: '香港會計師事務所的 AI 專家團隊 — 稅務先行、跨境制勝',
  description:
    '首個覆蓋香港三套 HKFRS 準則 + 轉移定價 + 全球最低稅的 AI 方案。' +
    '以 Finance Agent + Legal Agent 為基礎，注入香港 IRO / AFRC / OECD 知識庫，' +
    '讓每位會計師服務 3 倍客戶，年創收翻倍。' +
    '燈塔客戶：Cheng & Cheng Limited（PrimeGlobal 亞太區主席，140+ 國家網絡）。',
  entrepreneurPurpose: '讓每位會計師服務 3 倍客戶，年創收翻倍，無需增加人手',
  profitMetrics: [
    '利得稅計算表 4h→25min，每月多服務 15-20 新客戶',
    '銀行月結單整理 3天→3分鐘，稅務調查不再熬夜',
    '轉移定價本地文件 5天→1天，一個稅務合夥人年省 60 工作日',
    'AML 客戶盡調 3h→10min，降低 AMLO 違規罰款風險',
  ],
  valueEquivalent: { humanHours: 40, mbeMinutes: 180, acceleration: '800x' },
  agents: [
    agent('finance', 8002, '香港稅務顧問', '利得稅申報、轉移定價、FSIE豁免、暫繳稅計算'),
    agent('finance', 8002, '香港審計專家', 'HKFRS/HKPBE/HKSMEFRS三準則、AFRC質檢、審計底稿'),
    agent('legal', 8003, '香港法律顧問', '公司法(Cap.622)、僱傭條例(Cap.57)、合同法、私隱條例、商業糾紛'),
  ],
  localScripts: ['calc_hk_profits_tax', 'calc_hk_stamp_duty'],
  knowledgeCache: ['hk_tax_law', 'hk_transfer_pricing', 'hk_aml_kyc'],
  theme: { primary: '217 91% 60%', accent: '217 91% 60%', sidebarBg: '220 20% 7%' },
  enabledTabs: ['today', 'tax-filing', 'reports', 'tools', 'documents', 'chat', 'knowledge-graph'],
  tools: [
    {
      id: 'hk-profits-tax',
      type: 'calculator',
      name: '利得稅快速估算',
      icon: '🧮',
      agent: 'finance',
      apiPath: '/api/finance/hk/profits-tax/quick-estimate',
      description: '香港利得稅快速估算（兩級稅率 8.25%/16.5%，30 秒出結果）',
      fields: [
        { key: 'company_name', label: '公司名稱', type: 'text', required: true },
        { key: 'period', label: '財政年度', type: 'text', required: true, default: '2024/25' },
        { key: 'accounting_profit', label: '帳面稅前利潤（HKD）', type: 'currency', required: true },
        {
          key: 'entity_type',
          label: '實體類型',
          type: 'select',
          required: true,
          options: [
            { value: 'corporation', label: '有限公司（8.25%/16.5%）' },
            { value: 'partnership', label: '合夥/獨資（7.5%/15%）' },
          ],
        },
        {
          key: 'connected_persons_group',
          label: '集團已有成員享受優惠稅率',
          type: 'select',
          default: 'false',
          options: [
            { value: 'false', label: '否（可享兩級稅率）' },
            { value: 'true', label: '是（按標準稅率計算）' },
          ],
        },
      ],
    },
    {
      id: 'hk-bank-stmt',
      type: 'document-ai',
      name: '銀行月結單解析',
      icon: '🏦',
      agent: 'finance',
      apiPath: '/api/finance/hk/bank-stmt/parse-csv',
      description: '自動識別 22 家港銀品牌，提取交易記錄，標記可疑交易（傳統 3 天 → 3 分鐘）',
      acceptTypes: ['.csv', '.xlsx', '.txt'],
    },
    {
      id: 'hk-aml-screen',
      type: 'calculator',
      name: 'AML 客戶快速篩查',
      icon: '🛡️',
      agent: 'legal',
      apiPath: '/api/finance/hk/aml/screen',
      description: 'UN/OFAC/EU/HK 制裁名單 + PEP 評估 + 司法管轄區風險（AMLO Cap.615）',
      fields: [
        { key: 'entity_name', label: '客戶姓名/公司名稱', type: 'text', required: true },
        {
          key: 'entity_type',
          label: '客戶類型',
          type: 'select',
          required: true,
          options: [
            { value: 'company', label: '公司/機構' },
            { value: 'individual', label: '個人' },
            { value: 'trust', label: '信托' },
          ],
        },
        { key: 'jurisdiction', label: '司法管轄區（ISO代碼）', type: 'text', required: true, default: 'HK' },
        { key: 'business_nature', label: '業務性質（可選）', type: 'text' },
        { key: 'incorporation_jurisdiction', label: '成立地（如 VG=BVI, KY=開曼）', type: 'text' },
      ],
    },
    {
      id: 'hk-tp-alp',
      type: 'document-ai',
      name: 'TP 可比性分析（CSV）',
      icon: '📊',
      agent: 'finance',
      apiPath: '/api/finance/tp/analyze-csv',
      description: '上傳 Orbis/手動可比公司 CSV → IQR 四分位計算 → ALP 符合性驗證',
      acceptTypes: ['.csv', '.xlsx'],
    },
  ],
  workflows: [
    {
      id: 'hk_profits_tax_return',
      name: '利得稅申報全流程',
      icon: '🧮',
      description: '收集財務數據 → 稅務調整 → 計算兩級稅率 → 生成 BIR51/BIR52 草稿 → 離岸豁免初步評估',
      mode: 'sequential' as const,
      deliverable: 'BIR51/BIR52 利得稅計算表草稿 + 離岸豁免評估意見',
      successCriteria: [
        '稅務調整項目含 IRO 條款依據',
        '兩級稅率計算正確（首 HKD 200 萬 @ 8.25%）',
        '暫繳稅金額按 75% 計算',
      ],
      steps: [
        {
          id: 'collect_data', agent: 'finance', expert: 'hk_tax_advisor',
          label: '財務數據收集與科目映射',
          goal: '整理全年收支並按稅務科目分類',
          successCriteria: ['收入分類（應稅/免稅/離岸）', '不可扣除支出識別', '折舊免稅額資產清單'],
          profitImpact: { dimension: 'cost_saving', amount: '數據整理從 2 小時到 10 分鐘' },
        },
        {
          id: 'tax_calc', agent: 'finance', expert: 'hk_tax_advisor',
          label: '應評稅利潤及稅款計算',
          goal: '輸出完整的稅款計算表',
          successCriteria: ['加回/扣除含法規依據', '折舊免稅額按 Class A/B/C 計算', '暫繳稅正確計算'],
          profitImpact: { dimension: 'cost_saving', amount: '計算從 4 小時到 25 分鐘' },
        },
        {
          id: 'bir_draft', agent: 'finance', expert: 'hk_tax_advisor',
          label: 'BIR51/BIR52 草稿及離岸評估',
          goal: '生成可提交的申報表草稿和離岸豁免意見',
          successCriteria: ['BIR 各行填報數字與計算表一致', '離岸風險提示涵蓋 TP 交叉風險'],
          profitImpact: { dimension: 'cost_saving', amount: '申報準備從半天到 15 分鐘' },
        },
      ],
      triggerPhrases: ['利得稅', 'profits tax', 'BIR51', 'BIR52', '年度申報'],
    },
    {
      id: 'hk_bank_stmt_ocr',
      name: '銀行月結單整理',
      icon: '🏦',
      description: '上傳 22 家港銀月結單 → 自動解析 → 可疑交易標記 → 賬簿交叉核對',
      mode: 'sequential' as const,
      deliverable: '結構化交易記錄 + 可疑交易清單 + 稅務調查準備報告',
      successCriteria: [
        '識別銀行品牌（22 家覆蓋）',
        '提取所有交易記錄（日期/金額/描述）',
        '大額及可疑交易自動標記',
      ],
      steps: [
        {
          id: 'parse', agent: 'finance', expert: 'hk_tax_advisor',
          label: '月結單自動解析',
          goal: '提取全部交易記錄並識別銀行品牌',
          successCriteria: ['正確識別銀行', '提取所有交易', '可疑交易標記'],
          profitImpact: { dimension: 'cost_saving', amount: '整理從 3 天到 3 分鐘' },
        },
        {
          id: 'cross_check', agent: 'finance', expert: 'hk_tax_advisor',
          label: '賬簿交叉核對 & 調查準備',
          goal: '識別未入賬收入和個人/公司賬戶混用',
          successCriteria: ['未入賬收入清單', '異常交易說明', '稅務調查問答建議'],
          profitImpact: { dimension: 'loss_avoidance', amount: '稅務調查應對有據可查' },
        },
      ],
      triggerPhrases: ['月結單', 'bank statement', '銀行流水', '稅務調查'],
    },
    {
      id: 'hk_aml_screening',
      name: 'AML 客戶盡調',
      icon: '🛡️',
      description: '制裁名單篩查 + PEP 評估 + 司法管轄區風險 → AMLO Cap.615 格式 CDD 報告',
      mode: 'sequential' as const,
      deliverable: 'CDD 報告（符合 AMLO Cap.615 第 IV 部格式）+ 開戶決定建議',
      successCriteria: [
        '覆蓋 UN/OFAC/EU/HK 四大制裁名單',
        'PEP 評估含直系及關聯 PEP',
        '風險評級含評級理由和後續行動',
      ],
      steps: [
        {
          id: 'screen', agent: 'legal', expert: 'civil_lawyer',
          label: '多層制裁及 PEP 篩查',
          goal: '完成 L1-L3 三層篩查，識別所有風險標誌',
          successCriteria: ['制裁名單狀態明確', 'PEP 判定含信息來源', '司法管轄區 FATF 評估'],
          profitImpact: { dimension: 'loss_avoidance', amount: '盡調從 3 小時到 10 分鐘' },
        },
        {
          id: 'cdd_report', agent: 'legal', expert: 'civil_lawyer',
          label: 'CDD 報告生成及開戶決定',
          goal: '輸出合規 CDD 報告和開戶建議',
          successCriteria: ['報告符合 AMLO S12-S21', '開戶決定含風險依據', '後續行動清單明確'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免 AMLO 違規罰款最高 HKD 100 萬' },
        },
      ],
      triggerPhrases: ['AML', 'KYC', '盡職調查', 'CDD', '制裁名單', 'PEP'],
    },
    {
      id: 'tp_comparable_analysis',
      name: 'TP 可比性分析',
      icon: '📊',
      description: '自動搜索可比公司（yfinance）+ CSV 上傳（Orbis） → IQR → ALP 驗證 → PDF 報告',
      mode: 'parallel' as const,
      deliverable: 'OECD Annex II 格式 ALP 符合性報告（含 IQR 計算、WCA 調整）',
      successCriteria: [
        '可比公司 ≥ 5 家，含行業篩選說明',
        'IQR 區間計算（P25/P50/P75）',
        'ALP 合規結論含 IRO S50AAB 依據',
      ],
      steps: [
        {
          id: 'search', agent: 'finance', expert: 'hk_tax_advisor',
          label: '可比公司搜索',
          goal: '建立最終可比公司池',
          successCriteria: ['行業 SIC 代碼正確', '可比公司 ≥ 5 家', '異常值已剔除'],
          profitImpact: { dimension: 'cost_saving', amount: '可比搜索從 1 天到 30 分鐘' },
        },
        {
          id: 'alp_report', agent: 'finance', expert: 'hk_tax_advisor',
          label: 'IQR 計算及 ALP 結論',
          goal: '計算四分位區間並判定 ALP 合規性',
          successCriteria: ['IQR 方法符合 OECD §3.57-3.62', 'WCA 調整計算正確', '風險評級明確'],
          profitImpact: { dimension: 'loss_avoidance', amount: 'TP 文件充分降低 IRD 調整風險' },
        },
      ],
      triggerPhrases: ['轉移定價', 'transfer pricing', 'ALP', 'IQR', '可比性分析'],
    },
  ],
  scenarios: [
    {
      id: 'profits_tax_calc',
      label: '利得稅估算',
      icon: '🧮',
      prompt: '我的香港有限公司 2024/25 年度帳面利潤 HKD 500 萬，請計算應繳利得稅及暫繳稅',
      expectedOutcome: '兩級稅率計算表 + 應繳稅款 + 暫繳稅 + BIR51 草稿',
      expert: 'finance.hk_tax_advisor',
      profitImpact: { dimension: 'cost_saving', amount: '稅務計算從 4 小時到 25 分鐘' },
    },
    {
      id: 'offshore_check',
      label: '離岸豁免初步評估',
      icon: '🌏',
      prompt: '我公司是香港貿易公司，採購在深圳談判，香港開發票，是否可以申請離岸豁免？',
      expectedOutcome: '來源地分析 + 離岸豁免可行性 + 所需文件 + TP 交叉風險提示',
      expert: 'finance.hk_tax_advisor',
      profitImpact: { dimension: 'revenue', amount: '離岸利潤合法豁免，稅率從 16.5% 降至 0%' },
    },
    {
      id: 'bank_stmt_upload',
      label: '月結單整理（稅務調查)',
      icon: '🏦',
      prompt: '請整理這份 HSBC 月結單，識別可能需要向稅務局解釋的交易',
      expectedOutcome: '結構化交易列表 + 可疑交易標記 + 賬簿核對建議',
      workflowId: 'hk_bank_stmt_ocr',
      profitImpact: { dimension: 'cost_saving', amount: '月結單整理 3 天 → 3 分鐘' },
    },
    {
      id: 'aml_screen',
      label: 'AML 客戶篩查',
      icon: '🛡️',
      prompt: '請對這家 BVI 公司「XYZ Global Trade Limited」進行 AML 背景篩查',
      expectedOutcome: '制裁名單狀態 + PEP 評估 + 風險評級 + CDD 報告',
      workflowId: 'hk_aml_screening',
      profitImpact: { dimension: 'loss_avoidance', amount: '避免 AMLO 違規罰款（最高 HKD 100 萬）' },
    },
    {
      id: 'tp_alp_check',
      label: 'TP 定價合規性',
      icon: '📊',
      prompt: 'ABC Trading 向關聯方收取服務費，利潤率 2.5%，是否符合獨立交易原則？',
      expectedOutcome: 'ALP 區間 + IQR 統計 + 風險評級 + 建議措施',
      workflowId: 'tp_comparable_analysis',
      profitImpact: { dimension: 'loss_avoidance', amount: 'TP 風險預防：避免 IRD 調整補稅+罰款' },
    },
  ],
  slashCommands: [
    { cmd: '/利得稅', label: '利得稅估算', icon: '🧮', toolId: 'hk-profits-tax' },
    { cmd: '/月結單', label: '銀行月結單解析', icon: '🏦', toolId: 'hk-bank-stmt' },
    { cmd: '/AML', label: 'AML 客戶快速篩查', icon: '🛡️', toolId: 'hk-aml-screen' },
    { cmd: '/TP', label: 'TP 可比性分析', icon: '📊', toolId: 'hk-tp-alp' },
    { cmd: '/離岸', label: '離岸豁免評估', icon: '🌏', description: '啟動離岸豁免申請全流程' },
    { cmd: '/轉移定價', label: '轉移定價文件', icon: '📋', description: '生成 TP 本地文件草稿' },
  ],
  status: 'available',
}

export default hkFinanceTaxSolution
