/**
 * 自动拆分自 solution-registry-data.ts。
 * 请勿手工编辑“结构”——如需改方案内容，请直接改本文件字段即可。
 */
import type { SolutionConfig } from '../solution-router'
import { agent } from '../solution-router-agent'

export const insuranceOperationsSolution: SolutionConfig = {
  id: 'insurance-operations',
  name: '保险公司智能运营方案',
  icon: '🛡️',
  color: '#0891b2',
  tagline: '综合成本率降 3 个点，续保率升 15%，团险签约快一倍',
  description: '总经理最关心三个数字：综合成本率、续保率、新单保费。MBE 七位 AI 专家直接作用于这三个数字。',
  entrepreneurPurpose: '降低综合成本率、提升续保率和新单保费，直接改善承保利润',
  profitMetrics: ['综合成本率降 3 个点', '续保率提升 15%', '团险签约周期缩短一半'],
  valueEquivalent: { humanHours: 8, mbeMinutes: 2, acceleration: '240x' },
  agents: [
    agent('insurance_cs', 8013, '理赔顾问', '报案受理、定损核赔、速赔通道、赔付跟进'),
    agent('insurance_cs', 8013, '车险专家', '交强险/商业险报案、国任速赔、续保报价'),
    agent('insurance_cs', 8013, '保单服务专员', '投保咨询、保单查询、退保计算、保单贷款'),
    agent('insurance_cs', 8013, '合规守卫', '话术审查、销售误导检测、反洗钱、银保监消保'),
    agent('legal', 8003, '保险法务专家', '理赔纠纷、保险合同审查、代位求偿、投诉处理'),
    agent('finance', 8002, '保费财税专家', '保费收入确认、准备金计提、佣金税务处理'),
    agent('sales', 8008, '团险销售顾问', 'B2B团险销售、渠道拓展、商务谈判'),
  ],
  localScripts: ['calc_iit', 'calc_vat', 'calc_litigation_fee'],
  knowledgeCache: ['insurance_product_rates'],
  theme: { primary: '192 91% 37%', accent: '192 91% 37%', sidebarBg: '192 15% 6%' },
  enabledTabs: ['chat', 'tools', 'workflows', 'dashboard', 'knowledge-graph'],
  tools: [
    { id: 'litigation-fee', type: 'calculator', name: '诉讼费计算器', icon: '⚖️',
      agent: 'legal', apiPath: '/api/legal/calc/litigation-fee', localScript: 'calc_litigation_fee',
      fields: [{ key: 'amount', label: '标的额（元）', type: 'currency', required: true }],
    },
    {
      id: 'claims-medical', type: 'calculator', name: '医疗理赔计算', icon: '🏥',
      agent: 'insurance_cs', apiPath: '/api/insurance_cs/consult/calculate/claims',
      description: '医疗险理赔金额计算（扣除免赔额和自费部分）',
      fields: [
        { key: 'total_medical', label: '医疗总费用（元）', type: 'currency', required: true },
        { key: 'self_pay', label: '自费部分（元）', type: 'currency', default: 0 },
        { key: 'deductible', label: '免赔额（元）', type: 'currency', default: 10000 },
        { key: 'reimburse_rate', label: '报销比例', type: 'select', default: '0.8',
          options: [
            { value: '1.0', label: '100%' }, { value: '0.9', label: '90%' },
            { value: '0.8', label: '80%' }, { value: '0.7', label: '70%' },
          ] },
      ],
    },
    {
      id: 'claims-disability', type: 'calculator', name: '伤残赔偿计算', icon: '♿',
      agent: 'insurance_cs', apiPath: '/api/insurance_cs/consult/calculate/claims',
      description: '意外伤残保险金计算（保额×伤残等级比例）',
      fields: [
        { key: 'insured_amount', label: '保险金额（元）', type: 'currency', required: true },
        { key: 'disability_level', label: '伤残等级', type: 'select', required: true,
          options: [
            { value: '1', label: '一级（100%）' }, { value: '2', label: '二级（90%）' },
            { value: '3', label: '三级（80%）' }, { value: '4', label: '四级（70%）' },
            { value: '5', label: '五级（60%）' }, { value: '6', label: '六级（50%）' },
            { value: '7', label: '七级（40%）' }, { value: '8', label: '八级（30%）' },
            { value: '9', label: '九级（20%）' }, { value: '10', label: '十级（10%）' },
          ] },
      ],
    },
    {
      id: 'claims-auto', type: 'calculator', name: '车险理赔计算', icon: '🚗',
      agent: 'insurance_cs', apiPath: '/api/insurance_cs/consult/calculate/claims',
      description: '交强险+商业险赔付额度计算',
      fields: [
        { key: 'loss_amount', label: '损失金额（元）', type: 'currency', required: true },
        { key: 'liability_ratio', label: '责任比例', type: 'select', required: true,
          options: [
            { value: '1.0', label: '全责（100%）' }, { value: '0.7', label: '主责（70%）' },
            { value: '0.5', label: '同等（50%）' }, { value: '0.3', label: '次责（30%）' },
          ] },
        { key: 'compulsory_limit', label: '交强险限额（元）', type: 'currency', default: 200000 },
      ],
    },
  ],
  slashCommands: [
    { cmd: '/诉讼费', label: '诉讼费', icon: '⚖️', toolId: 'litigation-fee' },
    { cmd: '/医疗理赔', label: '医疗理赔计算', icon: '🏥', toolId: 'claims-medical' },
    { cmd: '/车险', label: '车险理赔计算', icon: '🚗', toolId: 'claims-auto' },
    { cmd: '/伤残', label: '伤残赔偿计算', icon: '♿', toolId: 'claims-disability' },
    { cmd: '/速赔', label: '速赔判定', icon: '⚡', toolId: 'claims-auto' },
    { cmd: '/合规', label: '合规自查', icon: '🛡️' },
    { cmd: '/成本率', label: '综合成本率', icon: '📊' },
  ],
  safetyRules: [
    { id: 'claims-amount-limit', label: '赔付金额上限拦截', trigger: '赔付金额超过保额或交强险限额', action: '阻止赔付指令，需核保人确认' },
    { id: 'duplicate-claims', label: '重复报案检测', trigger: '同一保单号+同一出险日期+同一事故描述', action: '弹窗警告，标记可疑重复理赔' },
    { id: 'speed-claims-threshold', label: '速赔阈值拦截', trigger: '速赔金额 > 5000 元', action: '退出速赔通道，转标准理赔' },
    { id: 'compliance-speech-block', label: '话术合规拦截', trigger: '检测到收益承诺/夸大保障/误导性表述', action: '阻止发送，显示违规条款' },
    { id: 'premium-fund-isolation', label: '保费资金隔离', trigger: '保费收入用于非承保支出', action: '拒绝操作（保险法第 100 条）' },
    { id: 'policy-modification-audit', label: '保单变更审计', trigger: '退保/减保/受益人变更', action: '强制记录操作人+客户确认凭证' },
  ],
  quickActions: [
    { id: 'new-claim', label: '新报案', icon: '📋', workflowId: 'claim_process', description: '录入出险信息，AI 自动路由险种通道', cta: '录入报案' },
    { id: 'speed-claim', label: '速赔判定', icon: '⚡', description: '小额车险 2 分钟自动判定+出定损单', cta: '速赔判定' },
    { id: 'renewal-batch', label: '批量续保', icon: '🔄', workflowId: 'renewal_management', description: '一键筛选到期保单，批量生成续保方案', cta: '批量续保' },
    { id: 'compliance-scan', label: '合规自查', icon: '🛡️', description: '话术+法规+财务+资质四维合规扫描', cta: '开始自查' },
    { id: 'group-quote', label: '团险报价', icon: '👥', workflowId: 'group_insurance', description: '输入企业信息，AI 设计产品组合并报价', cta: '生成方案' },
    { id: 'cost-ratio', label: '综合成本率', icon: '📊', description: '赔付率/费用率/综合成本率分析和优化建议', cta: '查看分析' },
  ],
  workflows: [
    {
      id: 'claim_process', name: '理赔处理全流程', icon: '📋',
      description: '确保理赔快速准确结案，赔付金额合理、流程合规',
      mode: 'sequential',
      deliverable: '理赔结案报告（含定损金额 + 赔付依据 + 合规确认）',
      successCriteria: ['定损金额有评估依据', '赔付条款引用保险合同具体条款', '全流程符合银保监合规要求'],
      steps: [
        { id: 'report', agent: 'insurance_cs', expert: 'cs_consultant', label: '报案受理与初审',
          goal: '确认出险事实和保险责任', successCriteria: ['确认保单有效性', '初步判定是否属于承保范围'],
          profitImpact: { dimension: 'cost_saving', amount: '自动初审提速 3 倍，每单省人力 30 分钟' } },
        { id: 'assess', agent: 'insurance_cs', expert: 'cs_consultant', label: '查勘定损',
          goal: '确定损失金额和赔付标准', successCriteria: ['损失金额有评估依据', '明确免赔额和赔付比例'],
          profitImpact: { dimension: 'loss_avoidance', amount: '定损准确避免多赔，每单省 0.5-2 万' } },
        { id: 'approve', agent: 'finance', expert: 'finance_accountant', label: '核赔审批',
          goal: '审核赔付金额的合理性', successCriteria: ['赔付金额不超保额', '计算过程可审计'],
          profitImpact: { dimension: 'loss_avoidance', amount: '精准核赔降低综合成本率 1-3 个点' } },
        { id: 'compliance', agent: 'legal', expert: 'civil_lawyer', label: '合规审查与结案',
          goal: '确保理赔全流程合规', successCriteria: ['符合保险法规定', '无拒赔/惜赔风险'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免银保监处罚和声誉损失 10-50 万' } },
      ],
      triggerPhrases: ['理赔', '报案', '出险'],
    },
    {
      id: 'renewal_management', name: '续保挽留流程', icon: '🔄',
      description: '到期保单自动预警→客户分析→个性化续保方案→保费核算→合规审查',
      mode: 'sequential',
      deliverable: '续保方案报告（客户画像 + 新旧方案对比 + 保费明细 + 话术模板）',
      successCriteria: [
        '到期保单提前 30 天触发流程',
        '续保方案含 ≥ 2 种险种组合对比',
        '保费变化说明清晰，客户可直接决策',
      ],
      steps: [
        { id: 'profile', agent: 'insurance_cs', expert: 'cs_consultant', label: '客户画像与出险分析',
          goal: '分析客户历史保单和出险记录，评估续保价值',
          successCriteria: ['历史保费和出险汇总', '客户价值评级（高/中/低）', '续保意愿预判'],
          profitImpact: { dimension: 'revenue', amount: '精准画像提升续保率 15%，多收保费 25-50 万' } },
        { id: 'plan', agent: 'insurance_cs', expert: 'cs_consultant', label: '个性化续保方案',
          goal: '设计适合客户需求变化的续保方案',
          successCriteria: ['新旧方案保障范围对比', '保费变化原因说明', '含加保/减保建议'],
          profitImpact: { dimension: 'revenue', amount: '个性化方案提高客单价 10-20%' } },
        { id: 'premium', agent: 'finance', expert: 'finance_accountant', label: '保费核算与佣金',
          goal: '计算续保保费和渠道佣金',
          successCriteria: ['各险种保费逐项列出', '佣金比例和金额明确', '含分期缴费方案'],
          profitImpact: { dimension: 'cost_saving', amount: '自动核算省财务人力，每单省 30 分钟' } },
        { id: 'compliance', agent: 'legal', expert: 'civil_lawyer', label: '续保合规审查',
          goal: '确保续保流程和话术合规',
          successCriteria: ['无销售误导风险', '条款变更说明符合银保监要求', '退保提示到位'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免销售误导处罚 10-100 万' } },
      ],
      triggerPhrases: ['续保', '到期保单', '保单续期'],
    },
    {
      id: 'group_insurance', name: '团险签约流程', icon: '👥',
      description: '从企业需求分析到方案设计、报价、合同审查的团险全流程',
      mode: 'sequential',
      deliverable: '团险方案书（需求分析 + 险种组合 + 报价明细 + 合同要点）',
      successCriteria: [
        '方案覆盖企业核心需求（雇主责任/团意/团医）',
        '报价含对标竞品的优势说明',
        '合同条款无不利于投保人的隐患',
      ],
      steps: [
        { id: 'needs', agent: 'sales', expert: 'sales_strategist', label: '企业需求分析',
          goal: '评估企业保障需求和预算',
          successCriteria: ['行业风险特征分析', '员工人数和年龄结构', '预算范围和决策流程'],
          profitImpact: { dimension: 'revenue', amount: '精准需求匹配提升签约率，团险增收 5-15 万/单' } },
        { id: 'design', agent: 'insurance_cs', expert: 'cs_consultant', label: '方案设计与定价',
          goal: '设计险种组合并初步报价',
          successCriteria: ['≥ 2 套方案对比（基础/增强）', '含各险种保障范围和保额', '费率说明透明'],
          profitImpact: { dimension: 'revenue', amount: '多方案对比提高客单价 20%' } },
        { id: 'quote', agent: 'finance', expert: 'finance_accountant', label: '保费精算与佣金测算',
          goal: '输出精确报价和佣金结构',
          successCriteria: ['保费逐险种列出', '含年缴/月缴方案', '佣金和利润率测算'],
          profitImpact: { dimension: 'revenue', amount: '快速精准报价，签约周期缩短一半' } },
        { id: 'contract', agent: 'legal', expert: 'civil_lawyer', label: '合同条款审查',
          goal: '审查保险合同和补充协议',
          successCriteria: ['免责条款逐条标注', '理赔时效和流程说明清晰', '无不合理限制'],
          profitImpact: { dimension: 'loss_avoidance', amount: '合同审查避免后续纠纷损失 10-50 万' } },
      ],
      triggerPhrases: ['团险', '团体保险', '企业保险'],
    },
    {
      id: 'speed_claims', name: '速赔通道自动判定', icon: '⚡',
      description: '小额车险速赔：AI 自动判定资格→出定损单→赔付指令，2 分钟结案',
      mode: 'sequential',
      deliverable: '速赔判定结果（通过/拒绝 + 定损单 + 赔付指令）',
      successCriteria: ['金额在速赔阈值内', '无人伤', '材料齐全'],
      steps: [
        { id: 'check', agent: 'insurance_cs', expert: 'cs_consultant', label: '要素校验',
          goal: '核验报案金额、人伤情况、材料完整性',
          successCriteria: ['金额 < 5000 元', '无人伤确认', '材料齐全确认'],
          profitImpact: { dimension: 'cost_saving', amount: '速赔省人力 30 分钟/单，月省 200+ 小时' } },
        { id: 'judge', agent: 'insurance_cs', expert: 'cs_consultant', label: '规则引擎判定',
          goal: '比对速赔规则库输出通过/拒绝',
          successCriteria: ['规则匹配完整', '判定理由可追溯'],
          profitImpact: { dimension: 'cost_saving', amount: '自动判定零人工介入' } },
        { id: 'settle', agent: 'insurance_cs', expert: 'cs_consultant', label: '定损出单',
          goal: '自动生成定损单和赔付指令',
          successCriteria: ['定损金额合理', '赔付指令完整'],
          profitImpact: { dimension: 'cost_saving', amount: '客户满意度提升 40%' } },
      ],
      triggerPhrases: ['速赔', '快赔', '小额理赔'],
    },
    {
      id: 'compliance_audit', name: '合规自查', icon: '🛡️',
      description: '话术+法规+财务+资质四维并行扫描，一键输出自查报告',
      mode: 'parallel',
      deliverable: '合规自查报告（四维扫描结果 + 整改清单 + 优先级排序）',
      successCriteria: ['话术无违规表述', '法规比对无遗漏', '财务资金隔离合规', '人员资质齐全'],
      steps: [
        { id: 'speech', agent: 'insurance_cs', expert: 'cs_consultant', label: '话术扫描',
          goal: '检查全部客服/销售话术合规性',
          successCriteria: ['无收益承诺', '无夸大保障', '免责告知到位'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免银保监话术类处罚 10-50 万' } },
        { id: 'regulation', agent: 'legal', expert: 'civil_lawyer', label: '法规比对',
          goal: '比对最新银保监规定标注缺口',
          successCriteria: ['覆盖最新法规', '合规缺口逐项标注'],
          profitImpact: { dimension: 'loss_avoidance', amount: '规避法规盲区处罚' } },
        { id: 'finance_compliance', agent: 'finance', expert: 'finance_accountant', label: '财务合规',
          goal: '保费资金隔离和准备金合规检查',
          successCriteria: ['保费资金隔离', '准备金计提充足', '佣金支付合规'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免资金违规处罚 50-200 万' } },
        { id: 'hr_compliance', agent: 'hr', expert: 'hr_consultant', label: '资质审查',
          goal: '代理人持证和培训记录审查',
          successCriteria: ['全员持证上岗', '培训记录完整', '继续教育达标'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免无证经营处罚' } },
      ],
      triggerPhrases: ['合规', '自查', '银保监检查'],
    },
    {
      id: 'combined_ratio', name: '综合成本率分析', icon: '📊',
      description: '按险种/渠道分拆赔付率和费用率，对标行业均值并给出优化路径',
      mode: 'parallel',
      deliverable: '综合成本率分析报告（赔付率 + 费用率 + 行业对标 + 优化建议）',
      successCriteria: ['各险种赔付率分拆', '费用率分渠道计算', '对标行业均值'],
      steps: [
        { id: 'collect', agent: 'finance', expert: 'finance_accountant', label: '数据归集',
          goal: '按险种和渠道归集赔付与费用数据',
          successCriteria: ['数据覆盖全险种', '渠道分拆完整'],
          profitImpact: { dimension: 'revenue', amount: '精准数据支撑降赔决策' } },
        { id: 'analyze', agent: 'insurance_cs', expert: 'cs_consultant', label: '高赔分析',
          goal: '识别高赔付险种和高频出险场景',
          successCriteria: ['Top5 高赔险种', '高频出险场景分析'],
          profitImpact: { dimension: 'cost_saving', amount: '针对性降赔省 3-5 个点' } },
        { id: 'benchmark', agent: 'finance', expert: 'finance_accountant', label: '行业对标',
          goal: '综合成本率对标同业',
          successCriteria: ['行业均值对比', '偏差原因分析', '优化路径'],
          profitImpact: { dimension: 'revenue', amount: '综合成本率降 3 个点 = 利润率升 3 个点' } },
      ],
      triggerPhrases: ['综合成本率', '赔付率', '费用率'],
    },
  ],
  scenarios: [
    { id: 'claim_consult', label: '理赔咨询', icon: '📞', prompt: '咨询这个保险理赔的流程和注意事项', expectedOutcome: '理赔材料清单 + 时间预估 + 注意事项 + 拒赔风险提示', expert: 'insurance_cs.cs_consultant', profitImpact: { dimension: 'cost_saving', amount: '速赔通道省运营成本 500-2000 元/单' } },
    { id: 'policy_check', label: '保单查询', icon: '📄', prompt: '查询这份保单的保障范围和条款', expectedOutcome: '保障范围 + 免责条款 + 免赔额 + 理赔限额', expert: 'insurance_cs.cs_consultant', profitImpact: { dimension: 'cost_saving', amount: '自助查询减少人工坐席，月省 5000 元+' } },
    { id: 'renewal_quote', label: '续保方案', icon: '🔄', prompt: '为这位客户设计最优续保方案', expectedOutcome: '新旧方案对比 + 保费变化 + 保障差异 + 推荐理由', expert: 'insurance_cs.cs_consultant', profitImpact: { dimension: 'revenue', amount: '续保挽留率提升 15%，多收保费 25-50 万' } },
    { id: 'dispute_handle', label: '理赔纠纷', icon: '⚖️', prompt: '处理这个保险理赔纠纷，分析法律依据和应对方案', expectedOutcome: '纠纷性质判定 + 保险法条款引用 + 调解/诉讼建议', expert: 'legal.civil_lawyer', profitImpact: { dimension: 'loss_avoidance', amount: '避免败诉赔偿 10-50 万' } },
    { id: 'group_quote', label: '团险报价', icon: '👥', prompt: '为这家企业设计团体保险方案并报价', expectedOutcome: '险种组合推荐 + 保费估算 + 服务方案 + 竞品对标', expert: 'sales.sales_consultant', profitImpact: { dimension: 'revenue', amount: '精选方案提高签约率，团险增收 5-15 万/单' } },
    { id: 'speed_claim_check', label: '速赔判定', icon: '⚡', prompt: '判断这个车险案件是否符合速赔条件', expectedOutcome: '速赔资格判定 + 定损单 + 赔付时效预估', expert: 'insurance_cs.cs_consultant', profitImpact: { dimension: 'cost_saving', amount: '速赔 2 分钟结案，省人力 30 分钟/单' } },
    { id: 'cost_ratio', label: '综合成本率', icon: '📊', prompt: '分析本季度综合成本率并给出优化建议', expectedOutcome: '赔付率 + 费用率 + 行业对标 + 降赔路径', expert: 'finance.finance_accountant', profitImpact: { dimension: 'revenue', amount: '综合成本率降 3 个点' } },
    { id: 'compliance_self_check', label: '合规自查', icon: '🛡️', prompt: '进行银保监合规自查', expectedOutcome: '四维扫描结果 + 整改清单 + 优先级', expert: 'insurance_cs.cs_consultant', profitImpact: { dimension: 'loss_avoidance', amount: '避免银保监处罚 10-200 万' } },
  ],
}

export default insuranceOperationsSolution
