/**
 * 自动拆分自 solution-registry-data.ts。
 * 请勿手工编辑“结构”——如需改方案内容，请直接改本文件字段即可。
 */
import type { SolutionConfig } from '../solution-router'
import { agent } from '../solution-router-agent'

export const investmentResearchSolution: SolutionConfig = {
  id: 'investment-research',
  name: '投研机构智能方案',
  icon: '📈',
  color: '#d97706',
  tagline: '研究员产出翻 10 倍，从 α 研究到合规发布全链路提速',
  description: '投研竞争力 = 研究深度 × 覆盖广度 × 出报告速度。一个研究员过去一周出一篇深度研报，现在一天出三篇，每个结论可追溯到数据源。',
  entrepreneurPurpose: '研究员产能翻 10 倍，帮客户赚到 α → AUM 增长 → 管理费收入增长',
  profitMetrics: ['深度研报 1 周→1 天', '覆盖股票数翻 10 倍', '合规审查自动化，发布快 50%'],
  valueEquivalent: { humanHours: 320, mbeMinutes: 15, acceleration: '1280x' },
  agents: [
    agent('invest', 8011, '投资分析专家', '四柱研判、MISES评分、产业链追踪、WorldMonitor全球情报'),
    agent('finance', 8002, '财务审计专家', '三表分析、估值建模、财务比率、异常检测'),
    agent('legal', 8003, '投资合规专家', '研报合规、信息披露、利益冲突、证券法'),
  ],
  localScripts: ['calc_iit', 'calc_vat'],
  knowledgeCache: ['invest_mises_framework'],
  theme: { primary: '38 92% 43%', accent: '38 92% 43%' },
  enabledTabs: ['today', 'research', 'portfolio', 'macro', 'compliance-pub', 'mises-export', 'tools', 'documents', 'chat', 'knowledge-graph'],
  onboarding: {
    questions: [
      { key: 'institution_type', label: '机构类型', options: ['私募基金', '家族办公室', '独立投研工作室', '券商/资管', '个人投资者'] },
      { key: 'coverage', label: '主要覆盖领域', options: ['A股', '港股', '美股', 'A+港股', '全球多市场'] },
      { key: 'aum_scale', label: 'AUM 规模', options: ['<1000万', '1000万-1亿', '1亿-10亿', '10亿以上', '不适用'] },
    ],
  },
  tools: [
    { id: 'financial-ratio', type: 'calculator', name: '财务比率分析', icon: '📊',
      agent: 'finance', apiPath: '/api/finance/calc/ratio',
      description: '杜邦分析、盈利/偿债/运营效率等20+财务比率计算',
      fields: [
        { key: 'revenue', label: '营业收入（万元）', type: 'currency', required: true },
        { key: 'net_profit', label: '净利润（万元）', type: 'currency', required: true },
        { key: 'total_assets', label: '总资产（万元）', type: 'currency', required: true },
        { key: 'total_equity', label: '股东权益（万元）', type: 'currency', required: true },
        { key: 'total_liability', label: '总负债（万元）', type: 'currency', required: true },
      ],
    },
    { id: 'mises-score', type: 'calculator', name: 'MISES 五维评分', icon: '🎯',
      agent: 'invest', apiPath: '/api/invest/mises-score',
      description: '市场/创新/可扩展/护城河/安全边际 五维量化评估',
      fields: [
        { key: 'ticker', label: '股票代码', type: 'text', required: true },
        { key: 'market', label: '市场', type: 'select', required: true,
          options: [
            { value: 'A', label: 'A股' },
            { value: 'HK', label: '港股' },
            { value: 'US', label: '美股' },
          ] },
      ],
    },
    { id: 'valuation-calc', type: 'calculator', name: '估值计算器', icon: '💹',
      agent: 'invest', apiPath: '/api/invest/valuation',
      description: 'PE/PB/PS/DCF 多方法交叉估值',
      fields: [
        { key: 'eps', label: '每股收益 EPS（元）', type: 'currency', required: true },
        { key: 'bvps', label: '每股净资产 BVPS（元）', type: 'currency', required: true },
        { key: 'revenue_ps', label: '每股营收 RPS（元）', type: 'currency', required: true },
        { key: 'growth_rate', label: '预期增长率（%）', type: 'number', required: true },
      ],
    },
    { id: 'stamp-tax', type: 'calculator', name: '印花税计算', icon: '📌',
      agent: 'finance', apiPath: '/api/finance/calc/stamp-tax',
      description: '证券交易印花税计算（卖出时0.05%）',
      fields: [
        { key: 'contract_type', label: '类型', type: 'select', required: true,
          options: [
            { value: 'stock_sale', label: '股票卖出（0.05%）' },
            { value: 'property_transfer', label: '产权转移（0.05%）' },
          ] },
        { key: 'amount', label: '交易金额（元）', type: 'currency', required: true },
      ],
    },
    // ── 企业 AI 降本增效（workforce_ai_analyst Expert） ──
    { id: 'workforce-ai-roi', type: 'calculator', name: '企业AI降本ROI测算', icon: '🤖',
      agent: 'invest', apiPath: '/api/invest/workforce_ai/roi_only',
      description: '输入股票代码，秒算企业部署 AI 后的人力替代率 / 年化节省 / 投资回收期',
      category: 'AI 降本增效',
      fields: [
        { key: 'ticker', label: '股票代码', type: 'text', placeholder: '如 600482 或 00751.HK', required: true },
        { key: 'deployment_mode', label: '部署模式', type: 'select', default: 'auto',
          options: [
            { value: 'auto', label: '自动识别（按行业推荐）' },
            { value: 'saas', label: 'SaaS 云端（溢价 1.0×）' },
            { value: 'private', label: '私有化部署（溢价 2.5×）' },
            { value: 'hybrid', label: '混合云（溢价 1.8×）' },
            { value: 'offline', label: '物理隔离离线（溢价 4.0×）' },
          ] },
        { key: 'industry_key', label: '行业标识（可选）', type: 'text', placeholder: '留空自动识别' },
      ],
    },
    { id: 'workforce-ai-report', type: 'doc-generator', name: '企业AI应用场景研报', icon: '📝',
      agent: 'invest', apiPath: '/api/invest/workforce_ai/full_report',
      description: '端到端生成《企业 AI 降本增效应用场景研究》Markdown 研报（含 ROI 测算 + 场景拆解 + 部署建议）',
      category: 'AI 降本增效',
      fields: [
        { key: 'ticker', label: '股票代码', type: 'text', placeholder: '如 600482', required: true },
        { key: 'deployment_mode', label: '部署模式', type: 'select', default: 'auto',
          options: [
            { value: 'auto', label: '自动识别' },
            { value: 'saas', label: 'SaaS 云端' },
            { value: 'private', label: '私有化部署' },
            { value: 'hybrid', label: '混合云' },
            { value: 'offline', label: '物理隔离离线' },
          ] },
        { key: 'industry_key', label: '行业标识覆盖', type: 'text', placeholder: '留空自动识别' },
        { key: 'title_override', label: '自定义报告标题', type: 'text', placeholder: '留空使用默认标题' },
      ],
    },
    { id: 'workforce-ai-batch-scan', type: 'calculator', name: '企业AI降本批量扫描', icon: '🔍',
      agent: 'invest', apiPath: '/api/invest/workforce_ai/batch_scan',
      description: '批量扫描多只股票的 AI 降本增效潜力，一次生成多份研报（按 ROI 从高到低）',
      category: 'AI 降本增效',
      fields: [
        { key: 'tickers', label: '股票代码列表', type: 'textarea',
          placeholder: '多个代码用逗号、换行或分号分隔\n例如：600482, 600036, 000001',
          required: true, array: true, arraySeparator: '[,;\\n\\s]+' },
        { key: 'deployment_mode', label: '部署模式', type: 'select', default: 'auto',
          options: [
            { value: 'auto', label: '自动识别（按行业推荐）' },
            { value: 'saas', label: 'SaaS 云端' },
            { value: 'private', label: '私有化部署' },
            { value: 'hybrid', label: '混合云' },
            { value: 'offline', label: '物理隔离离线' },
          ] },
      ],
    },
    // ── MISES 研报导出（PDF / PPTX 矢量版） ──
    { id: 'mises-report-export', type: 'file-export', name: 'MISES 深度研报导出', icon: '📄',
      agent: 'invest', apiPath: '/api/invest/mises/report/{ticker}/export',
      method: 'GET',
      description: '导出含矢量图表的 MISES 五维深度研报（PDF 或 PPTX），支持打印 / 路演分发',
      category: 'MISES 研报',
      fileNameTemplate: '{ticker}_MISES研报_{date}.{ext}',
      fields: [
        { key: 'ticker', label: '股票代码', type: 'text',
          placeholder: '如 600482 或 00751.HK 或 AAPL', required: true },
        { key: 'market', label: '市场', type: 'select', required: true,
          options: [
            { value: 'A', label: 'A股' },
            { value: 'HK', label: '港股' },
            { value: 'US', label: '美股' },
          ] },
      ],
      exportFormats: [
        { value: 'pdf',  label: 'PDF（适合打印/存档）', ext: 'pdf' },
        { value: 'pptx', label: 'PPTX（适合路演/演示）', ext: 'pptx' },
      ],
    },
  ],
  slashCommands: [
    { cmd: '/比率', label: '财务比率', icon: '📊', toolId: 'financial-ratio' },
    { cmd: '/评分', label: 'MISES评分', icon: '🎯', toolId: 'mises-score' },
    { cmd: '/估值', label: '估值计算', icon: '💹', toolId: 'valuation-calc' },
    { cmd: '/印花税', label: '印花税', icon: '📌', toolId: 'stamp-tax' },
    { cmd: '/降本', label: 'AI降本ROI', icon: '🤖', toolId: 'workforce-ai-roi' },
    { cmd: '/AI研报', label: '企业AI研报', icon: '📝', toolId: 'workforce-ai-report' },
  ],
  workflows: [
    {
      id: 'deep_research', name: '行业深度研究', icon: '🏛️',
      description: '宏观环境 → 行业分析 → 公司筛选 → 深度评分 → 研报生成',
      mode: 'sequential',
      deliverable: '行业深度研究报告（宏观+行业+重点公司+投资建议）',
      successCriteria: [
        '宏观信号有明确 BUY/CASH 判断且来源可追溯',
        '行业分析含生命周期和 AI 影响评估',
        '个股 MISES 评分 ≥ 3 维达标',
        '研报结构完整，含免责声明和数据来源',
      ],
      steps: [
        { id: 'macro_assessment', agent: 'invest', expert: 'investment_analyst', label: '宏观环境评估',
          goal: '获取 WorldMonitor 信号，计算 MEI 评分，判断 Risk-On/Off', successCriteria: ['MEI 评分及分项', 'BUY/CASH 信号判断', '地缘风险标注'],
          profitImpact: { dimension: 'loss_avoidance', amount: 'CASH 信号避免系统性下跌，保护本金 10-30%' } },
        { id: 'industry_analysis', agent: 'invest', expert: 'investment_analyst', label: '行业深度分析',
          goal: '行业生命周期+五力分析+产业链利润定位+AI影响', successCriteria: ['行业景气度评分', '产业链利润分布', 'AI 影响光谱'],
          profitImpact: { dimension: 'revenue', amount: '精准行业选择，超额收益 10-25%' } },
        { id: 'company_screening', agent: 'invest', expert: 'investment_analyst', label: '公司筛选',
          goal: '自上而下+多因子过滤+MISES 排序', successCriteria: ['MISES 五维评分', '筛出 5-8 家候选标的', '标注核心竞争优势'],
          profitImpact: { dimension: 'revenue', amount: 'MISES 选股胜率 65%+，Alpha 显著' } },
        { id: 'financial_deep_dive', agent: 'finance', expert: 'finance_accountant', label: '财务深度分析',
          goal: '三表分析+20+比率+杜邦分解+异常检测', successCriteria: ['财务健康评分', '异常指标红旗', '三年趋势'],
          profitImpact: { dimension: 'loss_avoidance', amount: '识别财务造假，避免踩雷损失 20-50%' } },
        { id: 'report_generation', agent: 'invest', expert: 'investment_analyst', label: '研报生成',
          goal: '整合分析结果，按标准结构输出研报', successCriteria: ['标注数据来源', '含风险提示', '含免责声明'],
          profitImpact: { dimension: 'revenue', amount: '深度研报 1 周→1 天，研究员产出翻 10 倍' } },
      ],
      triggerPhrases: ['行业研究', '深度研报', '全链路', '从头分析'],
    },
    {
      id: 'stock_screening', name: '多维选股筛选', icon: '🎯',
      description: '宏观评分 → 行业轮动 → 多因子筛选 → 估值验证 → 候选池',
      mode: 'sequential',
      deliverable: '选股候选池（3-5 只标的 + MISES 评分 + 买入区间 + 止损线）',
      successCriteria: [
        '多因子筛选覆盖成长/质量/估值/动量/AI 五维',
        '估值交叉验证 ≥ 2 种方法',
        '每只标的含安全边际评估',
      ],
      steps: [
        { id: 'macro_scoring', agent: 'invest', expert: 'investment_analyst', label: '宏观评分与配置',
          goal: 'MEI 评分→总仓位+行业权重', successCriteria: ['建议总仓位', '推荐行业权重', '风险事件标注'],
          profitImpact: { dimension: 'loss_avoidance', amount: '仓位控制避免大幅回撤' } },
        { id: 'factor_screening', agent: 'invest', expert: 'investment_analyst', label: '多因子筛选',
          goal: '成长+质量+估值+动量+AI 五维因子过滤', successCriteria: ['各因子得分', '综合排序', '推荐逻辑'],
          profitImpact: { dimension: 'revenue', amount: '多因子选股胜率提升，Alpha 收益显著' } },
        { id: 'valuation_verify', agent: 'finance', expert: 'finance_accountant', label: '估值交叉验证',
          goal: 'DCF + 同行对标 + 安全边际', successCriteria: ['估值区间', '安全边际评级', '方法标注'],
          profitImpact: { dimension: 'loss_avoidance', amount: '买在低估区间，避免高位接盘' } },
        { id: 'final_ranking', agent: 'invest', expert: 'investment_analyst', label: '综合排序',
          goal: 'MISES + BM Score 综合排序，生成候选池', successCriteria: ['最终 3-5 只推荐', '含买入区间和止损', '含风险提示'],
          profitImpact: { dimension: 'revenue', amount: '精选标的年化收益提升 10-20%' } },
      ],
      triggerPhrases: ['选股', '筛选', '多因子', '候选池'],
    },
    {
      id: 'portfolio_review', name: '组合定期审查', icon: '📊',
      description: '持仓回顾 + 宏观信号 + 估值检查 + 合规检查 → 调仓建议',
      mode: 'parallel',
      deliverable: '组合审查报告（持仓状态 + 宏观变化 + 估值健康 + 合规 + 调仓建议）',
      successCriteria: [
        '四维审查完整覆盖',
        '调仓建议含执行计划和时间窗口',
        '合规检查标注超限风险',
      ],
      steps: [
        { id: 'position_review', agent: 'invest', expert: 'investment_analyst', label: '持仓回顾',
          goal: '各持仓涨跌+逻辑变化+催化剂跟踪', successCriteria: ['持仓状态评级', '投资逻辑变化标注', '事件日历'],
          profitImpact: { dimension: 'revenue', amount: '及时发现持仓问题，减少无效持有' } },
        { id: 'macro_update', agent: 'invest', expert: 'investment_analyst', label: '宏观信号更新',
          goal: 'WorldMonitor 最新信号 + MEI 变化 + 地缘扫描', successCriteria: ['MEI 与上期对比', '信号变化方向', '影响评估'],
          profitImpact: { dimension: 'loss_avoidance', amount: '宏观预警避免系统性风险' } },
        { id: 'valuation_check', agent: 'finance', expert: 'finance_accountant', label: '估值健康检查',
          goal: '当前估值 vs 买入估值 + 同行对标', successCriteria: ['估值状态评级', '异常标注', '调整建议'],
          profitImpact: { dimension: 'loss_avoidance', amount: '及时发现估值泡沫，锁定利润' } },
        { id: 'compliance_check', agent: 'legal', expert: 'civil_lawyer', label: '合规检查',
          goal: '集中度+关联交易+信息披露', successCriteria: ['合规状态', '违规明细', '整改建议'],
          profitImpact: { dimension: 'loss_avoidance', amount: '合规预警避免监管处罚' } },
        { id: 'rebalance_suggestion', agent: 'invest', expert: 'investment_analyst', label: '调仓建议',
          goal: '综合四维审查，生成加/减/清/新建仓建议', successCriteria: ['操作清单按优先级', '理由和预期影响', '调仓后风险评估'],
          profitImpact: { dimension: 'revenue', amount: '纪律化调仓，组合年化收益提升 5-10%' } },
      ],
      triggerPhrases: ['组合审查', '持仓回顾', '调仓', '组合检查'],
    },
    {
      id: 'report_compliance', name: '研报合规审查', icon: '📋',
      description: '内容审查 → 利益冲突 → 数据验证 → 发布前清单',
      mode: 'sequential',
      deliverable: '合规审核意见（通过/修改后发布/退回 + 问题清单 + 修改建议）',
      successCriteria: [
        '内容审查覆盖数据来源/预测表述/评级定义/风险提示',
        '利益冲突检查完整',
        '数据源验证通过',
        '免责声明完整',
      ],
      steps: [
        { id: 'content_review', agent: 'legal', expert: 'civil_lawyer', label: '内容合规审查',
          goal: '检查数据来源/股价预测/评级定义/风险提示', successCriteria: ['合规问题清单', '严重程度分级', '修改建议'],
          profitImpact: { dimension: 'loss_avoidance', amount: '合规审查自动化，发布快 50%，避免违规处罚' } },
        { id: 'conflict_check', agent: 'legal', expert: 'civil_lawyer', label: '利益冲突检查',
          goal: '分析师持股/机构业务关系/承销利益冲突', successCriteria: ['冲突状态', '需披露清单', '披露文本'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免利益冲突丑闻，保护机构声誉' } },
        { id: 'data_verify', agent: 'invest', expert: 'investment_analyst', label: '数据源验证',
          goal: '验证引用数据准确性和时效性', successCriteria: ['数据验证清单', '过时数据标注', '假设合理性'],
          profitImpact: { dimension: 'loss_avoidance', amount: '数据准确性保障研报质量' } },
        { id: 'final_checklist', agent: 'legal', expert: 'civil_lawyer', label: '发布前清单',
          goal: '汇总所有审查+签发合规意见', successCriteria: ['合规评分', '必须修改项', '免责声明确认'],
          profitImpact: { dimension: 'loss_avoidance', amount: '一键合规审查替代人工 3-5 天审核' } },
      ],
      triggerPhrases: ['合规审查', '研报审核', '发布前检查'],
    },
    {
      id: 'workforce_ai_roi', name: 'AI 化程度 × ROI 全景', icon: '🤖',
      description: '知识员工结构分析 → 三源融合 AI 自动化率 → 降本 ROI → EPS 增厚 → 目标股价推导',
      mode: 'sequential',
      deliverable: 'AI 降本 ROI 报告（员工结构 + 三情景 ROI + EPS 增厚 + 目标股价 + a16z 六要素评分）',
      successCriteria: [
        '三源融合（O*NET × McKinsey × Anthropic EI 2026）自动化率计算完整',
        '悲观/基准/乐观三情景 ROI 区间清晰',
        'EPS 增厚和目标股价均有假设说明',
        'a16z 六要素评分有行业对标',
        '分析师确认 ROI 假设后才纳入研报',
      ],
      steps: [
        { id: 'workforce_structure', agent: 'invest', expert: 'investment_analyst', label: '员工结构分析',
          goal: '识别知识型岗位分布，估算知识员工总薪酬包',
          successCriteria: ['知识员工占比估算', '人均年薪口径明确', '总薪酬包区间'],
          profitImpact: { dimension: 'revenue', amount: '精准识别 AI 替代空间，差异化于传统研报' } },
        { id: 'ai_automation_rate', agent: 'invest', expert: 'investment_analyst', label: 'AI 自动化率（三源融合）',
          goal: '基于 O*NET × McKinsey × Anthropic EI 2026 计算加权自动化率',
          successCriteria: ['三源数据均有引用', '岗位类型分类完整', '综合自动化率有置信区间'],
          profitImpact: { dimension: 'revenue', amount: '三源融合方法论，研报说服力大幅提升' } },
        { id: 'roi_calculation', agent: 'invest', expert: 'investment_analyst', label: '降本 ROI 计算',
          goal: '三情景（悲观 20%/基准 40%/乐观 65% 采纳率）计算净节省和回本周期',
          successCriteria: ['三情景清晰区分', '净 ROI = 节省 - AI 工具成本', '回本周期 ≤ 2 年基准'],
          profitImpact: { dimension: 'revenue', amount: '可量化 ROI 是基金经理买单的核心依据' } },
        { id: 'eps_uplift', agent: 'finance', expert: 'finance_accountant', label: 'EPS 增厚测算',
          goal: '税后净利增量 ÷ 总股本，含 ROE 改善和回购摊薄测算',
          successCriteria: ['税率口径确认', 'EPS 增厚元/股清晰', '增厚比例 % 注明'],
          profitImpact: { dimension: 'revenue', amount: 'EPS 增厚直接支撑目标价上调' } },
        { id: 'target_price', agent: 'invest', expert: 'investment_analyst', label: '目标股价建模',
          goal: '(当前EPS + 增厚) × (PE + BCG AI成熟度溢价) → 三情景目标价',
          successCriteria: ['AI 成熟度等级 L1-L4 判断有依据', 'PE 基准来源注明', '三情景上涨空间计算'],
          profitImpact: { dimension: 'revenue', amount: 'AI 驱动目标价上调，是差异化研报的核心输出' } },
        { id: 'a16z_six_factors', agent: 'invest', expert: 'investment_analyst', label: 'a16z 六要素检核',
          goal: '数据护城河/工作流嵌入/模型定制/ROI可量化/执行力/替代风险六维打分',
          successCriteria: ['六维均有评分', '行业均值对标', 'AI 落地质量结论明确'],
          profitImpact: { dimension: 'revenue', amount: '六要素评分帮助基金经理识别 AI 红利兑现概率' } },
        { id: 'analyst_review', agent: 'invest', expert: 'investment_analyst', label: '分析师确认（HITL）',
          goal: '校验薪酬口径、采纳率情景、税率、PE 基准，确认后纳入研报',
          successCriteria: ['关键假设均已确认', '免责提示已添加', '数据截止日期注明'],
          profitImpact: { dimension: 'loss_avoidance', amount: 'HITL 确认保障研报数据质量，避免误导投资者' } },
      ],
      triggerPhrases: ['AI 降本', 'AI 化程度', 'ROI 分析', '人力替代', 'EPS 增厚', '企业 AI', 'workforce AI', '自动化率'],
    },
  ],
  safetyRules: [
    { id: 'insider-info-guard', label: '内幕信息防护', trigger: '对话涉及未公开财报数据、重大资产重组等内幕信息', action: '红色阻断，禁止生成含内幕信息的研报，提示合规申报' },
    { id: 'position-concentration-alert', label: '持仓集中度预警', trigger: '单只股票持仓占比超过组合 20% 或单行业超过 40%', action: '橙色预警，提示风险敞口并建议分散' },
    { id: 'stale-data-warning', label: '数据时效性检查', trigger: '引用的财务数据超过 2 个季度或宏观数据超过 1 个月', action: '橙色提示，标注数据截止日期并建议更新' },
    { id: 'prediction-precision-guard', label: '预测精度限制', trigger: '研报中出现精确到小数点的短期股价预测', action: '红色阻断，替换为区间估值和概率描述' },
    { id: 'conflict-disclosure-check', label: '利益冲突披露检查', trigger: '分析师或机构持有研报标的股票', action: '强制添加利益冲突披露声明' },
    { id: 'client-data-isolation', label: '客户数据隔离', trigger: '不同客户的持仓数据出现在同一会话', action: '红色阻断，确保客户数据严格隔离' },
  ],
  quickActions: [
    { id: 'quick-macro-refresh', label: '刷新宏观数据', icon: '🔄', workflowId: 'portfolio_review', description: '从 akshare/yfinance 拉取最新 PMI/M2/社融/CPI（6小时冷却）', cta: '立即刷新', apiEndpoint: '/api/invest/four-pillar/macro/refresh', apiMethod: 'POST' },
    { id: 'quick-macro', label: '宏观信号速查', icon: '🌍', workflowId: 'portfolio_review', description: '一键获取 WorldMonitor 7 大宏观信号和 BUY/CASH 判断', cta: '查看信号' },
    { id: 'quick-mises-score', label: 'MISES 评分', icon: '🎯', workflowId: 'stock_screening', description: '输入股票代码，秒出 MISES 五维评分', cta: '立即评分' },
    { id: 'quick-valuation', label: '快速估值', icon: '💹', workflowId: 'stock_screening', description: 'PE/PB/PS/DCF 多方法交叉估值', cta: '开始估值' },
    { id: 'quick-compliance', label: '研报合规审查', icon: '⚖️', workflowId: 'report_compliance', description: '一键审查研报内容的合规性', cta: '开始审查' },
    { id: 'quick-portfolio', label: '组合健康检查', icon: '📊', workflowId: 'portfolio_review', description: '一键审查持仓集中度/估值/合规状态', cta: '立即检查' },
    { id: 'quick-ai-roi', label: '企业AI降本', icon: '🤖', workflowId: 'workforce_ai_roi', description: '三源融合自动化率 → EPS 增厚 → 目标股价，3天→15分钟', cta: '开始分析' },
  ],
  scenarios: [
    // ── 四柱决策链：该不该买 → 买哪个行业 → 买哪只 → 怎么操作 ──
    { id: 'pillar_macro', label: '柱1·该不该买', icon: '🌍',
      prompt: '当前市场环境下应该加仓还是减仓？', apiEndpoint: '/api/invest/four-pillar/macro', apiMethod: 'GET',
      expectedOutcome: 'BUY/CASH 信号 + 先行/同步/滞后指标评分 + Risk-On/Off 判断',
      expert: 'invest.investment_analyst', profitImpact: { dimension: 'loss_avoidance', amount: '风控精准，最大回撤控制在 5% 内' } },
    { id: 'pillar_hotspot', label: '柱2·买哪个行业', icon: '🔥',
      prompt: '当前最值得关注的行业板块有哪些？', apiEndpoint: '/api/invest/four-pillar/hotspot', apiMethod: 'GET',
      expectedOutcome: '四象限热点模型 + 板块轮动方向 + 催化剂事件',
      expert: 'invest.investment_analyst', profitImpact: { dimension: 'revenue', amount: '精准择时择势，预期超额收益 10-30%' } },
    { id: 'pillar_stock', label: '柱3·买哪只股票', icon: '🎯',
      prompt: '在当前热点行业中筛选最优个股', apiEndpoint: '/api/invest/four-pillar/stock', apiMethod: 'GET',
      expectedOutcome: 'MISES 五维评分 + 信仰度评估 + 关键标的排名',
      expert: 'invest.investment_analyst', profitImpact: { dimension: 'revenue', amount: '选股胜率提升，Alpha 收益显著' } },
    { id: 'pillar_operation', label: '柱4·怎么操作', icon: '⚡',
      prompt: '给出具体的买入/卖出操作建议', apiEndpoint: '/api/invest/four-pillar/operation', apiMethod: 'GET',
      expectedOutcome: '买卖时机 + 仓位比例 + 止损止盈位 + 回撤控制',
      expert: 'invest.investment_analyst', profitImpact: { dimension: 'revenue', amount: '操作纪律化，年化收益提升 5-15%' } },
    // ── 辅助场景 ──
    { id: 'macro_report', label: '全球宏观报告', icon: '📡',
      prompt: '生成全球宏观市场环境报告（含 WorldMonitor 实时数据）', apiEndpoint: '/api/invest/four-pillar/macro-report?include_live_data=true', apiMethod: 'GET',
      expectedOutcome: 'WorldMonitor 7大宏观信号 + 全球市场概览 + GEI/DPI/MEI评分',
      expert: 'invest.investment_analyst', profitImpact: { dimension: 'revenue', amount: '全球视野辅助资产配置，预期增收 10-20%' } },
    { id: 'ai_chain', label: 'AI 产业链', icon: '🤖',
      prompt: '分析 AI 产业链上下游投资机会', apiEndpoint: '/api/invest/chain/spectrum', apiMethod: 'GET',
      expectedOutcome: '六层产业链（算力→基础设施→模型→应用）+ 关键标的 + AI冲击评估',
      expert: 'invest.investment_analyst', profitImpact: { dimension: 'revenue', amount: '发现 AI 产业链低估标的，预期收益 20-50%' } },
    { id: 'four_pillar_dashboard', label: '四柱仪表盘', icon: '📊',
      prompt: '一站式查看四柱投资系统全貌', apiEndpoint: '/api/invest/four-pillar/dashboard', apiMethod: 'GET',
      expectedOutcome: '四柱合一视图：宏观+热点+个股+操作的综合研判',
      expert: 'invest.investment_analyst', profitImpact: { dimension: 'revenue', amount: '一站式决策，研究效率翻 10 倍' } },
  ],
}

export default investmentResearchSolution
