/**
 * 自动拆分自 solution-registry-data.ts。
 * 请勿手工编辑“结构”——如需改方案内容，请直接改本文件字段即可。
 */
import type { SolutionConfig } from '../solution-router'
import { agent } from '../solution-router-agent'

export const lawFirmSolution: SolutionConfig = {
  id: 'law-firm',
  name: '律所智能运营方案',
  icon: '⚖️',
  color: '#3366cc',
  tagline: '同样 5 个律师，年营收翻倍 — 人均创收提升 200%',
  description: '律师 60% 时间花在非创收事务上。MBE 释放这些时间——同样 5 个律师，一年多接 3 倍案件，人均创收翻倍。',
  entrepreneurPurpose: '释放律师 60% 非创收时间，让每个律师年创收翻倍',
  profitMetrics: ['合同审查 16h→2min，每月多接 5-8 案', '文书效率 10 倍提升', '省下一个财务 ≈ 年省 8-12 万'],
  valueEquivalent: { humanHours: 16, mbeMinutes: 2, acceleration: '480x' },
  agents: [
    agent('legal', 8003, '诉讼分析专家', '案例检索、判决预测、诉讼策略'),
    agent('legal', 8003, '合同审查专家', '合同条款审查、风险识别、修改建议'),
    agent('finance', 8002, '律所财务专家', '案件收费、律师提成、税务申报'),
  ],
  localScripts: ['calc_litigation_fee', 'calc_labor_compensation', 'calc_statute'],
  knowledgeCache: ['civil_law_basics', 'contract_law'],
  theme: { primary: '220 65% 50%', accent: '220 65% 50%', sidebarBg: '220 15% 7%' },
  enabledTabs: ['today', 'cases', 'contracts', 'legal-docs', 'billing', 'tools', 'documents', 'chat', 'knowledge-graph'],
  orchestrationProfile: {
    modelStrategy: 'quality_first',
    qaLoop: 'final_deliverables',
    calculatorFirst: true,
    auditTrace: 'required',
    humanApproval: ['法律意见签发', '合同签署建议', '诉讼策略定稿'],
    badges: ['法律专家组协作', '强模型复核', '法条证据链', '人工签发'],
  },
  onboarding: {
    questions: [
      { key: 'firm_size', label: '律所规模', options: ['1-5人', '5-20人', '20-50人', '50人以上'] },
      { key: 'practice_area', label: '主要业务领域', options: ['民商事诉讼', '刑事辩护', '公司法务', '知识产权', '劳动争议', '婚姻家事', '综合'] },
      { key: 'monthly_cases', label: '月均新增案件', options: ['1-5件', '5-15件', '15-30件', '30件以上'] },
    ],
  },
  tools: [
    { id: 'compensation', type: 'calculator', name: '赔偿计算器', icon: '💰',
      agent: 'legal', apiPath: '/api/legal/calc/compensation', localScript: 'calc_labor_compensation',
      fields: [
        { key: 'monthly_salary', label: '月工资（元）', type: 'currency', required: true },
        { key: 'work_years', label: '工作年限', type: 'number', required: true },
        { key: 'dismissal_type', label: '解除类型', type: 'select', required: true,
          options: [
            { value: 'N', label: 'N（协商/裁员）' },
            { value: 'N+1', label: 'N+1（未提前通知）' },
            { value: '2N', label: '2N（违法解除）' },
          ] },
      ],
    },
    { id: 'litigation-fee', type: 'calculator', name: '诉讼费计算器', icon: '⚖️',
      agent: 'legal', apiPath: '/api/legal/calc/litigation-fee', localScript: 'calc_litigation_fee',
      fields: [{ key: 'amount', label: '标的额（元）', type: 'currency', required: true }],
    },
    { id: 'statute-check', type: 'calculator', name: '诉讼时效查询', icon: '⏰',
      agent: 'legal', apiPath: '/api/legal/calc/statute', localScript: 'calc_statute',
      fields: [
        { key: 'case_type', label: '案件类型', type: 'select', required: true,
          options: [
            { value: 'general', label: '一般民事（3年）' },
            { value: 'labor', label: '劳动争议（1年）' },
            { value: 'injury', label: '人身损害（3年）' },
          ] },
        { key: 'start_date', label: '起算日期', type: 'date', required: true },
      ],
    },
    { id: 'contract-review', type: 'document-ai', name: '合同审查', icon: '📋',
      agent: 'legal', apiPath: '/api/legal/ai/contract-review',
      acceptTypes: ['.txt', '.pdf', '.docx', '.jpg', '.png'],
    },
    { id: 'doc-gen', type: 'doc-generator', name: '法律文书生成', icon: '📄',
      agent: 'legal', apiPath: '/api/legal/documents/generate',
      fields: [
        { key: 'type', label: '文书类型', type: 'select', required: true,
          options: [
            { value: 'complaint', label: '起诉状' },
            { value: 'answer', label: '民事答辩状' },
            { value: 'appeal', label: '上诉状' },
            { value: 'lawyer_letter', label: '律师函' },
            { value: 'evidence', label: '证据清单' },
            { value: 'authorization', label: '授权委托书' },
            { value: 'opinion', label: '法律意见书' },
            { value: 'contract', label: '委托代理合同' },
            { value: 'arbitration', label: '仲裁申请书' },
            { value: 'review_report', label: '合同审查报告' },
            { value: 'defense_statement', label: '辩护词' },
            { value: 'bail_application', label: '取保候审申请书' },
          ] },
        { key: 'facts', label: '事实与理由', type: 'textarea', required: true },
      ],
    },
  ],
  slashCommands: [
    { cmd: '/计算', label: '赔偿计算', icon: '💰', toolId: 'compensation' },
    { cmd: '/审查', label: '合同审查', icon: '📋', toolId: 'contract-review' },
    { cmd: '/文书', label: '生成文书', icon: '📄', toolId: 'doc-gen' },
    { cmd: '/诉讼费', label: '诉讼费', icon: '⚖️', toolId: 'litigation-fee' },
    { cmd: '/时效', label: '时效查询', icon: '⏰', toolId: 'statute-check' },
    { cmd: '/案件', label: '案件管理流程', icon: '📂', description: '启动案件全流程' },
    { cmd: '/合规', label: '合规检查', icon: '🛡️', description: '法律+财务+运营三维合规扫描' },
    { cmd: '/转写', label: '庭审转写', icon: '🎙️', description: '录音转写+法律要点提取' },
  ],
  safetyRules: [
    { id: 'conflict-of-interest', label: '利益冲突拦截', trigger: '同一案件涉及律所已代理的对方当事人', action: '阻断并提示利益冲突，需合伙人审批' },
    { id: 'client-privilege', label: '客户保密', trigger: 'AI 回复包含其他客户案件信息或保密材料', action: '拦截回复，提示客户保密义务' },
    { id: 'statute-expiry-alert', label: '时效届满预警', trigger: '案件诉讼时效剩余 ≤ 30 天', action: '红色警告+短信通知主办律师和合伙人' },
    { id: 'fee-cap-check', label: '费率上限检查', trigger: '风险代理费率超过司法部规定上限', action: '提示费率违规并建议调整' },
    { id: 'court-deadline-guard', label: '庭审期限卫士', trigger: '距开庭/答辩/举证期限 ≤ 7 天且未提交', action: '高优先级弹窗，阻断低优先级任务' },
    { id: 'unauthorized-practice', label: '资质管控', trigger: '实习律师/律助独立出具法律意见书', action: '拦截并要求执业律师审批签章' },
  ],
  quickActions: [
    { id: 'new-case', label: '新建案件', icon: '📂', workflowId: 'case_management', description: '录入案件信息，AI 自动定性法律关系并生成初步方案', cta: '新建案件' },
    { id: 'contract-review-quick', label: '合同审查', icon: '📋', workflowId: 'contract_lifecycle', description: '上传合同，2 分钟获得结构化审查报告', cta: '上传审查' },
    { id: 'doc-gen', label: '文书生成', icon: '📝', toolId: 'doc-gen', description: '选择文书类型，AI 起草 12 类法律文书', cta: '生成文书' },
    { id: 'billing-calc', label: '计费结算', icon: '💰', workflowId: 'billing_settlement', description: '汇总工时和费用，一键生成结算单', cta: '生成结算单' },
    { id: 'compliance-scan', label: '合规检查', icon: '🛡️', workflowId: 'compliance_check', description: '法律+财务+运营三维合规并行扫描', cta: '开始检查' },
    { id: 'court-transcribe', label: '庭审转写', icon: '🎙️', workflowId: 'court_transcription', description: '上传录音，10 分钟获得法律要点摘要', cta: '上传录音' },
  ],
  workflows: [
    {
      id: 'case_management', name: '案件管理全流程', icon: '📂',
      description: '输出可直接执行的诉讼方案，含法律分析、证据清单、策略和费用预算',
      mode: 'sequential',
      deliverable: '案件分析报告（法律意见 + 证据清单 + 诉讼策略 + 费用预算）',
      successCriteria: [
        '法律关系定性明确，引用 ≥ 3 条法律条文',
        '证据清单标注每项证据的证明目的和效力等级',
        '诉讼策略含胜诉概率区间和风险预案',
        '费用预算含受理费、律师费、鉴定费等各项明细',
      ],
      steps: [
        { id: 'case_filing', agent: 'legal', expert: 'civil_lawyer', label: '案件立案与事实梳理',
          goal: '定性法律关系，明确诉讼请求',
          successCriteria: ['确定案由', '列出原被告主体信息', '明确管辖法院依据'],
          profitImpact: { dimension: 'revenue', amount: '快速立案缩短周期，每案多赚代理费 0.5-2 万' } },
        { id: 'evidence', agent: 'legal', expert: 'civil_lawyer', label: '证据分析与法律检索',
          goal: '构建完整证据链，检索支撑判例',
          successCriteria: ['每项证据标注证明目的', '标注证据缺口和补救方案', '检索 ≥ 2 个类似判例'],
          profitImpact: { dimension: 'loss_avoidance', amount: '完整证据链提高胜率，避免败诉损失 5-30 万' } },
        { id: 'strategy', agent: 'legal', expert: 'civil_lawyer', label: '诉讼策略制定',
          goal: '输出最优诉讼路径和备选方案',
          successCriteria: ['给出胜诉概率区间', '含调解/仲裁/诉讼三种路径对比', '标注关键时间节点'],
          profitImpact: { dimension: 'revenue', amount: '最优路径节省 30% 时间，年多接 10+ 案件' } },
        { id: 'budget', agent: 'finance', expert: 'finance_accountant', label: '诉讼费用预算',
          goal: '精确计算全部诉讼成本',
          successCriteria: ['受理费按标的额精确计算', '律师费标注计算方式', '含保全费/鉴定费等可能费用'],
          profitImpact: { dimension: 'cost_saving', amount: '精确预算避免垫资风险，每案省 0.5-3 万' } },
      ],
      triggerPhrases: ['新案件', '案件立案', '打官司'],
    },
    {
      id: 'contract_lifecycle', name: '合同全生命周期', icon: '📝',
      description: '输出可直接使用的合同文本，风险已排除、谈判要点已标注',
      mode: 'sequential',
      deliverable: '合同终稿（含风险批注 + 谈判备忘录）',
      successCriteria: [
        '合同要素完整（主体/标的/价款/履行/违约/争议解决）',
        '零高风险条款（或已给出替代文本）',
        '谈判要点含底线和让步空间',
      ],
      steps: [
        { id: 'draft', agent: 'legal', expert: 'civil_lawyer', label: '合同起草/模板选择',
          goal: '生成符合交易场景的合同框架',
          successCriteria: ['覆盖六大必备要素', '条款结构符合行业惯例'],
          profitImpact: { dimension: 'revenue', amount: '合同起草 4h→30min，月多接 8-10 单' } },
        { id: 'review', agent: 'legal', expert: 'civil_lawyer', label: '条款风险审查',
          goal: '识别并消除全部高风险条款',
          successCriteria: ['逐条标注风险等级', '每条高风险给出替代文本', '引用民法典条款号'],
          profitImpact: { dimension: 'loss_avoidance', amount: '零高风险条款通过，避免违约损失 10-50 万' } },
        { id: 'advice', agent: 'legal', expert: 'civil_lawyer', label: '签约建议与谈判要点',
          goal: '输出谈判策略和签约注意事项',
          successCriteria: ['标注可让步条款和底线条款', '含签约前检查清单'],
          profitImpact: { dimension: 'revenue', amount: '谈判策略精准，成交率提升 20%' } },
      ],
      triggerPhrases: ['起草合同', '合同审查', '签合同'],
    },
    {
      id: 'billing_settlement', name: '计费结算流程', icon: '💳',
      description: '工时统计 → 费用计算 → 开票 → 收款，确保律所创收颗粒归仓',
      mode: 'sequential',
      deliverable: '月度计费结算单（含工时明细、费用汇总、开票计划）',
      successCriteria: [
        '工时记录精确到 0.1 小时',
        '费用计算含律师费 + 诉讼费 + 差旅费各项',
        '开票金额和税率正确',
      ],
      steps: [
        { id: 'time_track', agent: 'finance', expert: 'finance_accountant', label: '工时与工作量统计',
          goal: '汇总本月所有案件的可计费工时',
          successCriteria: ['分律师统计工时', '区分可计费/不可计费活动', '标注异常工时'],
          profitImpact: { dimension: 'revenue', amount: '精确计时减少漏计费，月增收 1-3 万' } },
        { id: 'fee_calc', agent: 'finance', expert: 'tax_consultant', label: '费用计算与开票',
          goal: '按合同约定计算各案件应收费用并生成开票计划',
          successCriteria: ['按计时/按标的/风险代理分别计算', '含税金额正确', '标注逾期未收款项'],
          profitImpact: { dimension: 'revenue', amount: '催收+精确计费，月回款提升 10-20%' } },
      ],
      triggerPhrases: ['计费结算', '开票', '律师费', '工时'],
    },
    {
      id: 'court_transcription', name: '庭审录音转写', icon: '🎙️',
      description: '录音本地转写（Whisper）→ 法律要点提取 → 质证摘要生成',
      mode: 'sequential',
      deliverable: '庭审记录（含完整转写文本 + 法律要点提取 + 质证摘要）',
      successCriteria: [
        '转写准确率 ≥ 95%',
        '法律要点提取覆盖原被告全部发言要点',
        '质证摘要标注关键证据和争议焦点',
      ],
      steps: [
        { id: 'transcribe', agent: 'transcribe', expert: 'transcriber', label: '录音转写',
          goal: '将庭审录音转为完整文字记录',
          successCriteria: ['说话人标注', '时间戳标注', '专业术语识别'],
          profitImpact: { dimension: 'cost_saving', amount: '转写效率 8h→15min，每月省 3-5 个工作日' } },
        { id: 'extract', agent: 'legal', expert: 'civil_lawyer', label: '法律要点提取',
          goal: '从转写文本中提取法律争点和关键事实',
          successCriteria: ['覆盖全部争议焦点', '标注举证质证要点', '识别法官关注方向'],
          profitImpact: { dimension: 'revenue', amount: '精准把握法官态度，调整策略提高胜率' } },
      ],
      triggerPhrases: ['庭审转写', '录音转写', '庭审记录'],
    },
    {
      id: 'compliance_check', name: '企业合规检查', icon: '🛡️',
      description: '法律合规 + 数据合规 + 行业监管三维并行扫描，输出合规差距报告',
      mode: 'parallel',
      estimatedTime: { human: '2 天', ai: '20 分钟' },
      aiRate: 85,
      deliverable: '合规差距报告（法律/数据/监管三维 + 整改优先级）',
      successCriteria: ['三维合规全覆盖', '整改项有优先级', '引用具体法规条款'],
      steps: [
        { id: 'legal_comp', agent: 'legal', expert: 'civil_lawyer', label: '法律合规扫描（经营/合同/劳动）' },
        { id: 'data_comp', agent: 'legal', expert: 'civil_lawyer', label: '数据与隐私合规（PIPL/网络安全法）' },
        { id: 'industry_comp', agent: 'legal', expert: 'civil_lawyer', label: '行业监管合规检查' },
      ],
      triggerPhrases: ['企业合规', '合规检查', '数据合规', 'PIPL'],
    },
    {
      id: 'verdict_prediction', name: '判决结果预测', icon: '🔮',
      description: '案件要素分析 → 类案检索 → 胜诉概率 → 判决金额分布 → 谈判数据',
      mode: 'sequential',
      estimatedTime: { human: '1 天', ai: '15 分钟' },
      aiRate: 80,
      deliverable: '判决预测报告（胜诉概率区间 + 金额分布 + 类案对比 + 谈判建议）',
      successCriteria: ['对标 ≥ 5 个类案', '胜诉概率含置信区间', '判决金额分布含中位数'],
      steps: [
        { id: 'elements', agent: 'legal', expert: 'civil_lawyer', label: '案件要素提取与摘要' },
        { id: 'case_search', agent: 'legal', expert: 'civil_lawyer', label: '类案数据库检索' },
        { id: 'probability', agent: 'legal', expert: 'civil_lawyer', label: '胜诉概率与判决金额分布' },
        { id: 'factors', agent: 'legal', expert: 'civil_lawyer', label: '关键影响因素权重分析' },
      ],
      triggerPhrases: ['判决预测', '胜诉概率', '类案分析', '案件评估'],
    },
    {
      id: 'evidence_chain', name: '证据链整理', icon: '🔗',
      description: '证据材料分类 → 证据×待证事实矩阵 → 证明力评估 → 缺口识别与补证建议',
      mode: 'sequential',
      estimatedTime: { human: '4 小时', ai: '10 分钟' },
      aiRate: 85,
      deliverable: '证据体系分析报告（证据清单 + 对应矩阵 + 证明力评估 + 补证建议）',
      successCriteria: ['证据清单含证明目的和效力等级', '缺口识别具体', '补证方案可执行'],
      steps: [
        { id: 'catalog', agent: 'legal', expert: 'civil_lawyer', label: '证据材料分类与清单' },
        { id: 'matrix', agent: 'legal', expert: 'civil_lawyer', label: '证据×待证事实对应矩阵' },
        { id: 'strength', agent: 'legal', expert: 'civil_lawyer', label: '证明力评估与缺口识别' },
      ],
      triggerPhrases: ['证据整理', '证据链', '证据分析', '举证'],
    },
    {
      id: 'dispute_handling', name: '纠纷处理流程', icon: '⚖️',
      description: '事实认定 → 法律分析 → 补偿计算 → 应对策略（非诉/仲裁/诉讼路径）',
      mode: 'sequential',
      estimatedTime: { human: '1 天', ai: '30 分钟' },
      aiRate: 75,
      deliverable: '纠纷处理方案（事实认定 + 法律意见 + 赔偿金额 + 路径选择）',
      successCriteria: ['法律关系定性准确', '赔偿金额含计算过程', '路径选择含成本对比'],
      steps: [
        { id: 'facts', agent: 'legal', expert: 'civil_lawyer', label: '事实认定与法律关系定性' },
        { id: 'analysis', agent: 'legal', expert: 'civil_lawyer', label: '法律分析与责任判定' },
        { id: 'calc', agent: 'finance', expert: 'tax_consultant', label: '补偿/赔偿金额计算' },
        { id: 'strategy', agent: 'legal', expert: 'civil_lawyer', label: '应对策略（非诉/仲裁/诉讼）' },
      ],
      triggerPhrases: ['纠纷处理', '纠纷解决', '争议处理', '调解'],
    },
    {
      id: 'deadline_track', name: '期限与时效追踪', icon: '⏱️',
      description: 'OCR 提取关键日期 → 诉讼时效计算 → 分级预警 → 律师推送提醒',
      mode: 'sequential',
      estimatedTime: { human: '2 小时', ai: '5 分钟' },
      aiRate: 90,
      deliverable: '期限追踪报告（关键日期清单 + 时效计算 + 风险评级 + 提醒计划）',
      successCriteria: ['关键日期提取完整', '时效计算引用适用法条', '高风险项红色标注'],
      steps: [
        { id: 'extract', agent: 'legal', expert: 'civil_lawyer', label: 'OCR/文本提取关键日期' },
        { id: 'calc', agent: 'legal', expert: 'civil_lawyer', label: '诉讼时效计算（普通3年/特殊1年）' },
        { id: 'alert', agent: 'legal', expert: 'civil_lawyer', label: '分级预警与律师提醒推送' },
      ],
      triggerPhrases: ['时效追踪', '期限提醒', '诉讼时效', '截止日期'],
    },
    {
      id: 'severance_calc', name: '劳动赔偿计算', icon: '💰',
      description: 'N/N+1/2N 类型判定 → 基数与年限精确计算 → 附加项叠加 → 律师谈判数据',
      mode: 'sequential',
      estimatedTime: { human: '1 小时', ai: '3 分钟' },
      aiRate: 95,
      deliverable: '劳动赔偿计算报告（类型判定 + 精确金额 + 附加项 + 谈判区间）',
      successCriteria: ['适用类型判定有法规依据', '金额计算过程透明', '含谈判底线和合理区间'],
      steps: [
        { id: 'type', agent: 'legal', expert: 'civil_lawyer', label: '赔偿类型判定（N/N+1/2N）' },
        { id: 'calc', agent: 'finance', expert: 'tax_consultant', label: '核心赔偿金精确计算' },
        { id: 'extra', agent: 'legal', expert: 'civil_lawyer', label: '附加项叠加（代通知金/年假/社保）' },
      ],
      triggerPhrases: ['劳动赔偿', 'N+1计算', '2N赔偿', '离职赔偿'],
    },
    {
      id: 'risk_assessment', name: '法律风险评估', icon: '🔍',
      description: '合同/经营/诉讼/合规四维法律风险并行扫描，输出优先级排序整改方案',
      mode: 'parallel',
      estimatedTime: { human: '2 天', ai: '25 分钟' },
      aiRate: 80,
      deliverable: '法律风险评估报告（四维风险矩阵 + 优先级 + 整改建议）',
      successCriteria: ['四维覆盖完整', '风险按高/中/低分级', '每项高风险给出整改路径'],
      steps: [
        { id: 'contract_risk', agent: 'legal', expert: 'civil_lawyer', label: '合同法律风险扫描' },
        { id: 'operation_risk', agent: 'legal', expert: 'civil_lawyer', label: '经营合规风险扫描' },
        { id: 'litigation_risk', agent: 'legal', expert: 'civil_lawyer', label: '诉讼与债权风险评估' },
      ],
      triggerPhrases: ['法律风险', '风险评估', '法律体检', '合规风险'],
    },
  ],
  scenarios: [
    { id: 'case_assess', label: '案件胜率评估', icon: '⚖️', prompt: '评估这个案件的胜诉概率和风险', expectedOutcome: '胜诉概率区间 + 关键风险点 + 证据强弱分析', expert: 'legal.civil_lawyer', profitImpact: { dimension: 'revenue', amount: '精选高胜率案件，月增收 5-15 万' } },
    { id: 'demand_letter', label: '律师函起草', icon: '📄', prompt: '根据以下情况起草一份律师函', expectedOutcome: '可直接发送的律师函全文 + 法律依据', expert: 'legal.civil_lawyer', profitImpact: { dimension: 'revenue', amount: '文书效率 10 倍提升，每月多接 3-5 份' } },
    { id: 'statute_check', label: '诉讼时效查询', icon: '⏰', prompt: '查询这个案件的诉讼时效', expectedOutcome: '适用时效年限 + 起算日期 + 剩余天数 + 中断/中止情形', expert: 'legal.civil_lawyer', profitImpact: { dimension: 'loss_avoidance', amount: '避免超时效丧失诉权，挽回标的 5-50 万' } },
    { id: 'case_cost', label: '诉讼费估算', icon: '💰', prompt: '估算这个案件的全部诉讼成本', expectedOutcome: '受理费 + 律师费 + 鉴定费等各项明细金额', workflowId: 'case_management', profitImpact: { dimension: 'cost_saving', amount: '精准费用预算，避免超支 1-5 万' } },
    { id: 'court_transcribe', label: '庭审录音转写', icon: '🎙️', prompt: '上传庭审录音，本地转写并提取法律要点', expectedOutcome: '完整转写文本 + 争议焦点 + 质证摘要', workflowId: 'court_transcription', profitImpact: { dimension: 'cost_saving', amount: '转写效率 8h→15min，月省 3-5 个工作日' } },
  ],
}

export default lawFirmSolution
