/**
 * OEM 制造业方案 — Desktop 配置
 * 对应 solutions/oem-manufacturing/solution.yaml v0.1.0
 * 按规模分层：SMB（中小代工厂）/ 成长期（100-500人）/ 上市期（A/H股上市企业）
 */
import type { SolutionConfig } from '../solution-router'
import { agent } from '../solution-router-agent'

export const oemManufacturingSolution: SolutionConfig = {
  id: 'oem-manufacturing',
  name: 'OEM 制造业方案',
  icon: '🏭',
  color: '#64748b',
  tagline: '从代工厂到上市企业，法务+财务+HR+销售+客服五岗 AI 化，合规风险降 80%',
  description: '替代法务+财务+HR+销售+客服五个岗位，OEM 合同保护、出口退税、工厂用工合规、大客户销售、品质索赔、上市合规全周期覆盖。',
  entrepreneurPurpose: '替代法务+财务+HR+销售+客服五个岗位，合规风险降 80%，人力成本降 60%',
  profitMetrics: [
    'OEM 合同审查 ¥5/份（律所 5000 元），节省 99.9%',
    '出口退税申报 ¥50/月（代理记账 2000 元），节省 97.5%',
    '研发加计扣除逐项归集，平均多退税 18-35 万/年',
  ],
  valueEquivalent: { humanHours: 240, mbeMinutes: 15, acceleration: '960x' },
  agents: [
    agent('legal',   8003, '企业法务', 'OEM合同+供应商协议+IP保护+劳动法'),
    agent('finance', 8002, '企业财务', '出口退税+研发加计扣除+成本核算+增值税'),
    agent('hr',      8010, '人力资源', '工厂用工合规+工伤赔偿+绩效管理'),
    agent('sales',   8008, '销售顾问', '大客户BANT+报价策略+竞品分析'),
    agent('cs',      8004, '客服管理', '品质索赔+售后投诉+SLA管理'),
    agent('invest',  8011, '投资分析', '关联交易合规+股权激励+AI披露+年报'),
  ],
  localScripts: ['calc_iit', 'calc_vat', 'calc_export_rebate', 'calc_litigation_fee'],
  knowledgeCache: ['oem_tax_export', 'oem_labor_rules'],
  theme: { primary: '215 16% 47%', accent: '215 16% 47%', sidebarBg: '215 10% 8%' },
  enabledTabs: ['chat', 'tools', 'workflows', 'dashboard', 'knowledge-graph'],
  onboarding: {
    questions: [
      { key: 'company_tier', label: '企业规模', options: ['中小代工厂（<100人）', '成长型制造企业（100-500人）', '上市制造企业（500人以上）'] },
      { key: 'industry_sub', label: '细分行业', options: ['汽车零部件', '电子制造/EMS', '机械装备', '精密零件/模具', '其他 OEM/ODM'] },
      { key: 'export_ratio', label: '出口占比', options: ['<20%（以内销为主）', '20-60%（内外销并重）', '>60%（以出口为主）'] },
    ],
  },
  tools: [
    {
      id: 'export-rebate-calc', type: 'calculator', name: '出口退税计算器', icon: '🚢',
      agent: 'finance', apiPath: '/api/finance/calc/export-rebate',
      description: '免抵退税额计算（适用生产型出口企业）',
      fields: [
        { key: 'export_amount', label: '出口销售额（元）', type: 'currency', required: true },
        { key: 'rebate_rate', label: '退税率（%）', type: 'select', required: true,
          options: [
            { value: '0.13', label: '13%（标准税率货物）' },
            { value: '0.09', label: '9%（农产品/部分机械）' },
            { value: '0.06', label: '6%（部分劳动密集型）' },
          ] },
        { key: 'input_tax', label: '进项税额（元）', type: 'currency', required: true },
        { key: 'non_deductible', label: '不得抵扣进项税（元）', type: 'currency', default: 0 },
      ],
    },
    {
      id: 'injury-compensation', type: 'calculator', name: '工伤赔偿计算', icon: '⛑️',
      agent: 'hr', apiPath: '/api/hr/calc/injury-compensation',
      description: '工伤伤残等级赔偿金额计算（含社保部分）',
      fields: [
        { key: 'monthly_salary', label: '月工资（元）', type: 'currency', required: true },
        { key: 'disability_level', label: '伤残等级', type: 'select', required: true,
          options: [
            { value: '1', label: '一级（最重）' }, { value: '2', label: '二级' },
            { value: '3', label: '三级' }, { value: '4', label: '四级' },
            { value: '5', label: '五级' }, { value: '6', label: '六级' },
            { value: '7', label: '七级' }, { value: '8', label: '八级' },
            { value: '9', label: '九级' }, { value: '10', label: '十级（最轻）' },
          ] },
        { key: 'work_years', label: '工作年限（年）', type: 'number', required: true },
      ],
    },
    {
      id: 'overtime-calc', type: 'calculator', name: '加班费计算器', icon: '⏰',
      agent: 'hr', apiPath: '/api/hr/calc/overtime',
      description: '工作日/休息日/法定假日加班工资计算',
      fields: [
        { key: 'monthly_salary', label: '月工资（元）', type: 'currency', required: true },
        { key: 'overtime_type', label: '加班类型', type: 'select', required: true,
          options: [
            { value: 'workday', label: '工作日延长（1.5倍）' },
            { value: 'weekend', label: '休息日（2倍）' },
            { value: 'holiday', label: '法定节假日（3倍）' },
          ] },
        { key: 'overtime_hours', label: '加班小时数', type: 'number', required: true },
      ],
    },
    {
      id: 'severance-calc', type: 'calculator', name: '经济补偿金计算', icon: '💼',
      agent: 'legal', apiPath: '/api/legal/calc/severance',
      description: 'N / N+1 / 2N 经济补偿金/赔偿金计算',
      fields: [
        { key: 'monthly_salary', label: '月工资（元）', type: 'currency', required: true },
        { key: 'work_years', label: '工作年限（年）', type: 'number', required: true },
        { key: 'termination_type', label: '离职类型', type: 'select', required: true,
          options: [
            { value: 'n', label: 'N（协商解除/不可归责）' },
            { value: 'n1', label: 'N+1（代通知金）' },
            { value: '2n', label: '2N（违法解除赔偿金）' },
          ] },
      ],
    },
    {
      id: 'rd-deduction-calc', type: 'calculator', name: '研发加计扣除测算', icon: '🔬',
      agent: 'finance', apiPath: '/api/finance/calc/rd-deduction',
      description: '研发费用加计扣除节税额计算（100% 加计比例）',
      fields: [
        { key: 'rd_expense', label: '符合条件的研发费用（元）', type: 'currency', required: true },
        { key: 'enterprise_type', label: '企业类型', type: 'select', required: true,
          options: [
            { value: 'general', label: '一般企业（加计100%）' },
            { value: 'hnte', label: '高新技术企业（加计100%，税率15%）' },
            { value: 'sme', label: '科技型中小企业（加计100%）' },
          ] },
        { key: 'profit_amount', label: '应纳税所得额（元）', type: 'currency', required: true },
      ],
    },
  ],
  slashCommands: [
    { cmd: '/退税', label: '出口退税计算', icon: '🚢', toolId: 'export-rebate-calc' },
    { cmd: '/工伤', label: '工伤赔偿计算', icon: '⛑️', toolId: 'injury-compensation' },
    { cmd: '/加班费', label: '加班费计算', icon: '⏰', toolId: 'overtime-calc' },
    { cmd: '/赔偿', label: '经济补偿金', icon: '💼', toolId: 'severance-calc' },
    { cmd: '/研发', label: '研发加计扣除', icon: '🔬', toolId: 'rd-deduction-calc' },
    { cmd: '/合同', label: 'OEM 合同审查', icon: '📋' },
  ],
  safetyRules: [
    { id: 'export-rebate-deadline', label: '退税申报截止预警', trigger: '距出口退税申报截止日 ≤ 5 天且未完成', action: '红色预警，推送通知财务，置顶退税任务' },
    { id: 'injury-report-deadline', label: '工伤申报时效提醒', trigger: '工伤事故发生后 ≥ 24 小时未触发工伤申报', action: '提示 30 日申报时效，自动生成申报材料清单' },
    { id: 'oem-ip-alert', label: 'OEM 合同 IP 条款缺失', trigger: 'OEM 合同未约定技术图纸/模具知识产权归属', action: '标记高风险，强制触发 IP 条款审查' },
    { id: 'large-contract-dual-review', label: '大额合同双审', trigger: '合同金额超过月均营收 30%', action: '触发 Legal + Finance 双审，不得跳过' },
    { id: 'labor-contract-unsigned', label: '超期未签劳动合同', trigger: '用工超过 1 个月未签书面合同', action: '警告双倍工资风险，推送签约任务' },
    { id: 'listed-related-tx', label: '关联交易阈值预警', trigger: '关联交易金额超过最近一期净资产 1%', action: '触发关联交易合规审查工作流（上市层）' },
  ],
  quickActions: [
    { id: 'oem-contract', label: 'OEM 合同快审', icon: '📋', workflowId: 'oem_contract_review',
      description: '上传代工协议，8 分钟获得 IP/模具/付款风险报告', cta: '上传审查' },
    { id: 'export-rebate', label: '出口退税申报', icon: '🚢', workflowId: 'export_tax_rebate',
      description: '录入出口数据，AI 自动计算免抵退税额并生成申报表', cta: '开始申报' },
    { id: 'factory-compliance', label: '用工合规体检', icon: '🏭', workflowId: 'workforce_compliance',
      description: '输入工厂用工情况，AI 识别违法风险+生成整改方案', cta: '开始体检' },
    { id: 'rd-deduction', label: '研发加计扣除', icon: '🔬', workflowId: 'rd_expense_deduction',
      description: '提交研发费用明细，AI 归集口径+计算节税额', cta: '开始测算' },
    { id: 'ka-lifecycle', label: '大客户管理', icon: '🤝', workflowId: 'ka_customer_lifecycle',
      description: '输入客户信息，AI 生成报价策略+异议话术+服务 SLA', cta: '开始分析' },
    { id: 'related-tx', label: '关联交易审查', icon: '⚖️', workflowId: 'listed_related_transaction',
      description: '录入交易信息，AI 判断披露义务并生成公告草稿', cta: '开始审查' },
  ],
  workflows: [
    {
      id: 'oem_contract_review', name: 'OEM 代工协议审查', icon: '📋',
      description: '合同要素完整性 → IP/模具条款 → 付款与违约责任 → 税务影响分析',
      mode: 'sequential',
      deliverable: 'OEM 合同风险报告（IP 归属 + 模具费 + 违约责任 + 税务影响 + 修改建议）',
      successCriteria: ['IP 归属条款明确标注', '最大潜在损失量化', '修改建议可操作'],
      steps: [
        { id: 'completeness', agent: 'legal', expert: 'contract_reviewer', label: 'OEM 合同要素完整性检查',
          goal: '验证合同必备条款是否齐全',
          successCriteria: ['主体/标的/价格/交付/质保全部核查', '缺失条款清单'],
          profitImpact: { dimension: 'loss_avoidance', amount: '律所 5000 元/份 → ¥5/份，省 99.9%' } },
        { id: 'ip_review', agent: 'legal', expert: 'contract_reviewer', label: '模具费/IP 归属/保密条款',
          goal: '识别技术图纸、模具、工艺知识产权风险',
          successCriteria: ['IP 归属明确', '保密范围合理', '竞业条款无过度限制'],
          profitImpact: { dimension: 'loss_avoidance', amount: '防止模具/IP 被客户控制，每单潜在损失 50-500 万' } },
        { id: 'payment_risk', agent: 'legal', expert: 'contract_reviewer', label: '付款条款与违约责任',
          goal: '识别不合理付款周期和违约金设置',
          successCriteria: ['账期风险量化', '违约金比例符合法律上限 30%', '最大损失估算'],
          profitImpact: { dimension: 'loss_avoidance', amount: '账期陷阱识别，减少呆账风险' } },
        { id: 'tax_impact', agent: 'finance', expert: 'tax_consultant', label: '税务影响分析',
          goal: '分析合同结构对增值税/印花税的影响',
          successCriteria: ['增值税开票金额确认', '印花税计税依据明确', '税务优化建议'],
          profitImpact: { dimension: 'cost_saving', amount: '优化合同结构，合理降低税负' } },
        { id: 'confirm', agent: 'legal', expert: 'contract_reviewer', label: '管理层确认签约（HITL）',
          mode: 'human_in_loop',
          goal: '管理层审核并确认签约决定',
          profitImpact: { dimension: 'loss_avoidance', amount: '双审机制避免重大合同风险' } },
      ],
      triggerPhrases: ['OEM 合同', '代工协议', '采购合同', '供应商合同'],
    },
    {
      id: 'export_tax_rebate', name: '出口退税申报', icon: '🚢',
      description: '出口明细核对 → 免抵退税额计算 → 进项税额转出 → 申报表生成',
      mode: 'sequential',
      deliverable: '出口退税申报报告（免抵退税额 + 进项转出金额 + 申报表草稿）',
      successCriteria: ['退税率对应正确险种', '进项转出计算无误', '申报表格式符合税务系统'],
      steps: [
        { id: 'export_check', agent: 'finance', expert: 'tax_consultant', label: '出口明细与退税率核对',
          goal: '确认各商品 HS 编码对应的退税率',
          successCriteria: ['退税率逐项核对', '异常商品标注'],
          profitImpact: { dimension: 'revenue', amount: '精准退税率，不少退一分钱' } },
        { id: 'calc', agent: 'finance', expert: 'finance_accountant', label: '免抵退税额计算',
          goal: '按公式计算应退税额和免抵税额',
          successCriteria: ['免抵退税不得免征和抵扣税额计算正确', '应退税额有核查'],
          profitImpact: { dimension: 'revenue', amount: '代理记账 2000 元/月 → ¥50/月' } },
        { id: 'transfer_out', agent: 'finance', expert: 'finance_accountant', label: '进项税额转出处理',
          goal: '计算不得抵扣的进项税额转出金额',
          successCriteria: ['转出金额计算正确', '会计分录建议'],
          profitImpact: { dimension: 'cost_saving', amount: '准确转出避免税务风险' } },
        { id: 'declaration', agent: 'finance', expert: 'finance_accountant', label: '申报表生成',
          goal: '生成出口退税申报表草稿',
          successCriteria: ['格式符合国家税务总局标准', '数据逻辑自洽'],
          profitImpact: { dimension: 'cost_saving', amount: '申报从 2 天 → 20 分钟' } },
        { id: 'confirm', agent: 'finance', expert: 'finance_accountant', label: '财务确认申报（HITL）',
          mode: 'human_in_loop',
          goal: '财务人员确认数据后提交申报',
          profitImpact: { dimension: 'loss_avoidance', amount: 'HITL 确认避免申报错误被税务处罚' } },
      ],
      triggerPhrases: ['出口退税', '免抵退', '进项转出', '退税申报'],
    },
    {
      id: 'workforce_compliance', name: '工厂用工合规审查', icon: '🏭',
      description: '劳动合同检查 → 倒班/加班合规 → 工伤赔偿测算 → 违规风险整改',
      mode: 'parallel',
      deliverable: '工厂用工合规报告（违规清单 + 整改优先级 + 赔偿金额估算）',
      successCriteria: ['三维并行覆盖全面', '违规风险按严重程度分级', '整改方案可操作'],
      steps: [
        { id: 'contract_check', agent: 'hr', expert: 'hr_consultant', label: '劳动合同签订合规检查',
          goal: '检查合同签订率和条款合规性',
          successCriteria: ['超期未签名单', '合同条款违规标注'],
          profitImpact: { dimension: 'loss_avoidance', amount: '避免双倍工资风险，100人工厂潜在风险 50-100 万' } },
        { id: 'shift_check', agent: 'hr', expert: 'hr_consultant', label: '倒班/加班制度合法性',
          goal: '评估工时制度是否符合劳动法',
          successCriteria: ['综合计时制/标准工时制判断', '月加班上限 36 小时核查', '三种加班类型识别'],
          profitImpact: { dimension: 'loss_avoidance', amount: '规范加班制度，避免群体性劳动纠纷' } },
        { id: 'injury_calc', agent: 'legal', expert: 'civil_lawyer', label: '工伤赔偿基数计算',
          goal: '测算各伤残等级对应的公司赔偿金额',
          successCriteria: ['赔偿金额分级测算', '社保赔付部分区分', '公司实际承担金额明确'],
          profitImpact: { dimension: 'loss_avoidance', amount: '律师 3000 元/案 → ¥5/次，省 99.8%' } },
        { id: 'risk_list', agent: 'hr', expert: 'hr_consultant', label: '违规风险清单与整改',
          goal: '汇总所有合规风险并生成整改方案',
          successCriteria: ['风险按 P0/P1/P2 分级', '整改时间表', 'HR 负责人任务分配'],
          profitImpact: { dimension: 'loss_avoidance', amount: '系统性合规，每年规避劳动纠纷损失 10-100 万' } },
        { id: 'confirm', agent: 'hr', expert: 'hr_consultant', label: 'HR 负责人确认整改（HITL）',
          mode: 'human_in_loop',
          goal: 'HR 负责人确认整改方案并排期',
          profitImpact: { dimension: 'loss_avoidance', amount: 'HITL 确认确保整改切实执行' } },
      ],
      triggerPhrases: ['用工合规', '工伤', '加班', '倒班', '劳动合规'],
    },
    {
      id: 'rd_expense_deduction', name: '研发费用加计扣除', icon: '🔬',
      description: '研发立项合规 → 费用归集口径 → 加计扣除额测算 → 台账建立 → 汇算清缴',
      mode: 'sequential',
      deliverable: '研发加计扣除报告（合规研发项目清单 + 可加计金额 + 节税额 + 申报指南）',
      successCriteria: ['研发项目合规认定完整', '费用归集口径准确', '节税额有计算依据'],
      steps: [
        { id: 'project_qualify', agent: 'finance', expert: 'tax_consultant', label: '研发项目立项合规核查',
          goal: '判断哪些项目符合加计扣除条件',
          successCriteria: ['符合/不符合项目分类', '立项文件缺失清单'],
          profitImpact: { dimension: 'revenue', amount: '平均为制造企业多申报研发费 20-40%' } },
        { id: 'expense_collection', agent: 'finance', expert: 'finance_accountant', label: '研发费用归集',
          goal: '按六类归集口径整理研发支出',
          successCriteria: ['人员薪酬/折旧/材料/委外各类齐全', '不可归集项目剔除'],
          profitImpact: { dimension: 'revenue', amount: '准确归集，平均多退税 18-35 万/年' } },
        { id: 'deduction_calc', agent: 'finance', expert: 'tax_consultant', label: '加计扣除额测算',
          goal: '计算实际可加计扣除金额和节税效果',
          successCriteria: ['加计扣除额（100%比例）', '节税额 = 加计额 × 适用税率', '与上年对比'],
          profitImpact: { dimension: 'revenue', amount: '节税额直接增加净利润' } },
        { id: 'ledger', agent: 'finance', expert: 'finance_accountant', label: '台账建立与维护',
          goal: '建立研发费用专项台账，满足税务检查要求',
          successCriteria: ['台账格式符合国家税务总局要求', '项目/人员/费用三维记录'],
          profitImpact: { dimension: 'loss_avoidance', amount: '台账完整避免税务稽查风险' } },
        { id: 'confirm', agent: 'finance', expert: 'tax_consultant', label: '汇算清缴确认（HITL）',
          mode: 'human_in_loop',
          goal: '财务负责人确认研发费用申报数据',
          profitImpact: { dimension: 'loss_avoidance', amount: 'HITL 确认避免虚假申报风险' } },
      ],
      triggerPhrases: ['研发加计', '研发费用', '加计扣除', '高新技术'],
    },
    {
      id: 'rd_project_initiation', name: '研发立项报告', icon: '📋',
      description: '技术可行性 → 研发费用预算与加计扣除测算 → 合规性与资本化判断',
      mode: 'sequential',
      deliverable: '研发立项报告（技术目标 + 费用预算 + 加计扣除测算 + 立项合规凭证）',
      successCriteria: ['立项目标清晰可量化', '费用预算分类符合归集口径', '资本化/费用化判断有依据'],
      steps: [
        { id: 'tech_feasibility', agent: 'finance', expert: 'tax_consultant', label: '技术可行性与目标设定',
          goal: '确认研发目标和技术路径可行性',
          profitImpact: { dimension: 'revenue', amount: '立项报告是加计扣除台账必备凭证' } },
        { id: 'budget_rd', agent: 'finance', expert: 'finance_accountant', label: '研发费用预算与加计测算',
          goal: '按六类归集口径做预算，测算加计扣除节税额',
          profitImpact: { dimension: 'revenue', amount: '预算精准，最大化加计扣除额' } },
        { id: 'compliance', agent: 'legal', expert: 'civil_lawyer', label: '合规性与资本化判断（HITL）',
          mode: 'human_in_loop',
          goal: '确认立项文件完整且资本化/费用化处理正确',
          profitImpact: { dimension: 'loss_avoidance', amount: '合规立项避免税务稽查否定加计扣除' } },
      ],
      triggerPhrases: ['研发立项', '立项报告', '研发项目申请'],
    },
    {
      id: 'rd_tech_spec_generation', name: '技术规格书生成', icon: '📐',
      description: '客户需求解析 → 成本与质量条款 → 法律条款审查',
      mode: 'sequential',
      deliverable: '技术规格书草稿（技术参数 + 质量标准 + 法律条款 + 偏差说明）',
      successCriteria: ['客户需求完整映射', '质量标准可测量', '法律条款无重大风险'],
      steps: [
        { id: 'requirement', agent: 'sales', expert: 'sales_consultant', label: '客户需求解析',
          goal: '将客户非结构化需求转化为可执行技术规格',
          profitImpact: { dimension: 'revenue', amount: '快速出规格书，报价响应速度提升 80%' } },
        { id: 'cost_quality', agent: 'finance', expert: 'finance_accountant', label: '成本与质量条款',
          goal: '核算规格对应成本，确认质量条款合理性',
          profitImpact: { dimension: 'revenue', amount: '成本清晰支撑报价决策' } },
        { id: 'legal_review', agent: 'legal', expert: 'contract_reviewer', label: '法律条款审查（HITL）',
          mode: 'human_in_loop',
          goal: '审查技术规格书中的法律风险条款',
          profitImpact: { dimension: 'loss_avoidance', amount: '规格书法律风险提前识别' } },
      ],
      triggerPhrases: ['技术规格书', '产品规格书', 'tech spec', '规格书生成'],
    },
    {
      id: 'esop_management', name: 'ESOP 期权池管理', icon: '💼',
      description: '期权池规模 → 归属计划 → 行权税务 → 授权文件 → 409A 估值',
      mode: 'sequential',
      deliverable: 'ESOP 方案报告（期权池规模 + 归属计划 + 递延纳税方案 + 授权协议关键条款）',
      successCriteria: ['期权池稀释比例合理', '归属计划符合激励目的', '递延纳税资格核查完整'],
      steps: [
        { id: 'pool_sizing', agent: 'finance', expert: 'tax_consultant', label: '期权池规模设计',
          goal: '确定期权池占总股本比例和分批授予节奏',
          profitImpact: { dimension: 'revenue', amount: '精准设计激励池，最大化激励效果' } },
        { id: 'vesting', agent: 'legal', expert: 'civil_lawyer', label: '归属计划制定',
          goal: '设计 Cliff + Vesting 归属计划',
          profitImpact: { dimension: 'revenue', amount: '归属计划绑定核心员工' } },
        { id: 'tax_arrange', agent: 'finance', expert: 'tax_consultant', label: '行权税务安排（财税[2016]101号）',
          goal: '评估递延纳税资格，测算税负对比',
          profitImpact: { dimension: 'cost_saving', amount: '递延纳税从综合税率 45% → 固定 20%，员工税负大幅降低' } },
        { id: 'grant_doc', agent: 'legal', expert: 'civil_lawyer', label: '授权协议生成',
          goal: '生成授权协议关键条款框架',
          profitImpact: { dimension: 'loss_avoidance', amount: '条款完整避免后续纠纷' } },
        { id: 'valuation', agent: 'finance', expert: 'tax_consultant', label: '409A/公允价值确认（HITL）',
          mode: 'human_in_loop',
          goal: '确认行权价参考估算，决策是否委托正式 409A',
          profitImpact: { dimension: 'loss_avoidance', amount: '合规行权价避免税务争议' } },
      ],
      triggerPhrases: ['ESOP', '期权池', '股权激励', '归属计划', '期权授予'],
    },
    {
      id: 'equity_incentive_tax', name: '股权激励递延纳税', icon: '📊',
      description: '工具类型判断 → 财税101号资格核查 → 税额测算 → 备案 → 个税申报',
      mode: 'sequential',
      deliverable: '递延纳税方案（资格判断 + 两方案税负对比 + 备案材料清单 + 申报模板）',
      successCriteria: ['资格核查逐项完整', '税负差异量化', '备案材料清单可操作'],
      steps: [
        { id: 'classify', agent: 'finance', expert: 'tax_consultant', label: '激励工具类型判断',
          goal: '区分股票期权/限制性股票/员工持股计划',
          profitImpact: { dimension: 'cost_saving', amount: '正确工具选择影响数百万税负差异' } },
        { id: 'qualify', agent: 'finance', expert: 'tax_consultant', label: '递延纳税资格核查（财税101号）',
          goal: '逐项核查六大资格条件',
          profitImpact: { dimension: 'cost_saving', amount: '通过资格核查即可锁定 20% 税率' } },
        { id: 'tax_calc', agent: 'finance', expert: 'tax_consultant', label: '税额对比测算',
          goal: '普通纳税 vs 递延纳税税负差异量化',
          profitImpact: { dimension: 'cost_saving', amount: '递延纳税通常节税 30-50%' } },
        { id: 'register', agent: 'finance', expert: 'tax_consultant', label: '主管税务机关备案',
          goal: '生成备案材料清单，提示 15 日时限',
          profitImpact: { dimension: 'loss_avoidance', amount: '逾期备案丧失递延纳税资格' } },
        { id: 'iit_declare', agent: 'finance', expert: 'tax_consultant', label: '员工个税申报（HITL）',
          mode: 'human_in_loop',
          goal: '财务确认员工个税申报数据',
          profitImpact: { dimension: 'loss_avoidance', amount: '准确申报避免补税+滞纳金风险' } },
      ],
      triggerPhrases: ['递延纳税', '财税101', '股权激励个税', '限制性股票', '期权行权税'],
    },
    {
      id: 'rd_failure_analysis_8d', name: '8D 失效分析报告', icon: '🔍',
      description: '问题收集与遏制 → 根因分析 → 纠正措施 → 索赔金额与法律责任',
      mode: 'sequential',
      deliverable: '8D 失效分析报告（D1-D8 完整 + 根因分析 + 索赔法律意见）',
      successCriteria: ['8D 八个步骤均有完整输出', '根因用 5-Why 或鱼骨图支撑', '索赔金额有法律依据'],
      steps: [
        { id: 'problem_contain', agent: 'cs', expert: 'cs_consultant', label: 'D1-D3 问题收集与遏制措施',
          goal: '快速评估问题影响范围并建立遏制措施',
          profitImpact: { dimension: 'loss_avoidance', amount: '快速遏制减少不良品扩散损失' } },
        { id: 'root_cause', agent: 'cs', expert: 'cs_consultant', label: 'D4-D5 根因分析与纠正措施',
          goal: '5-Why/鱼骨图根因分析，制定纠正措施',
          profitImpact: { dimension: 'loss_avoidance', amount: '根因消除防止重复发生' } },
        { id: 'legal_liability', agent: 'legal', expert: 'civil_lawyer', label: '索赔金额与法律责任（HITL）',
          mode: 'human_in_loop',
          goal: '评估法律责任范围，确认索赔应对策略',
          profitImpact: { dimension: 'loss_avoidance', amount: '法律分析降低不合理索赔损失 20-50 万' } },
      ],
      triggerPhrases: ['8D', '失效分析', '品质索赔', '不良品', '质量事故'],
    },
    {
      id: 'ka_customer_lifecycle', name: '大客户全生命周期', icon: '🤝',
      description: 'BANT 认定 → 竞品差异化 → 报价策略 → 异议处理 → 合同签后 SLA',
      mode: 'sequential',
      deliverable: '大客户销售方案（BANT 报告 + 报价策略 + 异议话术 + 服务 SLA）',
      successCriteria: ['BANT 四维均有评估', '报价策略含底价边界', '异议话术直接可用'],
      steps: [
        { id: 'bant', agent: 'sales', expert: 'sales_strategist', label: '客户 BANT 资格认定',
          goal: '评估客户预算/权力/需求/时间线',
          profitImpact: { dimension: 'revenue', amount: '精准 BANT 过滤，销售效率提升 3 倍' } },
        { id: 'competitive', agent: 'sales', expert: 'sales_consultant', label: '竞品对比与差异化价值',
          goal: '识别对标竞争对手，建立差异化话术',
          profitImpact: { dimension: 'revenue', amount: '差异化定位支撑溢价 5-15%' } },
        { id: 'quote', agent: 'finance', expert: 'finance_accountant', label: '报价策略与底价边界',
          goal: '基于成本测算建立价格空间和底线',
          profitImpact: { dimension: 'revenue', amount: '成本透明化让步有据，避免无效让价' } },
        { id: 'objection', agent: 'sales', expert: 'sales_consultant', label: '异议处理话术生成',
          goal: '针对价格/竞品/交期异议生成标准应对话术',
          profitImpact: { dimension: 'revenue', amount: '标准话术提升成交率 20-30%' } },
        { id: 'sla', agent: 'cs', expert: 'cs_consultant', label: '合同签后服务 SLA 方案',
          goal: '设计合理的质量/交期/售后服务 SLA',
          profitImpact: { dimension: 'revenue', amount: 'SLA 承诺提升大客户续约率' } },
        { id: 'confirm', agent: 'sales', expert: 'sales_strategist', label: '销售负责人决策确认（HITL）',
          mode: 'human_in_loop',
          goal: '销售负责人确认方案和授权折扣',
          profitImpact: { dimension: 'revenue', amount: 'HITL 授权确保报价纪律' } },
      ],
      triggerPhrases: ['大客户', 'KA', '报价谈判', '宝马', '比亚迪', 'Tier-1'],
    },
    {
      id: 'listed_related_transaction', name: '关联交易合规审查', icon: '⚖️',
      description: '关联方认定 → 交易规模与披露义务 → 市场公允性 → 审批权限 → 公告草稿',
      mode: 'sequential',
      deliverable: '关联交易合规报告（披露义务判断 + 审批路径 + 公告草稿 + 整改建议）',
      successCriteria: ['关联方认定完整穿透', '披露义务阈值判断准确', '公告草稿格式符合交易所要求'],
      steps: [
        { id: 'related_party', agent: 'legal', expert: 'contract_reviewer', label: '关联方认定与关系图谱',
          goal: '穿透识别所有关联方及关系',
          profitImpact: { dimension: 'loss_avoidance', amount: '遗漏关联方认定将面临交易所处罚' } },
        { id: 'threshold', agent: 'invest', expert: 'investment_analyst', label: '交易规模与披露义务判断',
          goal: '按 A/H 股标准判断是否需要披露及审批级别',
          profitImpact: { dimension: 'loss_avoidance', amount: '准确判断避免因漏披被监管处罚' } },
        { id: 'fairness', agent: 'finance', expert: 'finance_accountant', label: '市场公允性分析',
          goal: '评估交易价格是否符合市场公允水平',
          profitImpact: { dimension: 'loss_avoidance', amount: '公允性分析抵御中小股东投诉' } },
        { id: 'approval', agent: 'legal', expert: 'contract_reviewer', label: '审批权限确认',
          goal: '确认是否需要董事会/股东大会审批',
          profitImpact: { dimension: 'loss_avoidance', amount: '跳过审批将导致决策无效' } },
        { id: 'announcement', agent: 'invest', expert: 'investment_analyst', label: '公告草稿生成',
          goal: '生成符合交易所格式的临时公告草稿',
          profitImpact: { dimension: 'cost_saving', amount: '公告草稿从 1 周 → 1 小时' } },
        { id: 'confirm', agent: 'legal', expert: 'civil_lawyer', label: '董秘/法务确认发布（HITL）',
          mode: 'human_in_loop',
          goal: '董秘或法务审核并确认公告发布',
          profitImpact: { dimension: 'loss_avoidance', amount: 'HITL 确认是上市公司合规底线' } },
      ],
      triggerPhrases: ['关联交易', '关联方', '披露义务', '股东大会审批', '关联方认定'],
    },
  ],
  scenarios: [
    { id: 'oem_contract_q', label: 'OEM 合同风险', icon: '📋',
      prompt: '客户发来代工协议，模具费归谁、IP 怎么约定、最大损失多少？',
      expectedOutcome: 'IP/模具风险标注 + 最大潜在损失量化 + 修改建议',
      expert: 'legal.contract_reviewer',
      profitImpact: { dimension: 'loss_avoidance', amount: '律所 5000 元/份 → ¥5/份' } },
    { id: 'export_rebate_q', label: '出口退税测算', icon: '🚢',
      prompt: '本月出口 80 万，退税率 13%，进项税 6 万，能退多少？',
      expectedOutcome: '免抵退税额 + 进项转出金额 + 申报注意事项',
      expert: 'finance.tax_consultant',
      profitImpact: { dimension: 'revenue', amount: '精确测算，不少退一分' } },
    { id: 'injury_q', label: '工伤赔偿计算', icon: '⛑️',
      prompt: '车间工人工伤六级，公司要赔多少？社保能报多少？',
      expectedOutcome: '赔偿金额分项 + 社保报销部分 + 公司实际承担',
      expert: 'legal.civil_lawyer',
      profitImpact: { dimension: 'loss_avoidance', amount: '律师 3000 元/案 → ¥5/次' } },
    { id: 'rd_q', label: '研发加计扣除', icon: '🔬',
      prompt: '今年研发投入 500 万，加计扣除能省多少企业所得税？',
      expectedOutcome: '加计扣除额 + 节税金额 + 需要准备的台账',
      expert: 'finance.tax_consultant',
      profitImpact: { dimension: 'revenue', amount: '多申报退税 18-35 万/年' } },
    { id: 'ka_q', label: '大客户报价策略', icon: '🤝',
      prompt: '宝马 Tier-1 询价，对方要压价 15%，怎么应对？',
      expectedOutcome: '底价边界分析 + 竞品差异化论据 + 异议处理话术',
      expert: 'sales.sales_strategist',
      profitImpact: { dimension: 'revenue', amount: '话术精准，保住利润空间' } },
    { id: 'related_tx_q', label: '关联交易合规', icon: '⚖️',
      prompt: '控股股东向公司采购 800 万，需要公告吗，需要股东大会审批吗？',
      expectedOutcome: '披露义务判断 + 审批级别 + 公告要点',
      expert: 'invest.investment_analyst',
      profitImpact: { dimension: 'loss_avoidance', amount: '合规判断避免监管处罚' } },
  ],
}

export default oemManufacturingSolution
